#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle_hol.pdf "HOL"
"$ISABELLE_TOOL" logo -o isabelle_hol.eps "HOL"

cp "$ISABELLE_HOME/doc-src/ProgProve/MyList.thy" .

"$ISABELLE_TOOL" latex -o sty
cp "$ISABELLE_HOME/doc-src/pdfsetup.sty" .

"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o bbl
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o "$FORMAT"
[ -f root.out ] && "$ISABELLE_HOME/doc-src/fixbookmarks" root.out
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o "$FORMAT"
