#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle_hol.pdf "HOL"
"$ISABELLE_TOOL" logo -o isabelle_hol.eps "HOL"

cp "$ISABELLE_HOME/doc-src/ProgProve/MyList.thy" .

"$ISABELLE_HOME/doc-src/prepare_document" "$FORMAT"

