#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle_sledgehammer.pdf "S/H"
"$ISABELLE_TOOL" logo -o isabelle_sledgehammer.eps "S/H"

cp "$ISABELLE_HOME/doc-src/iman.sty" .
cp "$ISABELLE_HOME/doc-src/manual.bib" .

"$ISABELLE_HOME/doc-src/prepare_document" "$FORMAT"

