#!/bin/bash
#
# Make Isabelle/JVM application bundle

THIS="$(cd "$(dirname "$0")"; pwd)"

APP="$THIS/Isabelle.app"

for NAME in Java MacOS PlugIns Resources
do
  mkdir -p "$APP/Contents/$NAME"
done

cp "$THIS/Info.plist" "$APP/Contents/."

for NAME in Pure.jar scala-library.jar scala-swing.jar
do
  ln -sf "../Resources/Isabelle/lib/classes/ext/$NAME" "$APP/Contents/Java"
done

cp -R "$THIS/Resources/." "$APP/Contents/Resources/."
cp "$THIS/../isabelle.icns" "$APP/Contents/Resources/."

ln -sf "../Resources/Isabelle/contrib/jdk-7u13/x86_64-darwin/jdk1.7.0_13.jdk" "$APP/Contents/PlugIns/jdk"

cp "$THIS/JavaAppLauncher" "$APP/Contents/MacOS/." && chmod +x "$APP/Contents/MacOS/JavaAppLauncher"

