#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo HOL

cp "$ISABELLE_HOME/src/Doc/proof.sty" .
cp "$ISABELLE_HOME/src/Doc/ttbox.sty" .
cp "$ISABELLE_HOME/src/Doc/manual.bib" .

cp "$ISABELLE_HOME/src/Doc/Tutorial/ToyList/ToyList1" .
cp "$ISABELLE_HOME/src/Doc/Tutorial/ToyList/ToyList2" .

"$ISABELLE_TOOL" latex -o sty
cp "$ISABELLE_HOME/src/Doc/pdfsetup.sty" .

"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o bbl
./isa-index root
"$ISABELLE_TOOL" latex -o "$FORMAT"
[ -f root.out ] && "$ISABELLE_HOME/src/Doc/fixbookmarks" root.out
"$ISABELLE_TOOL" latex -o "$FORMAT"
