#!/usr/bin/env bash

set -e

FORMAT="$1"
VARIANT="$2"

isabelle latex -o "$FORMAT"
isabelle latex -o bbl
isabelle latex -o "$FORMAT"
isabelle latex -o "$FORMAT"
./isa-index root
isabelle latex -o "$FORMAT"
