#!/usr/bin/env bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo HOL
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o bbl
./isa-index root
"$ISABELLE_TOOL" latex -o "$FORMAT"
[ -f root.out ] && "$ISABELLE_HOME/src/Doc/fixbookmarks" root.out
"$ISABELLE_TOOL" latex -o "$FORMAT"
