#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle.pdf ""
"$ISABELLE_TOOL" logo -o isabelle.eps ""

cp "$ISABELLE_HOME/doc-src/IsarRef/style.sty" .
cp "$ISABELLE_HOME/doc-src/iman.sty" .
cp "$ISABELLE_HOME/doc-src/extra.sty" .
cp "$ISABELLE_HOME/doc-src/isar.sty" .
cp "$ISABELLE_HOME/doc-src/ttbox.sty" .
cp "$ISABELLE_HOME/doc-src/underscore.sty" .
cp "$ISABELLE_HOME/doc-src/manual.bib" .

"$ISABELLE_TOOL" latex -o sty
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o bbl
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_HOME/doc-src/sedindex" root
"$ISABELLE_TOOL" latex -o "$FORMAT"
