#!/usr/bin/env bash
#
# Author: Makarius
#
# Generic Isabelle application wrapper.

if [ -L "$0" ]; then
  TARGET="$(LC_ALL=C ls -l "$0" | sed 's/.* -> //')"
  exec "$(cd "$(dirname "$0")"; cd "$(pwd -P)"; cd "$(dirname "$TARGET")"; pwd)/$(basename "$TARGET")" "$@"
fi


## settings

ISABELLE_HOME="$(cd "$(dirname "$0")"; pwd -P)"
source "$ISABELLE_HOME/lib/scripts/getsettings" || exit 2

unset ISABELLE_SETTINGS_PRESENT


## main

CLASSPATH="$(jvmpath "$CLASSPATH")"

exec "$ISABELLE_JAVA" \
  "-Disabelle.home=$(jvmpath "$ISABELLE_HOME")" \
  -jar "$(jvmpath "$ISABELLE_HOME/lib/classes/isabelle-scala.jar")" "$@"
