#
# $Id$
#
# IsaMakefile for PSV WS 2003/2004
#

SESSIONS = a1 a2 a3 a4 a5

## targets

default: sessions
sessions: $(SESSIONS)


## a1

a1: a1/generated/session.tex

a1/generated/session.tex: a1/ROOT.ML a1/*.thy
	isatool make

## a2

a2: a2/generated/session.tex

a2/generated/session.tex: a2/ROOT.ML a2/*.thy
	isatool make

## a3

a3: a3/generated/session.tex

a3/generated/session.tex: a3/ROOT.ML a3/*.thy
	isatool make

## a4

a4: a4/generated/session.tex

a4/generated/session.tex: a4/ROOT.ML a4/*.thy
	isatool make

## a5

a5: a5/generated/session.tex

a5/generated/session.tex: a5/ROOT.ML a5/*.thy
	isatool make

