title = Isabelle/VSCode extension
no_build = true
sources = \
  $ISABELLE_HOME/src/Pure/Build/browser_info.scala \
  $ISABELLE_HOME/src/Pure/General/bytes.scala \
  $ISABELLE_HOME/src/Pure/General/cache.scala \
  $ISABELLE_HOME/src/Pure/General/codepoint.scala \
  $ISABELLE_HOME/src/Pure/General/completion.scala \
  $ISABELLE_HOME/src/Pure/General/exn.scala \
  $ISABELLE_HOME/src/Pure/General/html.scala \
  $ISABELLE_HOME/src/Pure/General/js.scala \
  $ISABELLE_HOME/src/Pure/General/json.scala \
  $ISABELLE_HOME/src/Pure/General/mercurial.scala \
  $ISABELLE_HOME/src/Pure/General/message_digest.scala \
  $ISABELLE_HOME/src/Pure/General/multi_map.scala \
  $ISABELLE_HOME/src/Pure/General/output.scala \
  $ISABELLE_HOME/src/Pure/General/path.scala \
  $ISABELLE_HOME/src/Pure/General/position.scala \
  $ISABELLE_HOME/src/Pure/General/pretty.scala \
  $ISABELLE_HOME/src/Pure/General/properties.scala \
  $ISABELLE_HOME/src/Pure/General/scan.scala \
  $ISABELLE_HOME/src/Pure/General/space.scala \
  $ISABELLE_HOME/src/Pure/General/symbol.scala \
  $ISABELLE_HOME/src/Pure/General/time.scala \
  $ISABELLE_HOME/src/Pure/General/utf8.scala \
  $ISABELLE_HOME/src/Pure/General/value.scala \
  $ISABELLE_HOME/src/Pure/General/word.scala \
  $ISABELLE_HOME/src/Pure/PIDE/document_status.scala \
  $ISABELLE_HOME/src/Pure/PIDE/markup.scala \
  $ISABELLE_HOME/src/Pure/PIDE/protocol_message.scala \
  $ISABELLE_HOME/src/Pure/PIDE/rendering.scala \
  $ISABELLE_HOME/src/Pure/PIDE/text.scala \
  $ISABELLE_HOME/src/Pure/PIDE/xml.scala \
  $ISABELLE_HOME/src/Pure/PIDE/yxml.scala \
  $ISABELLE_HOME/src/Pure/ROOT.scala \
  $ISABELLE_HOME/src/Pure/System/isabelle_system.scala \
  $ISABELLE_HOME/src/Pure/System/platform.scala \
  $ISABELLE_HOME/src/Pure/System/scalajs.scala \
  $ISABELLE_HOME/src/Pure/library.scala \
  $ISABELLE_VSCODE_HOME/src/lsp.scala \
  $ISABELLE_VSCODE_HOME/src/language_server.scala \
  src/no_message_digest.scala \
  src/output_view.scala \
  src/dom_metric.scala \
  src/history_text_field.scala \
  src/pretty_text_area.scala \
  src/sledgehammer_view.scala \
  src/state_panel.scala \
  src/symbols_view.scala \
  src/webview_api.scala