#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

cp "$ISABELLE_HOME/doc-src/iman.sty" .
cp "$ISABELLE_HOME/doc-src/extra.sty" .
cp "$ISABELLE_HOME/doc-src/isar.sty" .
cp "$ISABELLE_HOME/doc-src/manual.bib" .

"$ISABELLE_HOME/doc-src/prepare_document" "$FORMAT"

