#!/bin/bash

THIS="$(cd "$(dirname "$0")"; echo "$PWD")"
SUPER="$(cd "$THIS"; cd ..; echo "$PWD")"
NAME="$(basename "$THIS")"

[ -h "$NAME" ] && { echo "$NAME is a symlink!"; exit 2; }

TAR=tar
type -path gtar >/dev/null && TAR=gtar

cd "$SUPER"
mkdir -p "$NAME/dist"


echo "*** ${NAME}_base.tar.gz"
"$TAR" czf "$NAME/dist/${NAME}_base.tar.gz" polyml "$NAME/LICENCE" "$NAME/bin"
ln -sf "${NAME}_base.tar.gz" "$NAME/dist/polyml_base.tar.gz"

for PLATFORM in sparc-solaris x86-linux
do
  echo "*** ${NAME}_${PLATFORM}.tar.gz"
  "$TAR" czf "$NAME/dist/${NAME}_${PLATFORM}.tar.gz" "$NAME/$PLATFORM"
  ln -sf "${NAME}_${PLATFORM}.tar.gz" "$NAME/dist/polyml_${PLATFORM}.tar.gz"
done
