#!/usr/bin/env bash
#
# Portable Poly/ML command-line tool

THIS="$(cd "$(dirname "$0")"; pwd)"

export DYLD_LIBRARY_PATH="$THIS:$DYLD_LIBRARY_PATH"

if type -p rlwrap > /dev/null
then
  exec rlwrap "$THIS/poly" "$@"
else
  exec "$THIS/poly" "$@"
fi
