#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle_isar.pdf "Isar"
"$ISABELLE_TOOL" logo -o isabelle_isar.eps "Isar"

cp "$ISABELLE_HOME/doc-src/iman.sty" .
cp "$ISABELLE_HOME/doc-src/extra.sty" .
cp "$ISABELLE_HOME/doc-src/isar.sty" .
cp "$ISABELLE_HOME/doc-src/proof.sty" .
cp "$ISABELLE_HOME/doc-src/manual.bib" .

for NAME in architecture adapt
do
  latex "$NAME"
  $ISABELLE_DVIPS -E -o "$NAME.eps" "$NAME.dvi"
  $ISABELLE_EPSTOPDF "$NAME.eps"
done

"$ISABELLE_TOOL" latex -o sty
cp "$ISABELLE_HOME/doc-src/pdfsetup.sty" .

"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o bbl
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_HOME/doc-src/sedindex" root
[ -f root.out ] && "$ISABELLE_HOME/doc-src/fixbookmarks" root.out
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o "$FORMAT"
