#!/usr/bin/env bash
#
# Author: Jasmin Blanchette
#
# DESCRIPTION: TPTP FOF version of Nitpick


PRG="$(basename "$0")"

function usage() {
  echo
  echo "Usage: isabelle $PRG FILES"
  echo
  echo "  Runs Nitrox on a CNF or FOF TPTP problem."
  echo
  exit 1
}

[ "$#" -eq 0 -o "$1" = "-?" ] && usage

SCRATCH="Scratch_${PRG}_$$_${RANDOM}"

for FILE in "$@"
do
  echo "theory $SCRATCH imports \"Nitpick\" begin ML {* Nitrox.pick_nits_in_fof_file \"$FILE\" *} end;" \
    > /tmp/$SCRATCH.thy
  "$ISABELLE_PROCESS" -e "use_thy \"/tmp/$SCRATCH\"; exit 1;"
done
