#!/usr/bin/env bash

set -e

FORMAT="$1"
VARIANT="$2"

# ad-hoc patching of temporary path from sources
perl -i -pe 's/\\isakeyword\{module\{\\isacharunderscore\}name\}\\ Example\\ \\isakeyword\{file\}\\ \{\\isachardoublequoteopen\}.*\{\\isacharslash\}/\\isakeyword{module{\\isacharunderscore}name}\\ Example\\ \\isakeyword{file}\\ {\\isachardoublequoteopen}examples{\\isacharslash}/g' \
  Introduction.tex

"$ISABELLE_TOOL" logo Isar
"$ISABELLE_HOME/src/Doc/prepare_document" "$FORMAT"

# clean up afterwards
rm -rf "${ISABELLE_TMP}/examples"
