#!/usr/bin/env bash

set -e

FORMAT="$1"
VARIANT="$2"

# ad-hoc patching of temporary path from sources
perl -i -pe 's/\{\\isachardollar\}ISABELLE\{\\isacharunderscore\}TMP\{\\isacharslash\}examples/examples/g' *.tex

"$ISABELLE_HOME/src/Doc/prepare_document" "$FORMAT"

# clean up afterwards
rm -rf "${ISABELLE_TMP}/examples"
