#!/usr/bin/env bash
#
# Author: Lukas Bulwahn, TU Muenchen, 2010
#
# Determine SWI-Prolog version

if [ "$EXEC_SWIPL" = "" ]; then
  echo ""
else
  VERSION="$("$EXEC_SWIPL" --version)"
  REGEXP='^SWI-Prolog version ([0-9\.]*) for .*$'
  if [[ "$VERSION" =~ $REGEXP ]]; then
    echo "${BASH_REMATCH[1]}"
  else
    echo undefined
  fi
fi
