#!/usr/bin/env bash
#
# Author: Lukas Bulwahn, TU Muenchen, 2010
#
# Determine SWI-Prolog version

if [ "$ISABELLE_SWIPL" != "" ]; then
  VERSION="$("$ISABELLE_SWIPL" --version)"
  REGEXP='^SWI-Prolog version ([0-9\.]*) for .*$'
  if [[ "$VERSION" =~ $REGEXP ]]; then
    echo -n "${BASH_REMATCH[1]}"
  else
    echo -n undefined
  fi
fi
