#!/usr/bin/env bash
#
# Author: Lukas Bulwahn, TU Muenchen, 2010
#
# Determine SWI-Prolog version

if [ "$EXEC_SWIPL" = "" ]; then
  echo ""
else
  # FIXME does not allow spaces in $EXEC_SWIPL
  # FIXME "expr match" not portable
  # FIXME prefer $(...) in bash
  VERSION=`$EXEC_SWIPL --version`
  echo `expr match "$VERSION" 'SWI-Prolog version \([0-9\.]*\)'`
fi
