#!/usr/bin/env bash
#
# Author: Florian Haftmann, TU Muenchen
#
# DESCRIPTION: pie chart with Mercurial churn statistics

ALIAS="${1:-$ISABELLE_HOME/Admin/user-aliases}"
shift

SCRIPT="$ISABELLE_HOME/Admin/lib/scripts/churn_pie"

cd "$(dirname "$ALIAS")"

"${HG:-hg}" churn --aliases "$ALIAS" | "$SCRIPT" "$@"
