#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: update standard keyword files for Emacs Proof General
# (Proof General legacy)

isabelle_admin_build jars || exit $?

declare -a JAVA_ARGS; eval "JAVA_ARGS=($ISABELLE_BUILD_JAVA_OPTIONS)"

cd "$ISABELLE_HOME/etc"

"$ISABELLE_TOOL" java "${JAVA_ARGS[@]}" isabelle.Keywords update_keywords

