#!/usr/bin/env bash
#
# Author: Makarius
#
# Main Isabelle application wrapper.

if [ -L "$0" ]; then
  TARGET="$(LC_ALL=C ls -l "$0" | sed 's/.* -> //')"
  exec "$(cd "$(dirname "$0")"; cd "$(pwd -P)"; cd "$(dirname "$TARGET")"; pwd)/$(basename "$TARGET")" "$@"
fi


## settings

PRG="$(basename "$0")"

ISABELLE_HOME="$(cd "$(dirname "$0")"; cd "$(pwd -P)"; pwd)"
source "$ISABELLE_HOME/lib/scripts/getsettings" || exit 2


## main

declare -a JAVA_ARGS
JAVA_ARGS=({JAVA_ARGS})

exec "$ISABELLE_HOME/bin/isabelle" java "${JAVA_ARGS[@]}" \
  -classpath "$ISABELLE_HOME/src/Tools/jEdit/dist/jedit.jar" isabelle.Main "$@"

