#!/usr/bin/env bash
#
# Author: Makarius
#
# Main Isabelle application script.

# minimal Isabelle environment

ISABELLE_HOME="$(cd "$(dirname "$0")"; cd "$(pwd -P)/../.."; pwd)"
source "$ISABELLE_HOME/lib/scripts/isabelle-platform"


# Java runtime options

declare -a JAVA_OPTIONS=($(perl -p -e 's,#.*$,,g;' "$ISABELLE_HOME/Isabelle.options"))


# main

#paranoia setting -- avoid problems of Java/Swing versus XIM/IBus etc.
unset XMODIFIERS

exec "$ISABELLE_HOME/contrib/jdk/x86_64-linux/jre/bin/java" \
  "-Disabelle.root=$ISABELLE_HOME" "${JAVA_OPTIONS[@]}" \
  -classpath "{CLASSPATH}" \
  "-splash:$ISABELLE_HOME/lib/logo/isabelle.gif" \
  isabelle.Main "$@"
