#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle_hol.pdf "HOL"
"$ISABELLE_TOOL" logo -o isabelle_hol.eps "HOL"

cp "$ISABELLE_HOME/src/Doc/iman.sty" .
cp "$ISABELLE_HOME/src/Doc/extra.sty" .
cp "$ISABELLE_HOME/src/Doc/ttbox.sty" .
cp "$ISABELLE_HOME/src/Doc/proof.sty" .
cp "$ISABELLE_HOME/src/Doc/manual.bib" .
cp "$ISABELLE_HOME/src/Doc/Logics/document/syntax.tex" .

"$ISABELLE_HOME/src/Doc/prepare_document" "$FORMAT"

