.TH GEN-ISADOC 1 "September 3, 1995"
.AT 3
.SH NAME
gen-isadoc \- a perl 4.x script
.SH SYNOPSIS
.B gen-isadoc [options] convtable-file keytable-file
.SH DESCRIPTION
.I gen-isadoc
reads the 
.I convtable-file
and the
.I keytable-file,
generates the documentation files
.I fkmatrix.tex,
.I fontindex.tex,
and
.I keyindex.tex,
and makes the corresponding .dvi files.
Options must be seperated by blanks.
.SH OPTIONS
.TP 5
.B \-d "\t"
turn on debug mode. The script will tell you what it is doing.

.TP 5
.B \-dd "\t"
turn on double debug mode. This is very verbose.
.TP 5
.B \-2e "\t"
produce LaTeX2e code for the documentation. 

.SH ENVIRONMENT
No environment variables are used.
.SH FILES
None.
.SH AUTHOR
Franz Regensburger
.SH "SEE ALSO"
There is variable USE2E in the 
.I Makefile 
in the 
.I root directory 
of the 8bit package. The contents of this variable is passed to the 
.I Makefile 
in the 
.I subdirectory config 
which uses the switch in the call to 
.I gen-isadoc
when make is runned.
.SH DIAGNOSTICS

.SH BUGS

