.TH ISAPAL 1 "March 30, 1995"
.AT 3
.SH NAME
isapal \- a perl4.x script
.SH SYNOPSIS
.B isapal 
.SH DESCRIPTION
.I Isapal
prints the 8bit font for Isabelle to stdout. Usually the script is
only used in an environment that is capable of showing the 8bit font,
e\.g\. inside an Isabelle terminal \fIisaterm\fP.
.SH ENVIRONMENT
No environment variables are used.
.SH FILES
None.
.SH AUTHOR
Franz Regensburger
.SH SEE ALSO
Documentation in the 
.I doc
directory of the 8bit package.

.SH DIAGNOSTICS

.SH BUGS

