#!/bin/bash
# $Id$

THIS="$(cd "$(dirname "$0")"; pwd)"
SUPER="$(cd "$THIS/.."; pwd)"

LOG="$THIS/log"

cd "$THIS/cvs"
cvs up -dAP >> "$LOG" || exit 2


case $(hostname) in

atbroy51)
export HG=/home/isabelle/html-data/isabelle-repos/mercurial-atbroy51/bin/hg
export PYTHONPATH=/home/isabelle/html-data/isabelle-repos/mercurial-atbroy51/lib/python2.4/site-packages
;;

atbroy100)
export HG=/home/isabelle/html-data/isabelle-repos/mercurial-atbroy100/bin/hg
export PYTHONPATH=/home/isabelle/html-data/isabelle-repos/mercurial-atbroy100/lib64/python2.4/site-packages
;;

esac

export HGRCPATH="$THIS/cvs/Admin/Mercurial/hgrc"

cd "$THIS"
"$HG" convert --filemap cvs/Admin/Mercurial/filemap cvs hg >> "$LOG" || exit 2

[ -e hg/.hg/hgrc ] || ln -s ../../cvs/Admin/Mercurial/hgrc hg/.hg/hgrc
