#!/bin/bash
# $Id$

THIS="$(cd "$(dirname "$0")"; pwd)"
SUPER="$(cd "$THIS/.."; pwd)"

cd "$THIS/cvs"
cvs up -dAP || exit 2


case $(hostname) in

atbroy51)
MERCURIAL=/home/isabelle/html-data/isabelle-repos/mercurial-atbroy51/bin/hg
export PYTHONPATH=/home/isabelle/html-data/isabelle-repos/mercurial-atbroy51/lib/python2.4/site-packages
;;

atbroy100)
MERCURIAL=/home/isabelle/html-data/isabelle-repos/mercurial-atbroy100/bin/hg
export PYTHONPATH=/home/isabelle/html-data/isabelle-repos/mercurial-atbroy100/lib64/python2.4/site-packages
;;

esac

cd "$THIS"
"$MERCURIAL" convert --filemap cvs/Admin/Mercurial/filemap cvs hg
