#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo ZF

cp "$ISABELLE_HOME/src/Doc/isar.sty" .
cp "$ISABELLE_HOME/src/Doc/ttbox.sty" .
cp "$ISABELLE_HOME/src/Doc/proof.sty" .
cp "$ISABELLE_HOME/src/Doc/manual.bib" .
cp "$ISABELLE_HOME/src/Doc/Logics/document/syntax.tex" .

"$ISABELLE_HOME/src/Doc/prepare_document" "$FORMAT"

