#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle.pdf ""
"$ISABELLE_TOOL" logo -o isabelle.eps ""

cp "$ISABELLE_HOME/doc-src/iman.sty" .
cp "$ISABELLE_HOME/doc-src/extra.sty" .
cp "$ISABELLE_HOME/doc-src/ttbox.sty" .
cp "$ISABELLE_HOME/doc-src/proof.sty" .
cp "$ISABELLE_HOME/doc-src/manual.bib" .

"$ISABELLE_HOME/doc-src/prepare_document" "$FORMAT"

