#!/usr/bin/env bash
#
# DESCRIPTION: start the main Isabelle cronjob

THIS="$(cd "$(dirname "$0")"; pwd)"

source "$HOME/.bashrc"

export ISABELLE_IDENTIFIER="cronjob"
"$THIS/../build" jars_fresh || exit $?

exec "$THIS/../../bin/isabelle_java" "-Duser.timezone=Europe/Berlin" isabelle.Isabelle_Cronjob "$@"
