#!/bin/bash
#
# self-update of the administrative isabelle repository
#
# Need to copy this file manually to $HOME/cronjob in order to
# avoid overwriting the running self_update by itself!

source "$HOME/.bashrc"

cd "$HOME/cronjob"
mkdir -p run log

hg -R isabelle pull "https://isabelle.in.tum.de/repos/isabelle" -q || echo "self_update pull failed"
hg -R isabelle update -C -q || echo "self_update update failed"
isabelle/bin/isabelle components -a || echo "self_update components failed"
