#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle_zf.pdf "ZF"
"$ISABELLE_TOOL" logo -o isabelle_zf.eps "ZF"

cp "$ISABELLE_HOME/doc-src/isar.sty" .
cp "$ISABELLE_HOME/doc-src/ttbox.sty" .
cp "$ISABELLE_HOME/doc-src/proof.sty" .
cp "$ISABELLE_HOME/doc-src/manual.bib" .
cp "$ISABELLE_HOME/doc-src/Logics/document/syntax.tex" .

"$ISABELLE_HOME/doc-src/prepare_document" "$FORMAT"

