#!/bin/bash
#
# Make Isabelle application bundle

THIS="$(cd "$(dirname "$0")"; pwd)"

PLATYPUS_APP="/Applications/Platypus-4.0/Platypus.app"
COCOADIALOG_APP="/Applications/CocoaDialog.app"

"$PLATYPUS_APP/Contents/Resources/platypus" \
  -a Isabelle -u Isabelle \
  -I "de.tum.in.isabelle" \
  -i "$THIS/../isabelle.icns" \
  -p /bin/bash \
  -c "$THIS/script" \
  -o None \
  -f "$COCOADIALOG_APP" \
  "$PWD/Isabelle.app"
