section \<open>A finite subgroup of the multiplicative group of a field is cyclic\<close>

theory Field_Mult_Cyclic
  imports Poly_Ring Group_Operations
begin

text \<open>In particular the multiplicative group of a finite field (e.g.\ \<open>GF(p\<^sup>n)\<close>) is cyclic.
  The argument splits into a group-theoretic part and a field-theoretic part.
  If a finite group @{term G} satisfies the
  \<^emph>\<open>root bound\<close> that for every @{term "n > 0"} at most @{term n} elements @{term x} satisfy
  \<open>x\<^sup>n = 1\<close>, then @{term G} is cyclic.  The field part supplies the root bound: the elements
  @{term x} of the multiplicative group with \<open>x\<^sup>n = 1\<close> are roots of the polynomial \<open>X\<^sup>n - 1\<close>,
  and a field has at most @{term n} such roots.\<close>

subsection \<open>The order of a power in a finite group\<close>

context Group
begin

text \<open>In a finite group, the order of @{term "power a k"} is @{term "element_order a div gcd (element_order a) k"}.
  This is the key computation behind counting the elements of each order in a cyclic group.\<close>

lemma element_order_power:
  assumes fin: "finite G" and aG: "a \<in> G"
  shows "element_order (power a k) = element_order a div gcd (element_order a) k"
proof -
  define e where "e = element_order a"
  define d where "d = gcd e k"
  have e_pos: "e > 0" unfolding e_def using element_order_pos[OF fin aG] .
  have ak: "power a k \<in> G" using aG by simp
  have pow_iff: "power (power a k) m = \<one> \<longleftrightarrow> (e div d) dvd m" for m
  proof -
    have step: "power (power a k) m = \<one> \<longleftrightarrow> e dvd (k * m)"
      using aG e_def element_order_dvd fin power_mult power_element_order power_unit
      by (metis dvd_def)
    \<comment> \<open>Now reduce the divisibility using @{term d}.\<close>
    have d_pos: "d > 0" unfolding d_def using e_pos by simp
    have d_dvd_e: "d dvd e" and d_dvd_k: "d dvd k" unfolding d_def by auto
    have "coprime (e div d) (k div d)"
      unfolding d_def using e_pos by (simp add: div_gcd_coprime)
    with step coprime_dvd_mult_right_iff d_dvd_e d_dvd_k show ?thesis
      by fastforce
  qed
  then show ?thesis
    using ak d_def e_def element_order_dvd fin power_element_order
    by (metis gcd_nat.asym gcd_nat.refl)
qed

end


subsection \<open>Counting elements of each order in a cyclic group\<close>

context Group
begin

text \<open>The elements of order exactly @{term e} in the cyclic group generated by @{term a}
  (where @{term a} has order @{term e}) are exactly its generators: the powers @{term "power a k"}
  with @{term k} below @{term e} and coprime to it.\<close>

lemma card_order_e_in_cyclic:
  assumes fin: "finite G" and aG: "a \<in> G" and ord_a: "element_order a = e"
  shows "card {x \<in> cyclic_subgroup a. element_order x = e} = card {k. k < e \<and> gcd e k = 1}"
proof -
  have e_pos: "e > 0" 
    using ord_a element_order_pos[OF fin aG] by simp
  have set_eq: "{x \<in> cyclic_subgroup a. element_order x = e}
              = power a ` {k. k < e \<and> gcd e k = 1}" (is "?L=?R")
  proof
    show "?L \<subseteq> ?R"
    proof
      fix x assume xc: "x \<in> ?L"
      then obtain k where xk: "x = power a k" and kl: "k < e"
        unfolding cyclic_subgroup_def ord_a by auto
      have "element_order (power a k) = e"
        using element_order_power[OF fin aG] ord_a xc xk by blast
      then have "gcd e k = 1"
        by (simp add: aG div_eq_dividend_iff e_pos element_order_power fin ord_a)
      then show "x \<in> ?R" using xk kl by auto
    qed
  qed (auto simp: cyclic_subgroup_def aG element_order_power fin ord_a)
  \<comment> \<open>@{term "power a"} is injective on @{term "{..<e}"}.\<close>
  have "inj_on (power a) {..<e}" using power_inj_on_order[OF fin aG] ord_a by simp
  then have inj: "inj_on (power a) {k. k < e \<and> gcd e k = 1}"
    by (rule inj_on_subset) (auto simp: lessThan_def)
  show "card {x \<in> cyclic_subgroup a. element_order x = e} = card {k. k < e \<and> gcd e k = 1}"
    using set_eq inj card_image by auto
qed

end

subsection \<open>Counting the Residues Coprime to a Modulus\<close>

text \<open>
  The cyclicity criterion for a finite group needs two arithmetic facts about the number of
  residues below @{term e} coprime to @{term e}: that it is positive, and that summing it over the
  divisors of @{term d} recovers @{term d}.
\<close>

lemma coprime_count_pos:
  fixes e :: nat
  assumes "0 < e" shows "0 < card {k. k < e \<and> gcd e k = 1}"
    using Suc_lessI [OF assms] by (fastforce simp: card_gt_0_iff)

text \<open>The residues below @{term d} whose greatest common divisor with @{term d} is exactly @{term f}
  are the multiples @{term "j * f"} of @{term f} by residues below @{term "d div f"} coprime to it.\<close>
lemma card_gcd_class:
  fixes d f :: nat
  assumes d: "0 < d" and f: "f dvd d"
  shows "card {j. j < d div f \<and> gcd (d div f) j = 1} = card {k. k < d \<and> gcd k d = f}"
proof (rule bij_betw_same_card)
  have fpos: "0 < f" using d f by (auto intro: dvd_pos_nat)
  have deq: "d div f * f = d" using f by simp
  show "bij_betw (\<lambda>j. j * f) {j. j < d div f \<and> gcd (d div f) j = 1} {k. k < d \<and> gcd k d = f}"
    unfolding bij_betw_def
  proof
    show "inj_on (\<lambda>j. j * f) {j. j < d div f \<and> gcd (d div f) j = 1}"
      using fpos by (simp add: inj_on_def)
  next
    show "(\<lambda>j. j * f) ` {j. j < d div f \<and> gcd (d div f) j = 1} = {k. k < d \<and> gcd k d = f}"
    proof (intro set_eqI iffI)
      fix k assume "k \<in> (\<lambda>j. j * f) ` {j. j < d div f \<and> gcd (d div f) j = 1}"
      then obtain j where j: "j < d div f" "gcd (d div f) j = 1" and k: "k = j * f" by auto
      from j(1) fpos have "j * f < d div f * f" by (rule mult_less_mono1)
      then have "k < d" using k deq by simp
      moreover have "gcd k d = f"
      proof -
        have "gcd k d = gcd (j * f) (d div f * f)" using k deq by simp
        also have "\<dots> = gcd (d div f) j * f" by (simp add: gcd_mult_right)
        also have "\<dots> = f" using j(2) by simp
        finally show ?thesis .
      qed
      ultimately show "k \<in> {k. k < d \<and> gcd k d = f}" by simp
    next
      fix k assume "k \<in> {k. k < d \<and> gcd k d = f}"
      then have k: "k < d" and g: "gcd k d = f" and keq: "k div f * f = k" by auto
      have "gcd (d div f) (k div f) * f = f" using g
        using deq keq by (metis gcd.commute gcd_mult_distrib_nat mult.commute)
      moreover have "k div f < d div f" using k fpos f by (simp add: div_less_iff_less_mult)
      ultimately show "k \<in> (\<lambda>j. j * f) ` {j. j < d div f \<and> gcd (d div f) j = 1}"
        using keq fpos by (force simp: image_iff)
    qed
  qed
qed

text \<open>Summing the coprime counts over the divisors of @{term d} recovers @{term d}: the residues
  below @{term d} are partitioned by their greatest common divisor with @{term d}.\<close>
theorem coprime_count_divisor_sum:
  fixes d :: nat
  assumes d: "0 < d"
  shows "(\<Sum>e | e dvd d. card {k. k < e \<and> gcd e k = 1}) = d"
proof -
  have part: "{k. k < d} = (\<Union>f \<in> {f. f dvd d}. {k. k < d \<and> gcd k d = f})"
    by auto
  have "d = card {k. k < d}" by simp
  also have "\<dots> = (\<Sum>f | f dvd d. card {k. k < d \<and> gcd k d = f})"
    unfolding part using d by (intro card_UN_disjoint) auto
  also have "\<dots> = (\<Sum>f | f dvd d. card {j. j < d div f \<and> gcd (d div f) j = 1})"
    using card_gcd_class [OF d] by simp
  also have "\<dots> = (\<Sum>e | e dvd d. card {k. k < e \<and> gcd e k = 1})"
  proof (rule sum.reindex_bij_witness [of _ "\<lambda>e. d div e" "\<lambda>f. d div f"])
  qed (use d div_div_eq_right in auto)
  finally show ?thesis by simp
qed

subsection \<open>The abstract group criterion for being cyclic\<close>

context Group
begin

text \<open>The set of elements of order exactly @{term e} in a finite group.\<close>

text \<open>Every element of a finite group has order dividing @{term "card G"}, so the group is
  partitioned by order over the divisors of @{term "card G"}.\<close>

lemma card_G_sum_orders:
  assumes fin: "finite G"
  shows "card G = (\<Sum>e | e dvd card G. card {x \<in> G. element_order x = e})"
proof -
  have part: "G = (\<Union>e \<in> {e. e dvd card G}. {x \<in> G. element_order x = e})"
    using element_order_dvd_card[OF fin] by auto
  have "card G > 0"
    using fin card_gt_0_iff unit_closed by blast
  then have fin_div: "finite {e. e dvd card G}" by (rule finite_divisors_nat)
  have "card G = card (\<Union>e \<in> {e. e dvd card G}. {x \<in> G. element_order x = e})"
    using part by simp
  also have "\<dots> = (\<Sum>e | e dvd card G. card {x \<in> G. element_order x = e})"
    using fin by (intro card_UN_disjoint fin_div) auto
  finally show ?thesis .
qed

text \<open>The root bound: for each positive @{term n}, at most @{term n} elements satisfy \<open>x\<^sup>n = 1\<close>.
  Under this hypothesis, at most @{term "card {k. k < e \<and> gcd e k = 1}"} elements have order
  exactly @{term e}.\<close>

lemma card_order_e_le_coprime_count:
  assumes fin: "finite G"
    and bound: "\<And>n. n > 0 \<Longrightarrow> card {x \<in> G. power x n = \<one>} \<le> n"
    and e_pos: "e > 0"
  shows "card {x \<in> G. element_order x = e} \<le> card {k. k < e \<and> gcd e k = 1}"
proof (cases "{x \<in> G. element_order x = e} = {}")
  case True show ?thesis
    by (simp add: True)
next
  case False
  then obtain a where aG: "a \<in> G" and ord_a: "element_order a = e" by auto
  \<comment> \<open>The @{term e} powers of @{term a} all solve \<open>x\<^sup>e = 1\<close>; the bound forces them to be \<^emph>\<open>all\<close> solutions.\<close>
  have cyc_sub: "cyclic_subgroup a \<subseteq> {x \<in> G. power x e = \<one>}"
  proof
    fix x assume "x \<in> cyclic_subgroup a"
    then obtain k where xk: "x = power a k" and "k < e"
      unfolding cyclic_subgroup_def ord_a by auto
    have "power x e = \<one>"
      using aG fin power_mult ord_a power_element_order power_unit xk by (metis mult.commute) 
    with xk aG show "x \<in> {x \<in> G. power x e = \<one>}" by simp
  qed
  have "card (cyclic_subgroup a) = e"
    using card_cyclic_subgroup[OF fin aG] ord_a by simp
  with cyc_sub bound[OF e_pos] fin have *: "cyclic_subgroup a = {x \<in> G. power x e = \<one>}"
    by (simp add: card_seteq)
  have "{x \<in> G. element_order x = e} = {x \<in> cyclic_subgroup a. element_order x = e}"
    by (auto simp: * fin power_element_order)
  then show ?thesis
    using card_order_e_in_cyclic[OF fin aG ord_a] by simp
qed

text \<open>The abstract criterion: a finite group satisfying the root bound is cyclic.\<close>

theorem cyclic_of_root_bound:
  assumes fin: "finite G" and ne: "G \<noteq> {}"
    and bound: "\<And>n. n > 0 \<Longrightarrow> card {x \<in> G. power x n = \<one>} \<le> n"
  shows "\<exists>g \<in> G. cyclic_subgroup g = G"
proof -
  define d where "d = card G"
  have d_pos: "d > 0" unfolding d_def using fin ne by (simp add: card_gt_0_iff)
  \<comment> \<open>Every order divides @{term d}; summing over divisors gives @{term d}.\<close>
  have sum_orders: "(\<Sum>e | e dvd d. card {x \<in> G. element_order x = e}) = d"
    unfolding d_def using card_G_sum_orders[OF fin] by simp
  have sum_counts: "(\<Sum>e | e dvd d. card {k. k < e \<and> gcd e k = 1}) = d"
    using coprime_count_divisor_sum [OF d_pos] by simp
  have fin_div: "finite {e. e dvd d}"
    using d_pos finite_divisors_nat by (metis gr_implies_not0)
  have le: "card {x \<in> G. element_order x = e} \<le> card {k. k < e \<and> gcd e k = 1}"
    if "e dvd d" for e
    using bound card_0_eq card_order_e_le_coprime_count d_def fin that by fastforce
  have eq_all: "card {x \<in> G. element_order x = e0} = card {k. k < e0 \<and> gcd e0 k = 1}"
    if "e0 dvd d" for e0
  proof (rule ccontr)
    assume neq: "card {x \<in> G. element_order x = e0} \<noteq> card {k. k < e0 \<and> gcd e0 k = 1}"
    with le that have strict: "card {x \<in> G. element_order x = e0}
                                 < card {k. k < e0 \<and> gcd e0 k = 1}" by force
    have "(\<Sum>e | e dvd d. card {x \<in> G. element_order x = e})
        < (\<Sum>e | e dvd d. card {k. k < e \<and> gcd e k = 1})"
      by (intro sum_strict_mono_ex1 fin_div) (use that strict le in auto)
    with sum_orders sum_counts show False by simp
  qed
  \<comment> \<open>In particular there is an element of order @{term d}, which generates @{term G}.\<close>
  have "card {x \<in> G. element_order x = d} = card {k. k < d \<and> gcd d k = 1}"
    using eq_all by simp
  moreover have "card {k. k < d \<and> gcd d k = 1} > 0" using d_pos by (rule coprime_count_pos)
  ultimately have "{x \<in> G. element_order x = d} \<noteq> {}" by (metis card.empty less_irrefl)
  then obtain g where gG: "g \<in> G" and gord: "element_order g = d" by auto
  have "cyclic_subgroup g = G"
    by (simp add: card_cyclic_subgroup card_subset_eq cyclic_subgroup_subset d_def fin gG gord)
  with gG show ?thesis by blast
qed

end


subsection \<open>The multiplicative group of a field and the root bound\<close>

context Field
begin

text \<open>The nonzero elements of the field.\<close>

definition Fstar :: "'a set"
  where "Fstar = R - {\<zero>}"

lemma Fstar_iff [simp]: "x \<in> Fstar \<longleftrightarrow> x \<in> R \<and> x \<noteq> \<zero>"
  unfolding Fstar_def by auto

lemma one_in_Fstar: "\<one> \<in> Fstar"
  using nontrivial by simp

text \<open>The nonzero elements form a group under multiplication.\<close>

theorem Group_Fstar: "Group Fstar (\<cdot>) \<one>"
proof (intro GroupI one_in_Fstar)
  fix a b assume "a \<in> Fstar" "b \<in> Fstar"
  then show "a \<cdot> b \<in> Fstar"
    using local.no_zero_divisors by auto 
next
  fix u assume "u \<in> Fstar"
  then show "\<exists>v \<in> Fstar. u \<cdot> v = \<one> \<and> v \<cdot> u = \<one>"
    using field_inverse nontrivial by fastforce
qed (auto simp: multiplicative.associative)

end


subsection \<open>The polynomial root bound, via the polynomial ring\<close>

text \<open>The number of \<open>n\<close>th roots of unity in a field is at most \<open>n\<close>.  Rather than reproving a bound on
  polynomial roots by hand, we reuse @{thm [source] Field.card_roots_le_degree} from
  \<open>Poly_Ring\<close>: the \<open>n\<close>th roots of unity are exactly the roots of the polynomial
  \<open>X\<^sup>n - 1\<close>, which is nonzero of degree \<open>n\<close>.\<close>

context Field
begin

text \<open>The ring power @{const rpow} of \<open>Poly_Ring\<close> agrees with the multiplicative
  group power.\<close>
lemma rpow_eq_power: "rpow x n = multiplicative.power x n"
  by (induction n) simp_all

text \<open>The polynomial \<open>X\<^sup>n - 1\<close>, as a coefficient sequence: @{term "- \<one>"} at 0, @{term \<one>} at @{term n},
  and @{term \<zero>} elsewhere (valid for @{term "n > 0"}).\<close>
definition xn_minus_1 :: "nat \<Rightarrow> (nat \<Rightarrow> 'a)"
  where "xn_minus_1 n \<equiv> (\<lambda>i. if i = 0 then - \<one> else if i = n then \<one> else \<zero>)"

lemma xn_minus_1_closed: "xn_minus_1 n \<in> poly_carrier"
proof (rule poly_carrierI)
  have "{i. xn_minus_1 n i \<noteq> \<zero>} \<subseteq> {0, n}" by (auto simp: xn_minus_1_def)
  then show "finite {i. xn_minus_1 n i \<noteq> \<zero>}" by (rule finite_subset) simp
  show "\<And>i. xn_minus_1 n i \<in> R" by (simp add: xn_minus_1_def)
qed

lemma xn_minus_1_coeff: "xn_minus_1 n i \<in> R"
  by (simp add: xn_minus_1_def)

lemma degree_xn_minus_1:
  assumes n: "n > 0" shows "degree (xn_minus_1 n) = n"
proof (rule le_antisym)
  show "degree (xn_minus_1 n) \<le> n"
    using degree_le_iff xn_minus_1_closed xn_minus_1_def by auto
  then show "n \<le> degree (xn_minus_1 n)"
    using coeff_gt_degree le_eq_less_or_eq nontrivial xn_minus_1_closed xn_minus_1_def by fastforce
qed

lemma xn_minus_1_nonzero:
  assumes n: "n > 0" shows "xn_minus_1 n \<noteq> \<zero>\<^sub>P"
  by (metis degree_xn_minus_1 degree_zero less_zeroE n)

text \<open>Its value at @{term x} is @{term "multiplicative.power x n - \<one>"}.\<close>
lemma eval_xn_minus_1:
  assumes n: "n > 0" and x: "x \<in> R"
  shows "eval x (xn_minus_1 n) = multiplicative.power x n + (- \<one>)"
proof -
  have "eval x (xn_minus_1 n) = additive.fincomp (\<lambda>i. xn_minus_1 n i \<cdot> rpow x i) {..n}"
    using degree_xn_minus_1 local.eval_def n by force
  also have "\<dots> = additive.fincomp (\<lambda>i. xn_minus_1 n i \<cdot> rpow x i) {0, n}"
    using x
    by (intro additive.fincomp_mono_neutral_cong_right) (auto simp: xn_minus_1_def xn_minus_1_coeff)
  also have "\<dots> = (- \<one>) + multiplicative.power x n"
    using n x by (simp add: xn_minus_1_coeff xn_minus_1_def rpow_eq_power)
  also have "\<dots> = multiplicative.power x n + (- \<one>)"
    using x by (simp add: additive.commutative)
  finally show ?thesis .
qed

text \<open>The roots of unity are exactly the roots of \<open>X\<^sup>n - 1\<close>.\<close>
lemma card_nth_roots_of_unity:
  assumes n: "n > 0"
  shows "finite {x \<in> R. multiplicative.power x n = \<one>}
       \<and> card {x \<in> R. multiplicative.power x n = \<one>} \<le> n"
proof -
  have "multiplicative.power x n = \<one>"
    if "x \<in> R" and "multiplicative.power x n - \<one> = \<zero>" for x 
  proof -
    have "multiplicative.power x n = (multiplicative.power x n + (- \<one>)) + \<one>"
      using additive.invertible_left_inverse[of \<one>] \<open>x \<in> R\<close> by (simp add: additive.associative)
    also have "\<dots> = \<one>" using that by (simp add: additive.associative)
    finally show "multiplicative.power x n = \<one>" .
  qed
  then have "{x \<in> R. multiplicative.power x n = \<one>} = {x \<in> R. eval x (xn_minus_1 n) = \<zero>}"
    by (auto simp: eval_xn_minus_1 n)
  then show ?thesis 
    using degree_xn_minus_1[OF n] xn_minus_1_closed xn_minus_1_nonzero[OF n] card_roots_le_degree 
    by force
qed

end



subsection \<open>The main theorem\<close>

text \<open>The @{term Fstar}-power (multiplicative power in the group of nonzero elements) coincides
  with the field's multiplicative power, so the root bound transfers to the group.\<close>

context Field
begin

lemma Fstar_power_eq:
  "Monoid.power (\<cdot>) \<one> x n = multiplicative.power x n"
  by (simp only: Monoid.power_def)

text \<open>Any finite subgroup of the multiplicative group of a field is cyclic.\<close>

theorem finite_subgroup_Fstar_cyclic:
  assumes sub: "Subgroup H Fstar (\<cdot>) \<one>" and fin: "finite H"
  shows "\<exists>g \<in> H. Group.cyclic_subgroup (\<cdot>) \<one> g = H"
proof -
  interpret G: Group Fstar "(\<cdot>)" \<one> by (rule Group_Fstar)
  interpret H: Subgroup H Fstar "(\<cdot>)" \<one> by (rule sub)
  have HR: "H \<subseteq> R" using H.subset by (auto simp: Fstar_def)
  \<comment> \<open>The root bound restricted to @{term H}: at most @{term n} elements of @{term H} solve \<open>x\<^sup>n = 1\<close>.\<close>
  have bound: "card {x \<in> H. Monoid.power (\<cdot>) \<one> x n = \<one>} \<le> n" if n: "n > 0" for n
  proof -
    have sub_set: "{x \<in> H. Monoid.power (\<cdot>) \<one> x n = \<one>} \<subseteq> {x \<in> R. multiplicative.power x n = \<one>}"
      using HR by blast
    then show ?thesis
      by (metis (no_types, lifting) card_mono card_nth_roots_of_unity[of n] order_trans that) 
  qed
  have ne: "H \<noteq> {}" using H.sub.unit_closed by auto
  show ?thesis
    using H.sub.cyclic_of_root_bound[OF fin ne] bound by blast
qed

text \<open>In particular, if the whole multiplicative group @{term Fstar} is finite (e.g.\ a finite
  field), it is cyclic.\<close>

corollary finite_field_mult_cyclic:
  assumes fin: "finite Fstar"
  shows "\<exists>g \<in> Fstar. Group.cyclic_subgroup (\<cdot>) \<one> g = Fstar"
  by (simp add: Group.group_self_subgroup Group_Fstar fin finite_subgroup_Fstar_cyclic)

end

end
