section \<open>Complex splitting-field extension of generic restriction\<close>

theory Galois_Restriction
  imports Galois_Action Galois_Restriction_Core
begin

text \<open>
  The generic restriction map, its homomorphism, kernel, quotient, and solvability results are
  provided by the generic restriction core.  This theory retains the complex-specific
  extension theorem: in a generated root field, every automorphism of the intermediate field
  extends to an automorphism of the larger field.
\<close>

text \<open>Surjectivity of restriction for a generated root field.  Let \<open>F \<subseteq> E \<subseteq> K\<close> with
  @{term K} generated by @{term E} and the roots of an @{term F}-polynomial.  The finite
  homomorphism-extension theorem supplies an extension of every @{term F}-automorphism of @{term E}.
\<close>
theorem galois_restriction_surjective:
  fixes K E F :: "'a :: field set" and Phi :: "'a poly"
  assumes sfE: "Subfield E" and sfF: "Subfield F" and FE: "F \<subseteq> E"
    and Phi: "Phi \<in> poly_over F"
    and Kdef: "K = generate_field (E \<union> {r. poly Phi r = 0})"
    and finR: "finite {r. poly Phi r = 0}"
    and algR: "\<And>r. poly Phi r = 0 \<Longrightarrow> algebraic_over E r"
    and closed: "\<And>q :: 'a poly. 0 < degree q \<Longrightarrow> \<exists>b. poly q b = 0"
    and t: "\<tau> \<in> field_auto E F"
  shows "\<exists>\<sigma> \<in> field_auto K F. \<forall>x \<in> E. \<sigma> x = \<tau> x"
proof -
  define R where "R = {r. poly Phi r = 0}"
  have EK: "E \<subseteq> K" using Kdef by (auto simp: subset_generate_field)
  have sfK: "Subfield K" unfolding Kdef by (rule subfield_generate_field)
  have FK: "F \<subseteq> K" using FE EK by simp
  have homt: "field_hom_on E \<tau>" using sfE t by (rule field_auto_imp_field_hom_on)
  have fixFt: "\<And>x. x \<in> F \<Longrightarrow> \<tau> x = x" using t by (auto simp: field_auto_mem_iff)
  \<comment> \<open>Extend @{term \<tau>} over the finite root set to a homomorphism @{term g} on @{term K}.\<close>
  have algRE: "\<And>r. r \<in> R \<Longrightarrow> algebraic_over E r" using algR by (simp add: R_def)
  obtain g where homg: "field_hom_on (generate_field (E \<union> R)) g"
    and gE: "\<And>x. x \<in> E \<Longrightarrow> g x = \<tau> x"
    using field_hom_on_extend_finite[OF closed finR[folded R_def] homt algRE] by blast
  have homgK: "field_hom_on K g" using homg by (simp add: Kdef R_def)
  have fixFg: "\<And>x. x \<in> F \<Longrightarrow> g x = x" using gE fixFt FE by auto
  have RK: "R \<subseteq> K" using EK unfolding Kdef R_def using subset_generate_field by blast
  have gR_sub: "g ` R \<subseteq> R"
    using hom_preserves_roots[OF homgK sfF FK fixFg Phi] RK
    by (auto simp: R_def)
  have injK: "inj_on g K" by (rule field_hom_on.inj_on[OF homgK])
  have gR: "g ` R = R"
    by (metis RK R_def endo_inj_surj finR gR_sub injK inj_on_subset)
  have gE_onto: "g ` E = E"
    by (metis bij_betw_imp_surj_on field_auto_mem_iff gE image_cong t)
  have gUn: "g ` (E \<union> R) = E \<union> R" using gE_onto gR by (simp add: image_Un)
  have gK: "g ` K = K"
    by (metis EK Kdef RK R_def field_hom_on.image_generate_field_eq gUn homgK sup.boundedI)
  have aut: "restrict g K \<in> field_auto K F"
    by (rule field_hom_on_imp_field_auto[OF homgK gK fixFg FK])
  then show ?thesis using aut
    by (metis EK gE in_mono restrict_def)
qed

end
