section \<open>The fundamental theorem for finite Galois extensions\<close>

theory Galois_Finite_Correspondence
  imports Artin_Degree Galois_Degree Finite_Extension_Tower Galois_Restriction
begin

text \<open>Separability survives enlargement of the base field.  The new minimal polynomial divides
  the old one, and root-squarefreeness passes to divisors.\<close>
theorem finite_separable_extension_base_change:
  fixes F E K :: "'a :: field set"
  assumes T: "finite_subfield_tower F K" and sep: "separable_extension K F"
    and sfE: "Subfield E" and FE: "F \<subseteq> E" and EK: "E \<subseteq> K"
  shows "separable_extension K E"
proof (rule separable_extensionI)
  interpret T: finite_subfield_tower F K by (rule T)
  fix x assume xK: "x \<in> K" and algE: "algebraic_over E x"
  have algF: "algebraic_over F x" by (rule T.finite_extension_algebraic[OF xK])
  have sepF: "rsquarefree (minpoly F x)"
    by (rule separable_extensionD[OF sep xK algF])
  have minE: "is_minpoly E x (minpoly E x)"
    by (rule Subfield.is_minpoly_minpoly[OF sfE algE])
  have minF_E: "minpoly F x \<in> poly_over E"
    using T.base.minpoly_over[OF algF] poly_over_mono[OF FE] by blast
  have dvd: "minpoly E x dvd minpoly F x"
    by (rule Subfield.minpoly_dvd[OF sfE minE minF_E T.base.minpoly_root[OF algF]])
  show "rsquarefree (minpoly E x)" by (rule rsquarefree_dvd[OF dvd sepF])
qed

text \<open>Normality also survives enlargement of the base inside a finite extension.  The minimal
  polynomial over the larger base divides the old minimal polynomial, so every new conjugate is
  already an old conjugate.\<close>
theorem finite_normal_extension_base_change:
  fixes F E K :: "'a :: field set"
  assumes T: "finite_subfield_tower F K" and normal: "normal_extension K F"
    and sfE: "Subfield E" and FE: "F \<subseteq> E" and EK: "E \<subseteq> K"
  shows "normal_extension K E"
proof (rule normal_extensionI)
  interpret T: finite_subfield_tower F K by (rule T)
  fix p a
  assume pE: "p \<in> poly_over E" and irr: "irreducible_over E p"
    and aK: "a \<in> K" and pa: "poly p a = 0"
  have algF: "algebraic_over F a"
    by (rule T.finite_extension_algebraic[OF aK])
  have algE: "algebraic_over E a"
    by (rule algebraic_over_mono[OF algF FE])
  have minE: "is_minpoly E a (minpoly E a)"
    by (rule Subfield.is_minpoly_minpoly[OF sfE algE])
  have minF_E: "minpoly F a \<in> poly_over E"
    using T.base.minpoly_over[OF algF] poly_over_mono[OF FE] by blast
  have dvd: "minpoly E a dvd minpoly F a"
    by (rule Subfield.minpoly_dvd[OF sfE minE minF_E T.base.minpoly_root[OF algF]])
  have rootsF: "poly_root_set (minpoly F a) \<subseteq> K"
    by (rule normal_extensionD[OF normal T.base.minpoly_over[OF algF]
      irreducible_over_minpoly[OF T.base.Subfield_axioms algF]
      aK T.base.minpoly_root[OF algF]])
  show "poly_root_set p \<subseteq> K"
  proof
    fix b assume bR: "b \<in> poly_root_set p"
    have pb: "poly p b = 0" using bR by simp
    have min_b: "poly (minpoly E a) b = 0"
      by (rule Subfield.irreducible_over_root_is_minpoly_root[OF sfE irr pE minE pa pb])
    obtain q where factor: "minpoly F a = minpoly E a * q"
      using dvd by (elim dvdE)
    have rootF_b: "poly (minpoly F a) b = 0"
      using factor min_b by (simp add: poly_mult)
    have b_rootsF: "b \<in> poly_root_set (minpoly F a)"
      using rootF_b unfolding poly_root_set_def by simp
    show "b \<in> K" by (rule rootsF[THEN subsetD, OF b_rootsF])
  qed
qed


subsection \<open>The finite correspondence\<close>

context
  fixes F K :: "'a :: alg_closed_field set"
  assumes finite: "finite_subfield_tower F K"
    and normal: "normal_extension K F"
    and separable: "separable_extension K F"
begin

interpretation T: finite_subfield_tower F K by (rule finite)

interpretation GE: galois_extension K F
  by (rule galois_extension.intro[OF T.ext.Subfield_axioms T.base.Subfield_axioms
    T.base_subset])

text \<open>Any two conjugates over the base are related by an automorphism of a finite Galois
  extension.  A primitive element presents the extension as the field generated by the roots of its
  minimal polynomial; multiplying that polynomial by the minimal polynomial under consideration
  lets the generic transitivity theorem act on both roots without changing the generated field.\<close>
theorem finite_galois_root_transfer:
  assumes aK: "a \<in> K" and mb: "poly (minpoly F a) b = 0"
  shows "\<exists>\<sigma>\<in>field_auto K F. \<sigma> a = b"
proof -
  have alga: "algebraic_over F a"
    by (rule T.finite_extension_algebraic[OF aK])
  obtain theta where thetaK: "theta \<in> K" and prim: "primitive_element F K theta"
    using finite_separable_extension_is_simple[OF finite separable] by blast
  have algtheta: "algebraic_over F theta"
    by (rule T.finite_extension_algebraic[OF thetaK])
  define q where "q = minpoly F theta"
  define m where "m = minpoly F a"
  define Phi where "Phi = q * m"
  define R where "R = {r. poly Phi r = 0}"
  have qF: "q \<in> poly_over F"
    unfolding q_def by (rule T.base.minpoly_over[OF algtheta])
  have mF: "m \<in> poly_over F"
    unfolding m_def by (rule T.base.minpoly_over[OF alga])
  have q0: "q \<noteq> 0"
    unfolding q_def by (rule T.base.minpoly_nonzero[OF algtheta])
  have m0: "m \<noteq> 0"
    unfolding m_def by (rule T.base.minpoly_nonzero[OF alga])
  have PhiF: "Phi \<in> poly_over F"
    unfolding Phi_def by (rule T.base.poly_over_mult[OF qF mF])
  have Phi0: "Phi \<noteq> 0" unfolding Phi_def using q0 m0 by simp
  have finR: "finite R"
    unfolding R_def by (rule poly_roots_finite[OF Phi0])
  have qroots: "poly_root_set q \<subseteq> K"
    unfolding q_def
    by (rule normal_extensionD[OF normal T.base.minpoly_over[OF algtheta]
      irreducible_over_minpoly[OF T.base.Subfield_axioms algtheta]
      thetaK T.base.minpoly_root[OF algtheta]])
  have mroots: "poly_root_set m \<subseteq> K"
    unfolding m_def
    by (rule normal_extensionD[OF normal T.base.minpoly_over[OF alga]
      irreducible_over_minpoly[OF T.base.Subfield_axioms alga]
      aK T.base.minpoly_root[OF alga]])
  have RsubK: "R \<subseteq> K"
    using qroots mroots
    unfolding R_def Phi_def poly_root_set_def by (auto simp: poly_mult)
  have algR: "\<And>r. r \<in> R \<Longrightarrow> algebraic_over F r"
    by (rule T.finite_extension_algebraic) (use RsubK in blast)
  have thetaR: "theta \<in> R"
    unfolding R_def Phi_def q_def
    using T.base.minpoly_root[OF algtheta] by (simp add: poly_mult)
  have aR: "a \<in> R"
    unfolding R_def Phi_def m_def
    using T.base.minpoly_root[OF alga] by (simp add: poly_mult)
  have bR: "b \<in> R"
    unfolding R_def Phi_def m_def using mb by (simp add: poly_mult)
  have Kgen: "K = generate_field (F \<union> R)"
  proof (rule subset_antisym)
    have "K = generate_field (F \<union> {theta})"
      using primitive_elementD[OF prim]
        T.base.eval_img_eq_generate_field[OF algtheta] by simp
    also have "... \<subseteq> generate_field (F \<union> R)"
      by (rule generate_field_mono) (use thetaR in auto)
    finally show "K \<subseteq> generate_field (F \<union> R)" .
    show "generate_field (F \<union> R) \<subseteq> K"
      by (rule generate_field_least[OF T.ext.Subfield_axioms])
         (use T.base_subset RsubK in auto)
  qed
  have min_a: "is_minpoly F a (minpoly F a)"
    by (rule T.base.is_minpoly_minpoly[OF alga])
  have trans:
      "\<exists>g. field_hom_on (generate_field (F \<union> R)) g \<and> g a = b \<and>
        (\<forall>x\<in>F. g x = x) \<and> g ` generate_field (F \<union> R) = generate_field (F \<union> R)"
    by (rule galois_transitive[OF T.base.Subfield_axioms finR algR PhiF R_def
      alg_closed_imp_poly_has_root aR bR min_a mb])
  obtain g where homg: "field_hom_on (generate_field (F \<union> R)) g"
    and gab: "g a = b" and fixg: "\<forall>x\<in>F. g x = x"
    and imageg: "g ` generate_field (F \<union> R) = generate_field (F \<union> R)"
    using trans by blast
  have aut: "restrict g K \<in> field_auto K F"
    by (rule field_hom_on_imp_field_auto[OF homg[folded Kgen] imageg[folded Kgen]
      _ T.base_subset]) (use fixg in blast)
  have "restrict g K a = b" using aK gab by simp
  then show ?thesis using aut by blast
qed

text \<open>Every intermediate field is recovered as the fixed field of its relative Galois group.
  The upper extension remains finite, normal and separable.  Its degree equals the order of the
  relative group; Artin's theorem computes the degree over that group's fixed field.  The tower law
  then makes the intervening degree one.\<close>
theorem finite_galois_fixed_field:
  assumes E: "E \<in> inter_fields K F"
  shows "fixed_field K (field_auto K E) = E"
proof -
  have sfE: "Subfield E" and FE: "F \<subseteq> E" and EK: "E \<subseteq> K"
    using E by (auto simp: inter_fields_iff)
  have TFE_raw: "finite_subfield_tower F E"
    by (rule finite_subfield_tower_intermediate_left[OF finite sfE FE EK])
  have TEK_raw: "finite_subfield_tower E K"
    by (rule finite_subfield_tower_intermediate_right[OF finite sfE FE EK])
  interpret TFE: finite_subfield_tower F E by (rule TFE_raw)
  interpret TEK: finite_subfield_tower E K by (rule TEK_raw)
  have normalEK: "normal_extension K E"
    by (rule finite_normal_extension_base_change[OF finite normal sfE FE EK])
  have sepEK: "separable_extension K E"
    by (rule finite_separable_extension_base_change[OF finite separable sfE FE EK])

  have Hsub_raw: "Subgroup (field_auto K E) (field_auto K F) (compose K) (identity K)"
    by (rule field_auto_subgroup_of_Galois_group[OF T.ext.Subfield_axioms T.base_subset E])
  have Hsub: "field_auto K E \<in> galois_subgroups K F"
    using Hsub_raw by (simp add: galois_subgroups_iff)
  have Hle: "field_auto K E \<subseteq> field_auto K F"
    using Hsub by (rule galois_subgroups_subset)
  have finG: "finite (field_auto K F)"
    by (rule finite_normal_separable_field_auto[OF finite normal separable])
  have finH: "finite (field_auto K E)"
    by (rule finite_subset[OF Hle finG])
  have cardH: "card (field_auto K E) = TEK.extension_degree"
    by (rule finite_normal_separable_galois_degree[OF TEK_raw normalEK sepEK])

  have towerFix: "subfield_tower (fixed_field K (field_auto K E)) K"
    by (rule fixed_field_tower[OF T.ext.Subfield_axioms Hle])
  interpret FixK: subfield_tower "fixed_field K (field_auto K E)" K
    by (rule towerFix)
  obtain B where basis: "FixK.vs.basis B"
    and cardB: "card B = card (field_auto K E)"
    using artin_fixed_field_degree_data[where K=K and F=F and H="field_auto K E",
      OF T.ext.Subfield_axioms T.base.Subfield_axioms T.base_subset Hsub finH]
    by blast
  have TFixK_raw: "finite_subfield_tower (fixed_field K (field_auto K E)) K"
  proof (rule finite_subfield_tower.intro)
    show "subfield_tower (fixed_field K (field_auto K E)) K" by (rule towerFix)
    show "finite_subfield_tower_axioms (fixed_field K (field_auto K E)) K"
      by unfold_locales (rule exI[of _ B], rule basis)
  qed
  interpret TFixK: finite_subfield_tower "fixed_field K (field_auto K E)" K
    by (rule TFixK_raw)
  have degreeFix: "TFixK.extension_degree = card (field_auto K E)"
    using TFixK.extension_degree_eq_card_basis[OF basis] cardB by simp

  have EFix: "E \<subseteq> fixed_field K (field_auto K E)"
    by (rule GE.le_fixed_field_galois_group[OF E])
  have sfFix: "Subfield (fixed_field K (field_auto K E))"
    by (rule fixed_field_subfield[OF T.ext.Subfield_axioms Hle])
  have FixK: "fixed_field K (field_auto K E) \<subseteq> K"
    by (rule fixed_field_subset)
  have TEFix_raw: "finite_subfield_tower E (fixed_field K (field_auto K E))"
    by (rule finite_subfield_tower_intermediate_left[OF TEK_raw sfFix EFix FixK])
  interpret TEFix: finite_subfield_tower E "fixed_field K (field_auto K E)"
    by (rule TEFix_raw)
  interpret C: finite_subfield_tower_chain E "fixed_field K (field_auto K E)" K
    by (rule finite_subfield_tower_chain.intro[OF TEFix_raw TFixK_raw])
  have tower_degree:
      "TEK.extension_degree = TEFix.extension_degree * TFixK.extension_degree"
    by (rule C.extension_degree_tower_law_exists)
  have cancel_eq:
      "TFixK.extension_degree * 1 = TFixK.extension_degree * TEFix.extension_degree"
    using tower_degree cardH degreeFix by (simp add: mult.commute)
  have degree_one: "TEFix.extension_degree = 1"
    using cancel_eq TFixK.extension_degree_pos nat_mult_eq_cancel1 by simp

  have sepEFix: "separable_extension (fixed_field K (field_auto K E)) E"
  proof (rule separable_extensionI)
    fix x
    assume xFix: "x \<in> fixed_field K (field_auto K E)"
      and algE: "algebraic_over E x"
    have xK: "x \<in> K" using FixK xFix by blast
    show "rsquarefree (minpoly E x)"
      by (rule separable_extensionD[OF sepEK xK algE])
  qed
  obtain theta where thetaFix: "theta \<in> fixed_field K (field_auto K E)"
    and prim: "primitive_element E (fixed_field K (field_auto K E)) theta"
    using finite_separable_extension_is_simple[OF TEFix_raw sepEFix] by blast
  have algTheta: "algebraic_over E theta"
    by (rule TEFix.finite_extension_algebraic[OF thetaFix])
  have ext_one: "ext_degree E theta = 1"
    using TEFix.primitive_element_degree[OF prim] degree_one by simp
  have thetaE: "theta \<in> E"
    using ext_one Subfield.ext_degree_eq_1_iff[OF sfE algTheta] by blast
  have evalE: "eval_img E theta = E"
  proof -
    have "eval_img E theta = generate_field (E \<union> {theta})"
      by (rule Subfield.eval_img_eq_generate_field[OF sfE algTheta])
    also have "... = generate_field E"
      by (rule arg_cong[where f=generate_field]) (use thetaE in auto)
    also have "... = E" by (rule Subfield.generate_field_self[OF sfE])
    finally show ?thesis .
  qed
  show ?thesis using primitive_elementD[OF prim] evalE by simp
qed

text \<open>Conversely, a subgroup of the finite Galois group is recovered from its fixed field by
  Artin's theorem.\<close>
theorem finite_galois_fixed_group:
  assumes H: "H \<in> galois_subgroups K F"
  shows "field_auto K (fixed_field K H) = H"
proof -
  have finG: "finite (field_auto K F)"
    by (rule finite_normal_separable_field_auto[OF finite normal separable])
  have Hle: "H \<subseteq> field_auto K F"
    using H by (rule galois_subgroups_subset)
  have finH: "finite H" by (rule finite_subset[OF Hle finG])
  show ?thesis
    by (rule artin_theorem[OF T.ext.Subfield_axioms T.base.Subfield_axioms
      T.base_subset H finH])
qed

text \<open>The two antitone maps are therefore mutually inverse bijections.\<close>
theorem finite_galois_field_group_bij:
  "bij_betw (field_auto K) (inter_fields K F) (galois_subgroups K F)"
proof (rule bij_betw_byWitness[where f'="fixed_field K"])
  show "\<forall>E\<in>inter_fields K F. fixed_field K (field_auto K E) = E"
    using finite_galois_fixed_field by blast
  show "\<forall>H\<in>galois_subgroups K F. field_auto K (fixed_field K H) = H"
    using finite_galois_fixed_group by blast
  show "field_auto K ` inter_fields K F \<subseteq> galois_subgroups K F"
    using field_auto_subgroup_of_Galois_group[OF T.ext.Subfield_axioms T.base_subset]
    by (auto simp: galois_subgroups_iff)
  show "fixed_field K ` galois_subgroups K F \<subseteq> inter_fields K F"
    using GE.fixed_field_in_inter_fields by blast
qed

theorem finite_galois_group_field_bij:
  "bij_betw (fixed_field K) (galois_subgroups K F) (inter_fields K F)"
proof (rule bij_betw_byWitness[where f'="field_auto K"])
  show "\<forall>H\<in>galois_subgroups K F. field_auto K (fixed_field K H) = H"
    using finite_galois_fixed_group by blast
  show "\<forall>E\<in>inter_fields K F. fixed_field K (field_auto K E) = E"
    using finite_galois_fixed_field by blast
  show "fixed_field K ` galois_subgroups K F \<subseteq> inter_fields K F"
    using GE.fixed_field_in_inter_fields by blast
  show "field_auto K ` inter_fields K F \<subseteq> galois_subgroups K F"
    using field_auto_subgroup_of_Galois_group[OF T.ext.Subfield_axioms T.base_subset]
    by (auto simp: galois_subgroups_iff)
qed

theorem finite_galois_correspondence:
  "bij_betw (field_auto K) (inter_fields K F) (galois_subgroups K F) \<and>
   bij_betw (fixed_field K) (galois_subgroups K F) (inter_fields K F)"
  using finite_galois_field_group_bij finite_galois_group_field_bij by blast


subsection \<open>Degree and index formulas\<close>

context
  fixes E :: "'a set"
  assumes intermediate: "E \<in> inter_fields K F"
begin

lemma intermediate_data:
  "Subfield E \<and> F \<subseteq> E \<and> E \<subseteq> K"
  using intermediate by (simp add: inter_fields_iff)

lemma TFE_raw: "finite_subfield_tower F E"
  using intermediate_data
  by (blast intro: finite_subfield_tower_intermediate_left[OF finite])

lemma TEK_raw: "finite_subfield_tower E K"
  using intermediate_data
  by (blast intro: finite_subfield_tower_intermediate_right[OF finite])

interpretation TFE: finite_subfield_tower F E by (rule TFE_raw)
interpretation TEK: finite_subfield_tower E K by (rule TEK_raw)

lemma normalEK: "normal_extension K E"
  using intermediate_data
  by (blast intro: finite_normal_extension_base_change[OF finite normal])

lemma separableEK: "separable_extension K E"
  using intermediate_data
  by (blast intro: finite_separable_extension_base_change[OF finite separable])

lemma relative_subgroup:
  "Subgroup (field_auto K E) (field_auto K F) (compose K) (identity K)"
  by (rule field_auto_subgroup_of_Galois_group[OF T.ext.Subfield_axioms T.base_subset
    intermediate])

interpretation S: subgroup_of_group "field_auto K E" "field_auto K F"
    "compose K" "identity K"
proof (rule subgroup_of_groupI)
  show "Subgroup (field_auto K E) (field_auto K F) (compose K) (identity K)"
    by (rule relative_subgroup)
  show "Group (field_auto K F) (compose K) (identity K)"
    by (rule field_auto_group[OF T.ext.Subfield_axioms T.base_subset])
qed

text \<open>The relative Galois group has order equal to the degree of the upper extension.\<close>
theorem finite_galois_relative_group_order:
  "card (field_auto K E) = TEK.extension_degree"
  by (rule finite_normal_separable_galois_degree[OF TEK_raw normalEK separableEK])

text \<open>Its index in the full Galois group is the degree of the lower extension.\<close>
theorem finite_galois_relative_group_index:
  "S.index = TFE.extension_degree"
proof -
  have finG: "finite (field_auto K F)"
    by (rule finite_normal_separable_field_auto[OF finite normal separable])
  have lagrange:
      "card (field_auto K F) = card (field_auto K E) * S.index"
    by (rule S.lagrange[OF finG])
  have global_order: "card (field_auto K F) = T.extension_degree"
    by (rule finite_normal_separable_galois_degree[OF finite normal separable])
  interpret C: finite_subfield_tower_chain F E K
    by (rule finite_subfield_tower_chain.intro[OF TFE_raw TEK_raw])
  have tower_degree:
      "T.extension_degree = TFE.extension_degree * TEK.extension_degree"
    by (rule C.extension_degree_tower_law_exists)
  have cancel_eq:
      "TEK.extension_degree * TFE.extension_degree = TEK.extension_degree * S.index"
    using lagrange global_order finite_galois_relative_group_order tower_degree
    by (simp add: mult.commute)
  show ?thesis
    using cancel_eq TEK.extension_degree_pos nat_mult_eq_cancel1 by simp
qed

theorem finite_galois_relative_degree_index:
  "card (field_auto K E) = TEK.extension_degree \<and>
   S.index = TFE.extension_degree"
  using finite_galois_relative_group_order finite_galois_relative_group_index by blast


subsection \<open>Normal intermediate fields\<close>

text \<open>An intermediate field is normal over the base exactly when every automorphism of the
  ambient finite Galois extension preserves it setwise.\<close>
theorem finite_galois_normal_iff_stable:
  "normal_extension E F \<longleftrightarrow>
    (\<forall>\<sigma>\<in>field_auto K F. \<sigma> ` E = E)"
proof
  assume normalE: "normal_extension E F"
  have image_subset: "\<sigma> ` E \<subseteq> E" if sigma: "\<sigma> \<in> field_auto K F" for \<sigma>
  proof
    fix y assume "y \<in> \<sigma> ` E"
    then obtain x where xE: "x \<in> E" and y: "y = \<sigma> x" by blast
    have xK: "x \<in> K" using intermediate_data xE by blast
    have algx: "algebraic_over F x"
      by (rule TFE.finite_extension_algebraic[OF xE])
    have rootsE: "poly_root_set (minpoly F x) \<subseteq> E"
      by (rule normal_extensionD[OF normalE T.base.minpoly_over[OF algx]
        irreducible_over_minpoly[OF T.base.Subfield_axioms algx]
        xE T.base.minpoly_root[OF algx]])
    have hom: "field_hom_on K \<sigma>"
      by (rule field_auto_as_hom[OF T.ext.Subfield_axioms sigma])
    have fixF: "\<And>z. z \<in> F \<Longrightarrow> \<sigma> z = z"
      using sigma by (auto simp: field_auto_mem_iff)
    have image_root: "poly (minpoly F x) (\<sigma> x) = 0"
      by (rule hom_preserves_roots[OF hom T.base.Subfield_axioms T.base_subset fixF
        T.base.minpoly_over[OF algx] xK T.base.minpoly_root[OF algx]])
    have "\<sigma> x \<in> poly_root_set (minpoly F x)"
      using image_root unfolding poly_root_set_def by simp
    then show "y \<in> E" using rootsE y by blast
  qed
  show "\<forall>\<sigma>\<in>field_auto K F. \<sigma> ` E = E"
  proof (intro ballI)
    fix \<sigma> assume sigma: "\<sigma> \<in> field_auto K F"
    define tau where "tau = restrict (inv_into K \<sigma>) K"
    have tauG: "tau \<in> field_auto K F"
      unfolding tau_def
      by (rule field_auto_inverse[OF T.ext.Subfield_axioms sigma T.base_subset])
    have tauE: "tau ` E \<subseteq> E" by (rule image_subset[OF tauG])
    have sigmaE: "\<sigma> ` E \<subseteq> E" by (rule image_subset[OF sigma])
    show "\<sigma> ` E = E"
    proof (rule subset_antisym[OF sigmaE])
      show "E \<subseteq> \<sigma> ` E"
      proof
        fix y assume yE: "y \<in> E"
        have yK: "y \<in> K" using intermediate_data yE by blast
        have tauyE: "tau y \<in> E"
        proof (rule tauE[THEN subsetD])
          show "tau y \<in> tau ` E" by (rule imageI[OF yE])
        qed
        have bij: "bij_betw \<sigma> K K"
          using sigma by (simp add: field_auto_mem_iff)
        have y_image: "y \<in> \<sigma> ` K"
          using bij yK by (simp add: bij_betw_def)
        have sigma_tau: "\<sigma> (tau y) = y"
          unfolding tau_def using yK y_image by (simp add: f_inv_into_f)
        have "\<sigma> (tau y) \<in> \<sigma> ` E" by (rule imageI[OF tauyE])
        then show "y \<in> \<sigma> ` E" using sigma_tau by simp
      qed
    qed
  qed
next
  assume stable: "\<forall>\<sigma>\<in>field_auto K F. \<sigma> ` E = E"
  show "normal_extension E F"
  proof (rule normal_extensionI)
    fix p a
    assume pF: "p \<in> poly_over F" and irr: "irreducible_over F p"
      and aE: "a \<in> E" and pa: "poly p a = 0"
    have aK: "a \<in> K" using intermediate_data aE by blast
    have rootsK: "poly_root_set p \<subseteq> K"
      by (rule normal_extensionD[OF normal pF irr aK pa])
    show "poly_root_set p \<subseteq> E"
    proof
      fix b assume bR: "b \<in> poly_root_set p"
      have bK: "b \<in> K" by (rule rootsK[THEN subsetD, OF bR])
      have pb: "poly p b = 0" using bR unfolding poly_root_set_def by simp
      have alga: "algebraic_over F a"
        by (rule TFE.finite_extension_algebraic[OF aE])
      have min_a: "is_minpoly F a (minpoly F a)"
        by (rule T.base.is_minpoly_minpoly[OF alga])
      have min_b: "poly (minpoly F a) b = 0"
        by (rule T.base.irreducible_over_root_is_minpoly_root[OF irr pF min_a pa pb])
      obtain \<sigma> where sigma: "\<sigma> \<in> field_auto K F" and sab: "\<sigma> a = b"
        using finite_galois_root_transfer[OF aK min_b] by blast
      have "\<sigma> ` E = E" using stable sigma by blast
      moreover have "\<sigma> a \<in> \<sigma> ` E" by (rule imageI[OF aE])
      ultimately show "b \<in> E" using sab by simp
    qed
  qed
qed

text \<open>Setwise stability is also exactly normality of the corresponding subgroup.\<close>
theorem finite_galois_normal_subgroup_iff_stable:
  "normal_subgroup (field_auto K E) (field_auto K F) (compose K) (identity K) \<longleftrightarrow>
    (\<forall>\<sigma>\<in>field_auto K F. \<sigma> ` E = E)"
proof
  assume normalH:
    "normal_subgroup (field_auto K E) (field_auto K F) (compose K) (identity K)"
  interpret N: normal_subgroup "field_auto K E" "field_auto K F"
    "compose K" "identity K" by (rule normalH)
  have fixedE: "fixed_field K (field_auto K E) = E"
    by (rule finite_galois_fixed_field[OF intermediate])
  have image_subset: "\<sigma> ` E \<subseteq> E" if sigma: "\<sigma> \<in> field_auto K F" for \<sigma>
  proof
    fix y assume "y \<in> \<sigma> ` E"
    then obtain x where xE: "x \<in> E" and y: "y = \<sigma> x" by blast
    have xFix: "x \<in> fixed_field K (field_auto K E)" using xE fixedE by simp
    have xK: "x \<in> K" using fixed_field_memD[OF xFix] by blast
    have sigxK: "\<sigma> x \<in> K"
      using sigma xK by (auto simp: field_auto_mem_iff PiE_iff)
    have sigxFix: "\<sigma> x \<in> fixed_field K (field_auto K E)"
    proof (rule fixed_field_memI[OF sigxK])
      fix h assume hH: "h \<in> field_auto K E"
      have cosets:
          "coset_notation.Left_Coset (compose K) \<sigma> (field_auto K E) =
           coset_notation.Right_Coset (compose K) (field_auto K E) \<sigma>"
        by (rule N.Left_equals_Right_coset[OF sigma])
      have right_mem:
          "compose K h \<sigma> \<in>
           coset_notation.Right_Coset (compose K) (field_auto K E) \<sigma>"
        unfolding coset_notation.Right_Coset_def by (rule imageI[OF hH])
      have left_mem:
          "compose K h \<sigma> \<in>
           coset_notation.Left_Coset (compose K) \<sigma> (field_auto K E)"
        using right_mem cosets by simp
      have left_image:
          "compose K h \<sigma> \<in> (\<lambda>k. compose K \<sigma> k) ` field_auto K E"
        using left_mem unfolding coset_notation.Left_Coset_def .
      obtain k where kH: "k \<in> field_auto K E"
        and commute: "compose K \<sigma> k = compose K h \<sigma>"
      proof -
        from left_image obtain k where kH: "k \<in> field_auto K E"
          and eq: "compose K h \<sigma> = compose K \<sigma> k"
          by (elim imageE) simp
        show ?thesis by (rule that[OF kH eq[symmetric]])
      qed
      have kx: "k x = x" using fixed_field_memD[OF xFix] kH by blast
      have eval_eq: "\<sigma> (k x) = h (\<sigma> x)"
        using fun_cong[OF commute, of x] xK by (simp add: compose_def)
      show "h (\<sigma> x) = \<sigma> x" using eval_eq kx by simp
    qed
    show "y \<in> E" using sigxFix fixedE y by simp
  qed
  show "\<forall>\<sigma>\<in>field_auto K F. \<sigma> ` E = E"
  proof (intro ballI)
    fix \<sigma> assume sigma: "\<sigma> \<in> field_auto K F"
    define tau where "tau = restrict (inv_into K \<sigma>) K"
    have tauG: "tau \<in> field_auto K F"
      unfolding tau_def
      by (rule field_auto_inverse[OF T.ext.Subfield_axioms sigma T.base_subset])
    have tauE: "tau ` E \<subseteq> E" by (rule image_subset[OF tauG])
    have sigmaE: "\<sigma> ` E \<subseteq> E" by (rule image_subset[OF sigma])
    show "\<sigma> ` E = E"
    proof (rule subset_antisym[OF sigmaE])
      show "E \<subseteq> \<sigma> ` E"
      proof
        fix y assume yE: "y \<in> E"
        have yK: "y \<in> K" using intermediate_data yE by blast
        have tauyE: "tau y \<in> E"
        proof (rule tauE[THEN subsetD])
          show "tau y \<in> tau ` E" by (rule imageI[OF yE])
        qed
        have bij: "bij_betw \<sigma> K K"
          using sigma by (simp add: field_auto_mem_iff)
        have y_image: "y \<in> \<sigma> ` K"
          using bij yK by (simp add: bij_betw_def)
        have sigma_tau: "\<sigma> (tau y) = y"
          unfolding tau_def using yK y_image by (simp add: f_inv_into_f)
        have "\<sigma> (tau y) \<in> \<sigma> ` E" by (rule imageI[OF tauyE])
        then show "y \<in> \<sigma> ` E" using sigma_tau by simp
      qed
    qed
  qed
next
  assume stable: "\<forall>\<sigma>\<in>field_auto K F. \<sigma> ` E = E"
  have stable': "\<And>\<sigma>. \<sigma> \<in> field_auto K F \<Longrightarrow> \<sigma> ` E = E"
    using stable by blast
  have sfE: "Subfield E" using intermediate_data by blast
  have FE: "F \<subseteq> E" using intermediate_data by blast
  have EK: "E \<subseteq> K" using intermediate_data by blast
  have hom: "group_homomorphism (galois_restriction K E F)
      (field_auto K F) (compose K) (identity K)
      (field_auto E F) (compose E) (identity E)"
    unfolding galois_restriction_def
    by (rule galois_restriction_hom[OF T.ext.Subfield_axioms sfE FE EK stable'])
  interpret R: group_homomorphism "galois_restriction K E F"
      "field_auto K F" "compose K" "identity K"
      "field_auto E F" "compose E" "identity E"
    by (rule hom)
  have ker: "R.Ker = field_auto K E"
    unfolding galois_restriction_def
    by (rule galois_restriction_Ker[OF T.ext.Subfield_axioms sfE FE EK stable'])
  have "normal_subgroup R.Ker (field_auto K F) (compose K) (identity K)"
    by (rule R.kernel.normal_subgroup_axioms)
  then show "normal_subgroup (field_auto K E) (field_auto K F) (compose K) (identity K)"
    using ker by simp
qed

text \<open>This is the normal-field/normal-subgroup clause of the fundamental theorem.\<close>
theorem finite_galois_normal_iff_normal_subgroup:
  "normal_extension E F \<longleftrightarrow>
   normal_subgroup (field_auto K E) (field_auto K F) (compose K) (identity K)"
  using finite_galois_normal_iff_stable finite_galois_normal_subgroup_iff_stable by blast


subsection \<open>Restriction and the quotient theorem\<close>

text \<open>Restriction onto a stable intermediate field is surjective.  A primitive element for
  the full extension supplies a finite root-generated presentation over the intermediate field, so
  the generic homomorphism-extension theorem applies.\<close>
theorem finite_galois_restriction_image:
  assumes stable: "\<And>\<sigma>. \<sigma> \<in> field_auto K F \<Longrightarrow> \<sigma> ` E = E"
  shows "galois_restriction K E F ` field_auto K F = field_auto E F"
proof -
  have sfE: "Subfield E" and FE: "F \<subseteq> E" and EK: "E \<subseteq> K"
    using intermediate_data by blast+
  obtain theta where thetaK: "theta \<in> K" and prim: "primitive_element F K theta"
    using finite_separable_extension_is_simple[OF finite separable] by blast
  have algtheta: "algebraic_over F theta"
    by (rule T.finite_extension_algebraic[OF thetaK])
  define p where "p = minpoly F theta"
  define R where "R = {r. poly p r = 0}"
  have pF: "p \<in> poly_over F"
    unfolding p_def by (rule T.base.minpoly_over[OF algtheta])
  have p0: "p \<noteq> 0"
    unfolding p_def by (rule T.base.minpoly_nonzero[OF algtheta])
  have finR: "finite R" unfolding R_def by (rule poly_roots_finite[OF p0])
  have rootsK: "R \<subseteq> K"
  proof -
    have "poly_root_set (minpoly F theta) \<subseteq> K"
      by (rule normal_extensionD[OF normal T.base.minpoly_over[OF algtheta]
        irreducible_over_minpoly[OF T.base.Subfield_axioms algtheta]
        thetaK T.base.minpoly_root[OF algtheta]])
    then show ?thesis unfolding R_def p_def poly_root_set_def by simp
  qed
  have thetaR: "theta \<in> R"
    unfolding R_def p_def using T.base.minpoly_root[OF algtheta] by simp
  have Kgen: "K = generate_field (E \<union> R)"
  proof (rule subset_antisym)
    have "K = generate_field (F \<union> {theta})"
      using primitive_elementD[OF prim]
        T.base.eval_img_eq_generate_field[OF algtheta] by simp
    also have "... \<subseteq> generate_field (E \<union> R)"
      by (rule generate_field_mono) (use FE thetaR in auto)
    finally show "K \<subseteq> generate_field (E \<union> R)" .
    show "generate_field (E \<union> R) \<subseteq> K"
      by (rule generate_field_least[OF T.ext.Subfield_axioms])
         (use EK rootsK in auto)
  qed
  have algR: "\<And>r. poly p r = 0 \<Longrightarrow> algebraic_over E r"
  proof -
    fix r assume root: "poly p r = 0"
    have rR: "r \<in> R" using root unfolding R_def by simp
    have rK: "r \<in> K" by (rule rootsK[THEN subsetD, OF rR])
    show "algebraic_over E r" by (rule TEK.finite_extension_algebraic[OF rK])
  qed
  have Kgen': "K = generate_field (E \<union> {r. poly p r = 0})"
    using Kgen unfolding R_def .
  have finR': "finite {r. poly p r = 0}"
    using finR unfolding R_def .
  have image_subset:
      "galois_restriction K E F ` field_auto K F \<subseteq> field_auto E F"
    using gal_res_mem[OF T.ext.Subfield_axioms sfE FE EK stable]
    by (auto simp: galois_restriction_apply)
  have target_subset:
      "field_auto E F \<subseteq> galois_restriction K E F ` field_auto K F"
  proof
    fix tau assume tau: "tau \<in> field_auto E F"
    obtain sigma where sigma: "sigma \<in> field_auto K F"
      and agree: "\<forall>x\<in>E. sigma x = tau x"
      using galois_restriction_surjective[OF sfE T.base.Subfield_axioms FE pF
        Kgen' finR' algR alg_closed_imp_poly_has_root tau]
      by blast
    have restrict_eq': "restrict sigma E = restrict tau E"
      by (rule restrict_ext) (use agree in simp)
    have tauPiE: "tau \<in> E \<rightarrow>\<^sub>E E"
      using tau by (simp only: field_auto_mem_iff)
    have restrict_tau: "restrict tau E = tau" by (rule PiE_restrict[OF tauPiE])
    have restriction: "galois_restriction K E F sigma = tau"
      using sigma restrict_eq' restrict_tau by simp
    show "tau \<in> galois_restriction K E F ` field_auto K F"
      using sigma restriction by blast
  qed
  show ?thesis by (rule subset_antisym[OF image_subset target_subset])
qed

context
  assumes normal_intermediate: "normal_extension E F"
begin

lemma stable_intermediate:
  "\<And>\<sigma>. \<sigma> \<in> field_auto K F \<Longrightarrow> \<sigma> ` E = E"
  using iffD1[OF finite_galois_normal_iff_stable normal_intermediate] by blast

lemma restriction_image:
  "galois_restriction K E F ` field_auto K F = field_auto E F"
  by (rule finite_galois_restriction_image[OF stable_intermediate])

interpretation restriction: group_epimorphism "galois_restriction K E F"
    "field_auto K F" "compose K" "identity K"
    "field_auto E F" "compose E" "identity E"
proof -
  have sfE: "Subfield E" and FE: "F \<subseteq> E" and EK: "E \<subseteq> K"
    using intermediate_data by blast+
  show "group_epimorphism (galois_restriction K E F)
      (field_auto K F) (compose K) (identity K)
      (field_auto E F) (compose E) (identity E)"
    by (rule galois_restriction_epimorphism[OF T.ext.Subfield_axioms sfE FE EK
      stable_intermediate restriction_image])
qed

theorem finite_galois_restriction_kernel:
  "restriction.Ker = field_auto K E"
proof -
  have sfE: "Subfield E" and FE: "F \<subseteq> E" and EK: "E \<subseteq> K"
    using intermediate_data by blast+
  show ?thesis
    unfolding galois_restriction_def
    by (rule galois_restriction_Ker[OF T.ext.Subfield_axioms sfE FE EK
      stable_intermediate])
qed

text \<open>The first isomorphism theorem gives
  @{text "Gal(K/F) / Gal(K/E) \<cong> Gal(E/F)"}; the preceding kernel theorem identifies the
  factor-group kernel with the relative Galois group literally.\<close>
theorem finite_galois_quotient_isomorphism:
  "(restriction.kernel.Factor_Group,
     restriction.kernel.quotient_composition,
     restriction.kernel.Class (identity K)) \<cong>\<^sub>G
   (field_auto E F, compose E, identity E)"
proof -
  have iso:
      "(restriction.kernel.Factor_Group,
       restriction.kernel.quotient_composition,
       restriction.kernel.Class (identity K)) \<cong>\<^sub>G
       (galois_restriction K E F ` field_auto K F, compose E, identity E)"
    by (rule restriction.first_isomorphism)
  show ?thesis using iso restriction_image by simp
qed

end

end

end

end
