section \<open>The lattice of ideals\<close>

theory Ideal_Lattice
  imports Ideal_Theory Order_Theory
begin

text \<open>The ideals of a commutative ring \<open>R\<close>, ordered by inclusion, form a complete lattice: the
  infimum of a family of ideals is their intersection (with \<open>R\<close>, so the empty family has infimum
  \<open>R\<close>), and the supremum is the ideal generated by their union.  Together with the subgroup lattice
  this exercises the abstract order theory on the two archetypal substructure lattices.  As a
  by-product we obtain the ideal \<^emph>\<open>generated by a set\<close>, the analogue of the subgroup \<open>generate\<close>.\<close>

context commutative_ring
begin

subsection \<open>Intersections of ideals\<close>

text \<open>The intersection of a nonempty family of ideals is an ideal.\<close>
lemma ideal_Inter:
  assumes ne: "\<A> \<noteq> {}" and id: "\<And>I. I \<in> \<A> \<Longrightarrow> Ideal I R (+) (\<cdot>) \<zero> \<one>"
  shows "Ideal (\<Inter> \<A>) R (+) (\<cdot>) \<zero> \<one>"
proof -
  obtain I0 where I0: "I0 \<in> \<A>" using ne by blast
  interpret I0: Ideal I0 R "(+)" "(\<cdot>)" \<zero> \<one> by (rule id[OF I0])
  have sg: "Subgroup (\<Inter> \<A>) R (+) \<zero>"
  proof (rule additive.subgroupI)
    show "\<Inter> \<A> \<subseteq> R" using I0 I0.additive.subset by blast
  next
    show "\<zero> \<in> \<Inter> \<A>"
    proof
      fix I assume "I \<in> \<A>"
      then interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> by (rule id)
      show "\<zero> \<in> I" by (rule I.additive.sub_unit_closed)
    qed
  next
    fix g h assume g: "g \<in> \<Inter> \<A>" and h: "h \<in> \<Inter> \<A>"
    show "g + h \<in> \<Inter> \<A>"
    proof
      fix I assume I: "I \<in> \<A>"
      then interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> by (rule id)
      show "g + h \<in> I" using g h I by (blast intro: I.additive.sub_composition_closed)
    qed
  next
    fix g assume "g \<in> \<Inter> \<A>"
    then have "g \<in> R" using I0 I0.additive.subset by blast
    then show "additive.invertible g" by simp
  next
    fix g assume g: "g \<in> \<Inter> \<A>"
    show "additive.inverse g \<in> \<Inter> \<A>"
    proof
      fix I assume I: "I \<in> \<A>"
      then interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> by (rule id)
      have "g \<in> I" using g I by blast
      then show "additive.inverse g \<in> I"
        using I.additive.submonoid_inverse_closed I.additive.sub.invertible by blast
    qed
  qed
  interpret S: Subgroup "\<Inter> \<A>" R "(+)" \<zero> by (rule sg)
  show ?thesis
  proof unfold_locales
    fix a b assume a: "a \<in> R" and b: "b \<in> \<Inter> \<A>"
    show "a \<cdot> b \<in> \<Inter> \<A>"
    proof
      fix I assume I: "I \<in> \<A>"
      then interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> by (rule id)
      show "a \<cdot> b \<in> I" using a b I by (blast intro: I.Ideal(1))
    qed
    show "b \<cdot> a \<in> \<Inter> \<A>"
    proof
      fix I assume I: "I \<in> \<A>"
      then interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> by (rule id)
      show "b \<cdot> a \<in> I" using a b I by (blast intro: I.Ideal(2))
    qed
  qed
qed


text \<open>The whole ring is an ideal of itself (the top of the ideal lattice).\<close>
lemma whole_ideal: "Ideal R R (+) (\<cdot>) \<zero> \<one>"
proof -
  have "Subgroup R R (+) \<zero>"
    by (rule additive.subgroupI) auto
  then interpret S: Subgroup R R "(+)" \<zero> .
  show ?thesis by unfold_locales auto
qed


subsection \<open>The ideal generated by a set\<close>

text \<open>The ideal generated by a subset \<open>S\<close> of the ring: the intersection of all ideals containing
  \<open>S \<inter> R\<close>.  (Intersecting with \<open>R\<close> in the guard mirrors the subgroup \<open>generate\<close>, so elements outside
  the carrier are ignored.)\<close>
definition ideal_generated :: "'a set \<Rightarrow> 'a set"
  where "ideal_generated S = \<Inter> {I. Ideal I R (+) (\<cdot>) \<zero> \<one> \<and> S \<inter> R \<subseteq> I}"

lemma ideal_generated_is_ideal: "Ideal (ideal_generated S) R (+) (\<cdot>) \<zero> \<one>"
proof -
  have "R \<in> {I. Ideal I R (+) (\<cdot>) \<zero> \<one> \<and> S \<inter> R \<subseteq> I}"
    using whole_ideal by auto
  then have ne: "{I. Ideal I R (+) (\<cdot>) \<zero> \<one> \<and> S \<inter> R \<subseteq> I} \<noteq> {}" by blast
  show ?thesis
    unfolding ideal_generated_def by (rule ideal_Inter[OF ne]) auto
qed

lemma ideal_generated_incl: "S \<inter> R \<subseteq> ideal_generated S"
  unfolding ideal_generated_def by blast

lemma ideal_generated_minimal:
  assumes "Ideal J R (+) (\<cdot>) \<zero> \<one>" "S \<inter> R \<subseteq> J"
  shows "ideal_generated S \<subseteq> J"
  unfolding ideal_generated_def using assms by (blast intro: Inter_lower)

lemma ideal_generated_subset_carrier: "ideal_generated S \<subseteq> R"
proof -
  interpret gen: Ideal "ideal_generated S" R "(+)" "(\<cdot>)" \<zero> \<one> by (rule ideal_generated_is_ideal)
  show ?thesis by (rule gen.additive.subset)
qed


subsection \<open>The product of two ideals\<close>

text \<open>The product \<open>I \<odot> J\<close> of two ideals is the ideal generated by all products \<open>i \<cdot> j\<close> with
  \<open>i \<in> I\<close> and \<open>j \<in> J\<close>.  Together with the ideal sum and the intersection this completes the
  semiring of ideals; the product is contained in the intersection (hence, unlike sum and
  intersection, is in general \<^emph>\<open>not\<close> a lattice operation).\<close>
definition ideal_prod :: "'a set \<Rightarrow> 'a set \<Rightarrow> 'a set"  (infixl \<open>\<odot>\<close> 70)
  where "I \<odot> J = ideal_generated {i \<cdot> j |i j. i \<in> I \<and> j \<in> J}"

lemma ideal_prod_is_ideal: "Ideal (I \<odot> J) R (+) (\<cdot>) \<zero> \<one>"
  unfolding ideal_prod_def by (rule ideal_generated_is_ideal)

lemma ideal_prod_subset_carrier: "I \<odot> J \<subseteq> R"
  unfolding ideal_prod_def by (rule ideal_generated_subset_carrier)

text \<open>Generators lie in the product.\<close>
lemma ideal_prod_memI:
  assumes I: "Ideal I R (+) (\<cdot>) \<zero> \<one>" and J: "Ideal J R (+) (\<cdot>) \<zero> \<one>"
    and i: "i \<in> I" and j: "j \<in> J"
  shows "i \<cdot> j \<in> I \<odot> J"
proof -
  interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> by (rule I)
  interpret J: Ideal J R "(+)" "(\<cdot>)" \<zero> \<one> by (rule J)
  have "i \<cdot> j \<in> R" using i j I.additive.subset J.additive.subset by blast
  moreover have "i \<cdot> j \<in> {i \<cdot> j |i j. i \<in> I \<and> j \<in> J}" using i j by blast
  ultimately have "i \<cdot> j \<in> {i \<cdot> j |i j. i \<in> I \<and> j \<in> J} \<inter> R" by blast
  also have "\<dots> \<subseteq> ideal_generated {i \<cdot> j |i j. i \<in> I \<and> j \<in> J}" by (rule ideal_generated_incl)
  finally show ?thesis unfolding ideal_prod_def .
qed

text \<open>The product is contained in both factors, hence in their intersection.\<close>
lemma ideal_prod_subset:
  assumes I: "Ideal I R (+) (\<cdot>) \<zero> \<one>" and J: "Ideal J R (+) (\<cdot>) \<zero> \<one>"
  shows "I \<odot> J \<subseteq> I \<inter> J"
proof -
  interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> by (rule I)
  interpret J: Ideal J R "(+)" "(\<cdot>)" \<zero> \<one> by (rule J)
  have gen: "{i \<cdot> j |i j. i \<in> I \<and> j \<in> J} \<inter> R \<subseteq> I \<inter> J"
  proof
    fix x assume "x \<in> {i \<cdot> j |i j. i \<in> I \<and> j \<in> J} \<inter> R"
    then obtain i j where x: "x = i \<cdot> j" and i: "i \<in> I" and j: "j \<in> J" by blast
    have "i \<cdot> j \<in> I" using i j J.additive.subset by (blast intro: I.Ideal(2))
    moreover have "i \<cdot> j \<in> J" using i j I.additive.subset by (blast intro: J.Ideal(1))
    ultimately show "x \<in> I \<inter> J" using x by simp
  qed
  have "Ideal (\<Inter> {I, J}) R (+) (\<cdot>) \<zero> \<one>"
    by (rule ideal_Inter) (use I J in auto)
  then have IJ: "Ideal (I \<inter> J) R (+) (\<cdot>) \<zero> \<one>" by simp
  show ?thesis
    unfolding ideal_prod_def by (rule ideal_generated_minimal[OF IJ]) (use gen in simp)
qed

text \<open>Commutativity: the generating sets coincide because the ring is commutative.\<close>
lemma ideal_prod_commute:
  assumes I: "Ideal I R (+) (\<cdot>) \<zero> \<one>" and J: "Ideal J R (+) (\<cdot>) \<zero> \<one>"
  shows "I \<odot> J = J \<odot> I"
proof -
  interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> by (rule I)
  interpret J: Ideal J R "(+)" "(\<cdot>)" \<zero> \<one> by (rule J)
  have "{i \<cdot> j |i j. i \<in> I \<and> j \<in> J} = {j \<cdot> i |i j. i \<in> I \<and> j \<in> J}"
    using I.additive.subset J.additive.subset by (blast intro: multiplicative.commutative)
  also have "\<dots> = {j \<cdot> i |j i. j \<in> J \<and> i \<in> I}" by blast
  finally show ?thesis unfolding ideal_prod_def by simp
qed


subsection \<open>The complete lattice of ideals\<close>

definition ideals :: "'a set set"
  where "ideals = {I. Ideal I R (+) (\<cdot>) \<zero> \<one>}"

lemma ideals_iff [simp]: "I \<in> ideals \<longleftrightarrow> Ideal I R (+) (\<cdot>) \<zero> \<one>"
  by (simp add: ideals_def)

interpretation ideal_order: Partial_Order ideals "(\<subseteq>)"
  by unfold_locales auto

interpretation ideal_lattice: Complete_Lattice ideals "(\<subseteq>)"
proof (unfold_locales)
  fix \<A> :: "'a set set" assume \<A>: "\<A> \<subseteq> ideals"
  \<comment> \<open>Supremum: the ideal generated by the union.\<close>
  let ?s = "ideal_generated (\<Union> \<A>)"
  have s_id: "Ideal ?s R (+) (\<cdot>) \<zero> \<one>" by (rule ideal_generated_is_ideal)
  have "ideal_order.is_sup ?s \<A>"
  proof (rule ideal_order.is_supI)
    show "ideal_order.upper_bound ?s \<A>"
    proof (rule ideal_order.upper_boundI)
      show "?s \<in> ideals" using s_id by simp
      fix I assume I: "I \<in> \<A>"
      then interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> using \<A> by auto
      have "I \<subseteq> \<Union> \<A> \<inter> R" using I I.additive.subset by blast
      then show "I \<subseteq> ?s" using ideal_generated_incl by blast
    qed
  next
    fix x assume "ideal_order.upper_bound x \<A>"
    then have xid: "Ideal x R (+) (\<cdot>) \<zero> \<one>" and dom: "\<And>I. I \<in> \<A> \<Longrightarrow> I \<subseteq> x"
      by (auto dest: ideal_order.upper_boundD simp: ideal_order.upper_bound_def)
    have "\<Union> \<A> \<inter> R \<subseteq> x"
    proof
      fix y assume "y \<in> \<Union> \<A> \<inter> R"
      then obtain I where "I \<in> \<A>" "y \<in> I" by blast
      then show "y \<in> x" using dom by blast
    qed
    then show "?s \<subseteq> x" using xid by (intro ideal_generated_minimal) auto
  qed
  then show "\<exists>s. ideal_order.is_sup s \<A>" ..
next
  fix \<A> :: "'a set set" assume \<A>: "\<A> \<subseteq> ideals"
  \<comment> \<open>Infimum: the intersection of \<open>\<A>\<close> together with \<open>R\<close>.\<close>
  let ?i = "\<Inter> (insert R \<A>)"
  have all_id: "\<And>I. I \<in> insert R \<A> \<Longrightarrow> Ideal I R (+) (\<cdot>) \<zero> \<one>"
    using \<A> whole_ideal by auto
  have i_id: "Ideal ?i R (+) (\<cdot>) \<zero> \<one>" by (rule ideal_Inter) (use all_id in auto)
  have "ideal_order.is_inf ?i \<A>"
  proof (rule ideal_order.is_infI)
    show "ideal_order.lower_bound ?i \<A>"
    proof (rule ideal_order.lower_boundI)
      show "?i \<in> ideals" using i_id by simp
      fix I assume "I \<in> \<A>" then show "?i \<subseteq> I" by blast
    qed
  next
    fix x assume "ideal_order.lower_bound x \<A>"
    then have xid: "Ideal x R (+) (\<cdot>) \<zero> \<one>" and dom: "\<And>I. I \<in> \<A> \<Longrightarrow> x \<subseteq> I"
      by (auto dest: ideal_order.lower_boundD simp: ideal_order.lower_bound_def)
    interpret x: Ideal x R "(+)" "(\<cdot>)" \<zero> \<one> by (rule xid)
    show "x \<subseteq> ?i" using dom x.additive.subset by blast
  qed
  then show "\<exists>i. ideal_order.is_inf i \<A>" ..
qed

end

end
