section \<open>Extension and contraction of ideals along a ring homomorphism\<close>

theory Ideal_Extension
  imports Ideal_Lattice
begin

text \<open>Along a homomorphism @{term \<eta>} of commutative rings @{text "R \<rightarrow> R'"} there are two natural
  operations on ideals:

    \<^item> \<^emph>\<open>contraction\<close> @{text "J \<mapsto> \<eta> -` J \<inter> R"}, the preimage of an ideal of the target, which is
      always an ideal of the source;

    \<^item> \<^emph>\<open>extension\<close> @{text "I \<mapsto> \<langle>\<eta> ` I\<rangle>"}, the ideal of the target \<^emph>\<open>generated by\<close> the image of an
      ideal of the source.  Generation is needed: the direct image @{term "\<eta> ` I"} need not be an
      ideal of @{term R'} --- it is closed under addition and under multiplication by elements of
      @{term "\<eta> ` R"}, but not in general by arbitrary elements of @{term R'}.  (For the inclusion of the integers in the rationals, the image of the even integers is
      not an ideal of the rationals.)

  These form an \<^emph>\<open>adjoint pair\<close> between the ideal lattices, ordered by inclusion:
  @{text "\<langle>\<eta> ` I\<rangle> \<subseteq> J \<longleftrightarrow> I \<subseteq> \<eta> -` J \<inter> R"}.  So this is a genuine instance of the
  @{locale Galois_Connection} locale of \<open>Order_Theory\<close>, and all of its consequences --- the unit and
  counit inequalities, monotonicity of both adjoints, the semi-inverse identities, and idempotence of
  the induced closure and kernel operators --- come for free.

  The two rings are commutative because \<open>ideal_generated\<close> and \<open>ideals\<close> are defined in
  the \<open>commutative_ring\<close> context.  As with the module homomorphism locale, the target ring's
  operations are written with primes and the source's unprimed; the two rings are \<^emph>\<open>separate\<close> here
  (unlike the shared scalar ring of a module homomorphism), so no parameter is shared.\<close>

locale comm_ring_homomorphism = ring_homomorphism +
  source: commutative_ring R "(+)" "(\<cdot>)" \<zero> \<one> +
  target: commutative_ring R' "(+')" "(\<cdot>')" "\<zero>'" "\<one>'"
begin

subsection \<open>Contraction: the preimage of an ideal\<close>

text \<open>The contraction of a subset of the target: its preimage, cut down to the source carrier.\<close>
definition contract :: "'b set \<Rightarrow> 'a set"
  where "contract J = \<eta> -` J \<inter> R"

lemma contract_subset: "contract J \<subseteq> R"
  by (auto simp: contract_def)

lemma contract_memI: "\<lbrakk> a \<in> R; \<eta> a \<in> J \<rbrakk> \<Longrightarrow> a \<in> contract J"
  by (simp add: contract_def)

lemma contract_memD: "a \<in> contract J \<Longrightarrow> a \<in> R \<and> \<eta> a \<in> J"
  by (simp add: contract_def)

lemma contract_mono: "J \<subseteq> J' \<Longrightarrow> contract J \<subseteq> contract J'"
  by (auto simp: contract_def)

text \<open>The preimage of an ideal is an ideal: it contains the zero because \<open>\<eta>\<close> preserves it, is closed
  under addition and negation because \<open>\<eta>\<close> is additive, and absorbs multiplication because \<open>\<eta>\<close> is
  multiplicative and \<open>J\<close> absorbs multiplication in the target.\<close>
theorem contract_ideal:
  assumes J: "Ideal J R' (+') (\<cdot>') \<zero>' \<one>'"
  shows "Ideal (contract J) R (+) (\<cdot>) \<zero> \<one>"
proof -
  interpret J: Ideal J R' "(+')" "(\<cdot>')" "\<zero>'" "\<one>'" by (rule J)
  \<comment> \<open>@{term \<eta>} carries the additive inverse to the additive inverse.  This is
    @{thm [source] Monoid_homomorphism.invertible_commutes_with_inverse} for the additive
    homomorphism; its \<open>invertible\<close> hypothesis is discharged automatically because the additive
    monoid of a ring is a group.\<close>
  have hom_neg: "\<eta> (source.additive.inverse a) = target.additive.inverse (\<eta> a)" if a: "a \<in> R" for a
    using a by (simp add: additive.invertible_commutes_with_inverse)
  \<comment> \<open>The preimage is an additive subgroup ...\<close>
  have "Subgroup (contract J) R (+) \<zero>"
  proof (rule source.additive.subgroupI)
    show "contract J \<subseteq> R" by (rule contract_subset)
    show "\<zero> \<in> contract J"
      by (rule contract_memI) (simp_all add: additive.commutes_with_unit J.additive.sub_unit_closed)
    show "\<And>g h. \<lbrakk> g \<in> contract J; h \<in> contract J \<rbrakk> \<Longrightarrow> g + h \<in> contract J"
    proof -
      fix g h assume "g \<in> contract J" and "h \<in> contract J"
      then have gR: "g \<in> R" and hR: "h \<in> R" and hg: "\<eta> g \<in> J" and hh: "\<eta> h \<in> J"
        by (auto dest: contract_memD)
      have "\<eta> (g + h) = \<eta> g +' \<eta> h"
        using gR hR by (simp add: additive.commutes_with_composition)
      then show "g + h \<in> contract J"
        using gR hR hg hh by (auto intro!: contract_memI J.additive.sub_composition_closed)
    qed
    show "\<And>g. g \<in> contract J \<Longrightarrow> source.additive.invertible g"
      using contract_subset by auto
    show "\<And>g. g \<in> contract J \<Longrightarrow> source.additive.inverse g \<in> contract J"
    proof -
      fix g assume "g \<in> contract J"
      then have gR: "g \<in> R" and hg: "\<eta> g \<in> J" by (auto dest: contract_memD)
      have "\<eta> (source.additive.inverse g) = target.additive.inverse (\<eta> g)"
        using gR by (rule hom_neg)
      moreover have "target.additive.inverse (\<eta> g) \<in> J"
        using hg J.additive.sub.invertible by (simp add: J.additive.submonoid_inverse_closed)
      ultimately show "source.additive.inverse g \<in> contract J"
        using gR by (auto intro!: contract_memI)
    qed
  qed
  then interpret S: Subgroup "contract J" R "(+)" \<zero> .
  \<comment> \<open>... and it absorbs multiplication from either side.\<close>
  show ?thesis
  proof unfold_locales
    fix a b assume a: "a \<in> R" and b: "b \<in> contract J"
    then have bR: "b \<in> R" and hb: "\<eta> b \<in> J" by (auto dest: contract_memD)
    have "\<eta> (a \<cdot> b) = \<eta> a \<cdot>' \<eta> b"
      using a bR by (simp add: multiplicative.commutes_with_composition)
    also have "\<dots> \<in> J" using a hb by (blast intro: J.Ideal(1))
    finally show "a \<cdot> b \<in> contract J" using a bR by (blast intro: contract_memI)
  next
    fix a b assume a: "a \<in> R" and b: "b \<in> contract J"
    then have bR: "b \<in> R" and hb: "\<eta> b \<in> J" by (auto dest: contract_memD)
    have "\<eta> (b \<cdot> a) = \<eta> b \<cdot>' \<eta> a"
      using a bR by (simp add: multiplicative.commutes_with_composition)
    also have "\<dots> \<in> J" using a hb by (blast intro: J.Ideal(2))
    finally show "b \<cdot> a \<in> contract J" using a bR by (blast intro: contract_memI)
  qed
qed

text \<open>The contraction of the target's zero ideal is the kernel; contracting the whole target gives
  the whole source.\<close>
lemma contract_whole: "contract R' = R"
  using map_closed by (auto simp: contract_def)


subsection \<open>Extension: the ideal generated by the image\<close>

text \<open>The extension of a subset of the source: the ideal of the target generated by its image.\<close>
definition extend :: "'a set \<Rightarrow> 'b set"
  where "extend I = target.ideal_generated (\<eta> ` I)"

lemma extend_ideal: "Ideal (extend I) R' (+') (\<cdot>') \<zero>' \<one>'"
  unfolding extend_def by (rule target.ideal_generated_is_ideal)

lemma extend_subset: "extend I \<subseteq> R'"
  unfolding extend_def by (rule target.ideal_generated_subset_carrier)

text \<open>The image lands inside the extension.  Note the intersection with @{term R'} in
  @{thm [source] target.ideal_generated_incl} is harmless: the image of a subset of @{term R} already
  lies in @{term R'}.\<close>
lemma extend_incl:
  assumes I: "I \<subseteq> R" shows "\<eta> ` I \<subseteq> extend I"
proof -
  have "\<eta> ` I \<subseteq> R'" using I map_closed by blast
  then have "\<eta> ` I \<inter> R' = \<eta> ` I" by blast
  then show ?thesis
    unfolding extend_def using target.ideal_generated_incl[of "\<eta> ` I"] by simp
qed

text \<open>Extension is minimal: any target ideal containing the image contains the extension.\<close>
lemma extend_minimal:
  assumes J: "Ideal J R' (+') (\<cdot>') \<zero>' \<one>'" and sub: "\<eta> ` I \<subseteq> J"
  shows "extend I \<subseteq> J"
  unfolding extend_def
proof (rule target.ideal_generated_minimal[OF J])
  show "\<eta> ` I \<inter> R' \<subseteq> J" using sub by blast
qed

lemma extend_mono:
  assumes II': "I \<subseteq> I'" and I': "I' \<subseteq> R" shows "extend I \<subseteq> extend I'"
proof (rule extend_minimal[OF extend_ideal])
  show "\<eta> ` I \<subseteq> extend I'" using II' extend_incl[OF I'] by blast
qed


subsection \<open>The adjunction\<close>

text \<open>\<^emph>\<open>Extension is left adjoint to contraction.\<close>  Both directions are immediate from minimality of
  the generated ideal and the definition of preimage --- which is exactly why extension had to be
  defined by generation: without it the left-to-right direction would fail.\<close>
theorem extend_contract_galois:
  assumes I: "I \<subseteq> R" and J: "Ideal J R' (+') (\<cdot>') \<zero>' \<one>'"
  shows "extend I \<subseteq> J \<longleftrightarrow> I \<subseteq> contract J"
proof
  assume "extend I \<subseteq> J"
  with extend_incl[OF I] have "\<eta> ` I \<subseteq> J" by blast
  then show "I \<subseteq> contract J" using I by (auto intro: contract_memI)
next
  assume "I \<subseteq> contract J"
  then have "\<eta> ` I \<subseteq> J" by (auto dest: contract_memD)
  then show "extend I \<subseteq> J" by (rule extend_minimal[OF J])
qed

text \<open>\<^emph>\<open>The Galois connection.\<close>  On the ideal lattices of the two rings, ordered by inclusion,
  extension and contraction form an adjoint pair.  Interpreting @{locale Galois_Connection} makes its
  whole development available: @{text unit} (@{text "I \<subseteq> contract (extend I)"}), @{text counit}
  (@{text "extend (contract J) \<subseteq> J"}), isotonicity of both maps, the semi-inverse laws
  @{text "extend (contract (extend I)) = extend I"} and
  @{text "contract (extend (contract J)) = contract J"}, and idempotence of the closure
  @{text "contract \<circ> extend"} and kernel @{text "extend \<circ> contract"}.\<close>
theorem ideal_galois_connection:
  "Galois_Connection source.ideals (\<subseteq>) target.ideals (\<subseteq>) extend contract"
proof (rule Galois_Connection.intro)
  \<comment> \<open>Inclusion is a partial order on any set of sets; \<open>Ideal_Lattice\<close>'s own interpretation is
    inside its \<open>commutative_ring\<close> context and so is not citable by name from here.\<close>
  show "Partial_Order source.ideals (\<subseteq>)" by unfold_locales auto
  show "Partial_Order target.ideals (\<subseteq>)" by unfold_locales auto
  show "Galois_Connection_axioms source.ideals (\<subseteq>) target.ideals (\<subseteq>) extend contract"
  proof
    show "extend \<in> source.ideals \<rightarrow> target.ideals"
      using extend_ideal by (auto simp: target.ideals_iff)
    show "contract \<in> target.ideals \<rightarrow> source.ideals"
      using contract_ideal by (auto simp: source.ideals_iff target.ideals_iff)
    fix I J assume "I \<in> source.ideals" and "J \<in> target.ideals"
    then have I: "Ideal I R (+) (\<cdot>) \<zero> \<one>" and J: "Ideal J R' (+') (\<cdot>') \<zero>' \<one>'"
      by (simp_all add: source.ideals_iff target.ideals_iff)
    interpret I: Ideal I R "(+)" "(\<cdot>)" \<zero> \<one> by (rule I)
    have IR: "I \<subseteq> R" by (rule I.additive.subset)
    show "extend I \<subseteq> J \<longleftrightarrow> I \<subseteq> contract J" by (rule extend_contract_galois[OF IR J])
  qed
qed

text \<open>The consequences of the adjunction, specialised to ideals.  These are obtained by interpreting
  @{thm [source] ideal_galois_connection} locally rather than by a @{command sublocale} declaration:
  a \<open>sublocale galois_connection\<close> inside this locale sends the interpretation machinery into a loop,
  because @{locale comm_ring_homomorphism} would then be a source of \<open>galois_connection\<close> facts about
  its own ideal lattices while still being elaborated.  The theorem form has no such problem, and
  consumers can \<^theory_text>\<open>interpret\<close> it wherever they need the full development.\<close>

context
begin

interpretation GC: Galois_Connection
  "source.ideals" "(\<subseteq>)" "target.ideals" "(\<subseteq>)" extend contract
  by (rule ideal_galois_connection)

text \<open>\<^emph>\<open>Unit\<close>: an ideal is contained in the contraction of its extension.\<close>
corollary contract_extend_incl:
  "Ideal I R (+) (\<cdot>) \<zero> \<one> \<Longrightarrow> I \<subseteq> contract (extend I)"
  using GC.unit by simp

text \<open>\<^emph>\<open>Counit\<close>: the extension of a contraction is contained in the original ideal.  The inclusion is
  in general strict --- for @{text "\<int> \<subseteq> \<rat>"} every nonzero ideal of @{text \<rat>} contracts to a
  nonzero ideal of @{text \<int>} whose extension is all of @{text \<rat>}.\<close>
corollary extend_contract_subset:
  "Ideal J R' (+') (\<cdot>') \<zero>' \<one>' \<Longrightarrow> extend (contract J) \<subseteq> J"
  using GC.counit by simp

text \<open>Both adjoints are isotone on ideals.\<close>
corollary extend_mono_ideal:
  "\<lbrakk> Ideal I R (+) (\<cdot>) \<zero> \<one>; Ideal I' R (+) (\<cdot>) \<zero> \<one>; I \<subseteq> I' \<rbrakk> \<Longrightarrow> extend I \<subseteq> extend I'"
  using isotone_le[OF GC.lower_isotone] by simp

corollary contract_mono_ideal:
  "\<lbrakk> Ideal J R' (+') (\<cdot>') \<zero>' \<one>'; Ideal J' R' (+') (\<cdot>') \<zero>' \<one>'; J \<subseteq> J' \<rbrakk>
   \<Longrightarrow> contract J \<subseteq> contract J'"
  using isotone_le[OF GC.upper_isotone] by simp

text \<open>The \<^emph>\<open>semi-inverse\<close> laws: extension and contraction are mutually inverse up to one round trip.\<close>
corollary extend_contract_extend:
  "Ideal I R (+) (\<cdot>) \<zero> \<one> \<Longrightarrow> extend (contract (extend I)) = extend I"
  using GC.lower_semi_inverse by simp

corollary contract_extend_contract:
  "Ideal J R' (+') (\<cdot>') \<zero>' \<one>' \<Longrightarrow> contract (extend (contract J)) = contract J"
  using GC.upper_semi_inverse by simp

text \<open>Hence @{text "contract \<circ> extend"} is a closure operator on the ideals of the source, and
  @{text "extend \<circ> contract"} a kernel operator on those of the target.\<close>
corollary closure_idempotent:
  "Ideal I R (+) (\<cdot>) \<zero> \<one> \<Longrightarrow> contract (extend (contract (extend I))) = contract (extend I)"
  using GC.closure_idempotent by simp

corollary kernel_idempotent:
  "Ideal J R' (+') (\<cdot>') \<zero>' \<one>' \<Longrightarrow> extend (contract (extend (contract J))) = extend (contract J)"
  using GC.kernel_idempotent by simp

end

end (* comm_ring_homomorphism *)

end
