section \<open>Iterating the Iso-Extension over a Finite Set of Algebraic Elements\<close>

theory Iso_Extension_Tower
  imports Iso_Extension Complex_Field_Extension
begin

text \<open>
  Starting from a homomorphism @{term f} defined on a subfield @{term K}, we extend it across a
  whole finite family of elements that are algebraic over @{term K}, reaching a homomorphism on
  the generated subfield @{term "generate_field (K \<union> A)"}.  Each extension step uses the
  single-element @{thm [source] field_hom_on.iso_extension}; the only external requirement is
  that the target field @{typ "'b"} contains a root for every non-constant polynomial, i.e. is
  ``closed enough''.  Over @{typ complex} this is the fundamental theorem of algebra.
\<close>

text \<open>The minimal polynomial is monic, so its image under @{term f} keeps the same degree.\<close>
lemma (in field_hom_on) map_poly_minpoly_degree:
  assumes m: "is_minpoly K a m"
  shows "degree (map_poly f m) = degree m"
proof -
  have "lead_coeff m = 1" using m by (simp add: is_minpoly_def)
  then have "f (lead_coeff m) = 1" by simp
  then show ?thesis by (intro map_poly_degree_eq) simp
qed

text \<open>A subfield is generated by itself.\<close>
lemma (in Subfield) generate_field_self: "generate_field K = K"
proof
  show "generate_field K \<subseteq> K" using Subfield_axioms subset_refl by (rule generate_field_least)
  show "K \<subseteq> generate_field K" by (rule subset_generate_field)
qed

text \<open>The single-element extension, packaged with the closed-target hypothesis discharging the
  existence of a root of the mapped minimal polynomial.\<close>
lemma field_hom_on_extend_one:
  assumes f: "field_hom_on K f"
    and alg: "algebraic_over K a"
    and closed: "\<And>q :: 'b :: field poly. 0 < degree q \<Longrightarrow> \<exists>b. poly q b = 0"
  shows "\<exists>g. field_hom_on (generate_field (K \<union> {a})) g \<and> (\<forall>x\<in>K. g x = (f :: 'a :: field \<Rightarrow> 'b) x)"
proof -
  have sf: "Subfield K" using f by (rule field_hom_on.axioms(1))
  obtain m where m: "is_minpoly K a m" using Subfield.minpoly_exists[OF sf alg] by blast
  have "degree (map_poly f m) > 0"
    using m by (simp add: field_hom_on.map_poly_minpoly_degree[OF f] Subfield.minpoly_degree_pos[OF sf])
  then obtain b where b: "poly (map_poly f m) b = 0" using closed by blast
  obtain g where g: "field_hom_on (eval_img K a) g" "g a = b" "\<forall>x\<in>K. g x = f x"
    using field_hom_on.iso_extension[OF f alg m b] by blast
  have "eval_img K a = generate_field (K \<union> {a})" using Subfield.eval_img_eq_generate_field[OF sf alg] .
  then show ?thesis using g by auto
qed

text \<open>Iterating over a finite set: @{term f} extends to the subfield generated by @{term K}
  together with finitely many elements algebraic over @{term K}.\<close>
theorem field_hom_on_extend_finite:
  assumes closed: "\<And>q :: 'b :: field poly. 0 < degree q \<Longrightarrow> \<exists>b. poly q b = 0"
    and "finite A"
    and "field_hom_on K (f :: 'a :: field \<Rightarrow> 'b)"
    and "\<And>a. a \<in> A \<Longrightarrow> algebraic_over K a"
  shows "\<exists>g. field_hom_on (generate_field (K \<union> A)) g \<and> (\<forall>x\<in>K. g x = f x)"
  using assms(2-4)
proof (induction A rule: finite_induct)
  case empty
  have sf: "Subfield K" using empty.prems(1) by (rule field_hom_on.axioms(1))
  have "generate_field (K \<union> {}) = K" by (simp add: Subfield.generate_field_self[OF sf])
  then show ?case using empty.prems(1) by auto
next
  case (insert a A)
  define L where "L = generate_field (K \<union> A)"
  obtain g1 where g1: "field_hom_on L g1" "\<forall>x\<in>K. g1 x = f x"
    using insert.IH[OF insert.prems(1)] insert.prems(2) by (auto simp: L_def)
  have KsubL: "K \<subseteq> L"
    unfolding L_def using subset_generate_field by blast
  have algL: "algebraic_over L a"
    using insert.prems(2)[of a] KsubL by (auto intro: algebraic_over_mono)
  obtain g2 where g2: "field_hom_on (generate_field (L \<union> {a})) g2" "\<forall>x\<in>L. g2 x = g1 x"
    using field_hom_on_extend_one[OF g1(1) algL closed] by blast
  have "generate_field (L \<union> {a}) = generate_field ({a} \<union> generate_field (K \<union> A))"
    unfolding L_def by (simp add: Un_commute)
  also have "\<dots> = generate_field ({a} \<union> (K \<union> A))"
    by (rule generate_field_Un_collapse2)
  also have "\<dots> = generate_field (K \<union> insert a A)"
    by (simp add: Un_commute Un_left_commute)
  finally have "generate_field (L \<union> {a}) = generate_field (K \<union> insert a A)" .
  moreover have "\<forall>x\<in>K. g2 x = f x"
    using g2(2) g1(2) KsubL by auto
  ultimately show ?case using g2(1) by auto
qed


text \<open>
  The generic field-extension development works over an arbitrary ambient @{typ "'a :: field"} via the @{locale Subfield} and
  @{locale field_hom_on} locales.  The complex-specific Galois theory of
  \<open>Complex_Field_Extension\<close> instead fixes @{typ complex} and packages automorphisms as the set
  @{const field_auto}. Now we connect the two.
\<close>
text \<open>The two subfield notions coincide on @{typ complex}.\<close>
lemma complex_subfield_iff_subfield: "complex_subfield K \<longleftrightarrow> Subfield K"
proof
  assume "complex_subfield K"
  then interpret complex_subfield K .
  show "Subfield K"
    using complex_subfield_axioms complex_subfield_def Subfield.intro by fastforce
next
  assume "Subfield K"
  then interpret Subfield K .
  show "complex_subfield K"
    by unfold_locales (auto intro: add_closed uminus_closed mult_closed inverse_closed)
qed

text \<open>A field homomorphism on @{term K} (in the generic sense) that maps @{term K} \<^emph>\<open>onto\<close>
  itself and fixes a base subfield @{term F} pointwise restricts to an element of the complex
  Galois group @{term "field_auto K F"}n.\<close>
lemma field_hom_on_imp_field_auto:
  assumes hom: "field_hom_on K \<sigma>"
    and onto: "\<sigma> ` K = K"
    and fix_F: "\<And>x. x \<in> F \<Longrightarrow> \<sigma> x = x" and FK: "F \<subseteq> K"
  shows "restrict \<sigma> K \<in> field_auto K F"
proof -
  interpret S: field_hom_on K \<sigma> by (rule hom)
  have bij: "bij_betw (restrict \<sigma> K) K K"
    by (simp add: S.inj_on bij_betw_def onto)
  show ?thesis
    unfolding field_auto_mem_iff
  proof (intro conjI ballI)
    show "restrict \<sigma> K \<in> K \<rightarrow>\<^sub>E K"
      using onto by auto
    show "bij_betw (restrict \<sigma> K) K K" by (rule bij)
    show "\<And>x. x \<in> F \<Longrightarrow> restrict \<sigma> K x = x" using fix_F FK by auto
  qed (use S.hom_1 S.one_closed S.hom_add S.add_closed S.hom_mult S.mult_closed in auto)
qed

end
