section \<open>Ideals of the Polynomial Ring; Kronecker's Construction\<close>

theory Poly_Ideal
  imports Poly_Ring Ideal_Theory "HOL-Library.Multiset"
begin

text \<open>This theory joins the carrier-set polynomial ring \<open>Poly_Ring\<close> to the
  ideal theory of \<open>Ideal_Theory\<close>.  The payoff is Kronecker's lemma: over a
  field, the ideal generated by an irreducible polynomial is maximal, so the quotient
  @{text "F[X]/(p)"} is a field.  This is the engine that builds field extensions (and,
  ultimately, finite fields) by adjoining roots of irreducible polynomials.\<close>

context Field
begin

text \<open>Inside a field the polynomial ring is a commutative ring, so its principal ideals are
  available through @{const commutative_ring.principal_ideal}.  We abbreviate the principal
  ideal @{text "(p)"} of @{text "F[X]"}.\<close>

text \<open>The principal ideal generated by @{term p} in @{text "F[X]"}, written out concretely.\<close>
definition poly_pideal :: "(nat \<Rightarrow> 'a) \<Rightarrow> (nat \<Rightarrow> 'a) set"
  where "poly_pideal p = {r \<otimes>\<^sub>P p | r. r \<in> poly_carrier}"

lemma poly_pideal_memI: "r \<in> poly_carrier \<Longrightarrow> r \<otimes>\<^sub>P p \<in> poly_pideal p"
  unfolding poly_pideal_def by blast

lemma poly_pideal_contains:
  assumes "p \<in> poly_carrier" shows "p \<in> poly_pideal p"
  by (metis assms poly_mult_one_left poly_one_closed poly_pideal_memI)

text \<open>@{const poly_pideal} agrees with the generic @{const commutative_ring.principal_ideal} of
  the polynomial ring, and is therefore an ideal of @{text "F[X]"}.\<close>
lemma poly_pideal_is_ideal:
  assumes p: "p \<in> poly_carrier"
  shows "Ideal (poly_pideal p) poly_carrier (\<oplus>\<^sub>P) (\<otimes>\<^sub>P) \<zero>\<^sub>P \<one>\<^sub>P"
proof -
  interpret comm: commutative_ring poly_carrier "(\<oplus>\<^sub>P)" "(\<otimes>\<^sub>P)" "\<zero>\<^sub>P" "\<one>\<^sub>P"
    by (rule poly_commutative_ring)
  show ?thesis
    using comm.principal_ideal_is_ideal p
    unfolding comm.principal_ideal_def poly_pideal_def by presburger
qed

text \<open>\<^emph>\<open>Kronecker's lemma.\<close>  For an irreducible @{term p}, the principal ideal @{text "(p)"} is
  maximal in @{text "F[X]"}.  Properness holds because @{term "\<one>\<^sub>P"} would force @{term p} to be a
  unit; maximality uses that @{text "F[X]"} is a PID (@{thm [source] poly_PID}): any ideal
  @{term J} between @{text "(p)"} and @{text "F[X]"} is principal, @{term "J = poly_pideal b"},
  and @{term "p = c \<otimes>\<^sub>P b"} forces (by irreducibility) either @{term b} a unit, so
  @{term "J = poly_carrier"}, or @{term c} a unit, so @{term "J \<subseteq> poly_pideal p"}.\<close>
theorem poly_irreducible_maximal:
  assumes irr: "poly_irreducible p"
  shows "Ideal.maximal_ideal (poly_pideal p) poly_carrier (\<oplus>\<^sub>P) (\<otimes>\<^sub>P) \<zero>\<^sub>P \<one>\<^sub>P"
proof -
  have p: "p \<in> poly_carrier" using irr by (rule poly_irreducibleD_carrier)
  have pnu: "\<not> poly_unit p" using irr by (rule poly_irreducibleD_nonunit)
  interpret I: Ideal "poly_pideal p" poly_carrier "(\<oplus>\<^sub>P)" "(\<otimes>\<^sub>P)" "\<zero>\<^sub>P" "\<one>\<^sub>P"
    by (rule poly_pideal_is_ideal[OF p])
  \<comment> \<open>Properness: the ideal omits @{term "\<one>\<^sub>P"}, else @{term p} would be a unit.\<close>
  have proper: "poly_pideal p \<noteq> poly_carrier"
  proof
    assume "poly_pideal p = poly_carrier"
    then obtain r where r: "r \<in> poly_carrier" and rp: "\<one>\<^sub>P = r \<otimes>\<^sub>P p"
      unfolding poly_pideal_def by blast
    then have pr1: "p \<otimes>\<^sub>P r = \<one>\<^sub>P" 
      by (simp add: p poly_mult_comm)
    with pnu show False
      using p poly_unitI r rp by force
  qed
  \<comment> \<open>Maximality: any larger ideal is principal and collapses to @{text "(p)"} or all of @{text "F[X]"}.\<close>
  have "\<forall>J. Ideal J poly_carrier (\<oplus>\<^sub>P) (\<otimes>\<^sub>P) \<zero>\<^sub>P \<one>\<^sub>P \<longrightarrow> poly_pideal p \<subseteq> J
            \<longrightarrow> J = poly_pideal p \<or> J = poly_carrier"
  proof (intro allI impI)
    fix J assume J: "Ideal J poly_carrier (\<oplus>\<^sub>P) (\<otimes>\<^sub>P) \<zero>\<^sub>P \<one>\<^sub>P" and sub: "poly_pideal p \<subseteq> J"
    interpret J: Ideal J poly_carrier "(\<oplus>\<^sub>P)" "(\<otimes>\<^sub>P)" "\<zero>\<^sub>P" "\<one>\<^sub>P" by (rule J)
    obtain b where b: "b \<in> poly_carrier" and Jeq: "J = {r \<otimes>\<^sub>P b | r. r \<in> poly_carrier}"
      using poly_PID[OF J] by blast
    have JeqP: "J = poly_pideal b" unfolding poly_pideal_def by (rule Jeq)
    \<comment> \<open>@{term p} lies in @{term J}, so @{term p} is a multiple of @{term b}.\<close>
    have "p \<in> J" using sub poly_pideal_contains[OF p] by blast
    then obtain c where c: "c \<in> poly_carrier" and pcb: "p = c \<otimes>\<^sub>P b"
      using JeqP unfolding poly_pideal_def by blast
    from poly_irreducibleD_factor[OF irr c b pcb] show "J = poly_pideal p \<or> J = poly_carrier"
    proof
      \<comment> \<open>If @{term b} is a unit then @{term J} is all of @{text "F[X]"}.\<close>
      assume "poly_unit b"
      then obtain b' where b': "b' \<in> poly_carrier" and "b' \<otimes>\<^sub>P b = \<one>\<^sub>P"
        unfolding poly_unit_def by blast
      \<comment> \<open>@{term "\<one>\<^sub>P = b' \<otimes>\<^sub>P b"} is a multiple of @{term b}, hence in @{term "J = poly_pideal b"}.\<close>
      have "b' \<otimes>\<^sub>P b \<in> poly_pideal b" using b' by (rule poly_pideal_memI)
      then have "\<one>\<^sub>P \<in> J" using \<open>b' \<otimes>\<^sub>P b = \<one>\<^sub>P\<close> JeqP by simp
      then have "poly_carrier \<subseteq> J"
        using J.Ideal(1) \<open>\<one>\<^sub>P \<in> J\<close> poly_mult_one_right by fastforce
      then have "J = poly_carrier" using J.additive.subset by blast
      then show ?thesis ..
    next
      \<comment> \<open>If @{term c} is a unit then @{term b} is a multiple of @{term p}, so \<open>J \<subseteq> (p)\<close>.\<close>
      assume "poly_unit c"
      then obtain c' where c': "c' \<in> poly_carrier" and "c \<otimes>\<^sub>P c' = \<one>\<^sub>P" and c'c: "c' \<otimes>\<^sub>P c = \<one>\<^sub>P"
        unfolding poly_unit_def by blast
      \<comment> \<open>From @{term "p = c \<otimes>\<^sub>P b"}: @{term "b = c' \<otimes>\<^sub>P p"}.\<close>
      have "c' \<otimes>\<^sub>P p = c' \<otimes>\<^sub>P (c \<otimes>\<^sub>P b)" using pcb by simp
      also have "\<dots> = b" using b
        by (metis c c' c'c poly_mult_assoc poly_mult_one_left)
      finally have beq: "b = c' \<otimes>\<^sub>P p" ..
      \<comment> \<open>Hence every multiple of @{term b} is a multiple of @{term p}: \<open>J \<subseteq> (p)\<close>.\<close>
      have "J \<subseteq> poly_pideal p"
      proof
        fix x assume "x \<in> J"
        then obtain r where "r \<in> poly_carrier" "x = r \<otimes>\<^sub>P b"
          using JeqP unfolding poly_pideal_def by blast
        then show "x \<in> poly_pideal p" using poly_pideal_memI
          using I.Ideal(1) beq c' by presburger
      qed
      then have "J = poly_pideal p" using sub by blast
      then show ?thesis ..
    qed
  qed
  then show ?thesis using proper unfolding I.maximal_ideal_def by blast
qed

text \<open>The principal ideal @{text "(p)"} is an ideal of the \<^emph>\<open>commutative\<close> polynomial ring, so
  the quotient theory of @{locale ideal_in_comm_ring} applies to it.\<close>
lemma poly_pideal_in_comm_ring:
  assumes p: "p \<in> poly_carrier"
  shows "ideal_in_comm_ring (poly_pideal p) poly_carrier (\<oplus>\<^sub>P) (\<otimes>\<^sub>P) \<zero>\<^sub>P \<one>\<^sub>P"
  by (simp add: ideal_in_comm_ring.intro p poly_commutative_ring poly_pideal_is_ideal)

text \<open>\<^emph>\<open>Kronecker's theorem.\<close>  For an irreducible @{term p}, the principal ideal @{text "(p)"} is
  a maximal ideal of the \<^emph>\<open>commutative\<close> polynomial ring @{text "F[X]"}.  By the maximal-ideal
  characterisation @{thm [source] ideal_in_comm_ring.maximal_ideal_iff_quotient_field}, this is
  exactly the statement that the quotient @{text "F[X]/(p)"} is a field: it is nontrivial and
  every nonzero coset is invertible.\<close>
theorem poly_quotient_field:
  assumes irr: "poly_irreducible p"
  shows "ideal_in_comm_ring (poly_pideal p) poly_carrier (\<oplus>\<^sub>P) (\<otimes>\<^sub>P) \<zero>\<^sub>P \<one>\<^sub>P
         \<and> Ideal.maximal_ideal (poly_pideal p) poly_carrier (\<oplus>\<^sub>P) (\<otimes>\<^sub>P) \<zero>\<^sub>P \<one>\<^sub>P"
  by (simp add: irr poly_irreducibleD_carrier poly_irreducible_maximal
      poly_pideal_in_comm_ring)


subsection \<open>The size of the quotient ring\<close>

text \<open>Membership in the principal ideal @{text "(p)"} is detected by the remainder: @{term x} is a
  multiple of @{term p} iff @{term "pmod x p = \<zero>\<^sub>P"}.\<close>
lemma poly_pideal_iff_pmod:
  assumes p: "p \<in> poly_carrier" and pnz: "p \<noteq> \<zero>\<^sub>P" and x: "x \<in> poly_carrier"
  shows "x \<in> poly_pideal p \<longleftrightarrow> pmod x p = \<zero>\<^sub>P"
proof
  assume "x \<in> poly_pideal p"
  then obtain r where r: "r \<in> poly_carrier" and xr: "x = r \<otimes>\<^sub>P p"
    unfolding poly_pideal_def by blast
  \<comment> \<open>\<open>x = (p \<otimes> r) \<oplus> \<zero>\<close>, so its remainder is @{term "\<zero>\<^sub>P"}.\<close>
  have "x = (p \<otimes>\<^sub>P r) \<oplus>\<^sub>P \<zero>\<^sub>P"
    by (metis p poly_add_comm poly_add_zero poly_mult_comm poly_zero_closed r x xr) 
  then show "pmod x p = \<zero>\<^sub>P"
    using pmod_unique[OF x p pnz r poly_zero_closed] by simp
next
  assume z: "pmod x p = \<zero>\<^sub>P"
  obtain q where q: "q \<in> poly_carrier" and xeq: "x = (p \<otimes>\<^sub>P q) \<oplus>\<^sub>P pmod x p"
    using pmod_spec[OF x p pnz] by blast
  have "x = (p \<otimes>\<^sub>P q) \<oplus>\<^sub>P \<zero>\<^sub>P" 
    using xeq z by simp
  also have "\<dots> = q \<otimes>\<^sub>P p"
    using p q by (simp add: poly_add_comm poly_add_zero poly_mult_comm poly_zero_closed poly_mult_closed)
  finally have "x = q \<otimes>\<^sub>P p" .
  then show "x \<in> poly_pideal p" using q by (auto simp: poly_pideal_def)
qed

text \<open>The coset map \<open>r \<mapsto> coset r\<close> restricted to @{term "low_poly (degree p)"}
  is a bijection onto the set of cosets: every coset has a unique representative of degree below
  @{term p}.  Injectivity is uniqueness of @{const pmod} (equal cosets have equal remainders, and a
  low-degree polynomial is its own remainder).\<close>
theorem bij_betw_low_poly_cosets:
  assumes p: "p \<in> poly_carrier" and pnz: "p \<noteq> \<zero>\<^sub>P"
  shows "bij_betw (Ideal.coset (poly_pideal p) poly_carrier (\<oplus>\<^sub>P) \<zero>\<^sub>P)
                  (low_poly (degree p))
                  (Ideal.quotient_set (poly_pideal p) poly_carrier (\<oplus>\<^sub>P) \<zero>\<^sub>P)"
proof -
  interpret I: ideal_in_comm_ring "poly_pideal p" poly_carrier "(\<oplus>\<^sub>P)" "(\<otimes>\<^sub>P)" "\<zero>\<^sub>P" "\<one>\<^sub>P"
    by (rule poly_pideal_in_comm_ring[OF p])
  \<comment> \<open>Two carrier polynomials are in the same coset iff their difference is a multiple of @{term p}.\<close>
  \<comment> \<open>The additive-group inverse in @{text "F[X]"} is the polynomial negation @{term "\<ominus>\<^sub>P y"}.\<close>
  have inv_eq: "I.additive.inverse y = \<ominus>\<^sub>P y" if y: "y \<in> poly_carrier" for y
    by (simp add: poly_diff_zero_eq poly_neg_closed poly_neg_neg y)
  have same_coset: "I.coset x = I.coset y \<longleftrightarrow> x \<oplus>\<^sub>P (\<ominus>\<^sub>P y) \<in> poly_pideal p"
    if x: "x \<in> poly_carrier" and y: "y \<in> poly_carrier" for x y
    using I.coset_eq_iff[OF x y] by (simp add: inv_eq[OF y])
  \<comment> \<open>A polynomial of degree below @{term p} that is a multiple of @{term p} must be zero.\<close>
  have low_mult_zero: "d = \<zero>\<^sub>P"
    if dc: "d \<in> poly_carrier" "d = \<zero>\<^sub>P \<or> degree d < degree p" "d \<in> poly_pideal p" for d
    by (metis that p pmod_small pnz poly_pideal_iff_pmod)
  show ?thesis
  proof (rule bij_betw_imageI)
    \<comment> \<open>Injective: equal cosets give equal remainders, and low-degree polys are their own remainders.\<close>
    show "inj_on (I.coset) (low_poly (degree p))"
    proof (rule inj_onI)
      fix r1 r2 assume r1: "r1 \<in> low_poly (degree p)" and r2: "r2 \<in> low_poly (degree p)"
        and eq: "I.coset r1 = I.coset r2"
      have r1c: "r1 \<in> poly_carrier" using r1 by (rule low_poly_closed)
      have r2c: "r2 \<in> poly_carrier" using r2 by (rule low_poly_closed)
      have d1: "r1 = \<zero>\<^sub>P \<or> degree r1 < degree p" using r1 r1c by (simp add: low_poly_iff_degree)
      have d2: "r2 = \<zero>\<^sub>P \<or> degree r2 < degree p" using r2 r2c by (simp add: low_poly_iff_degree)
      \<comment> \<open>The difference is a low-degree multiple of @{term p}, hence zero.\<close>
      have diffc: "r1 \<oplus>\<^sub>P (\<ominus>\<^sub>P r2) \<in> poly_carrier"
        using r1c r2c poly_neg_closed by (simp add: poly_add_closed)
      have "r1 \<oplus>\<^sub>P (\<ominus>\<^sub>P r2) \<in> poly_pideal p" using same_coset[OF r1c r2c] eq by simp
      moreover have "r1 \<oplus>\<^sub>P (\<ominus>\<^sub>P r2) = \<zero>\<^sub>P \<or> degree (r1 \<oplus>\<^sub>P (\<ominus>\<^sub>P r2)) < degree p"
      proof (cases "r1 \<oplus>\<^sub>P (\<ominus>\<^sub>P r2) = \<zero>\<^sub>P")
        case False
        \<comment> \<open>The difference is nonzero, so @{term "degree p > 0"} (else @{term r1}, @{term r2} both zero).\<close>
        have dp: "degree p > 0"
          using d1 d2 poly_add_neg_right False by force
        have "degree (r1 \<oplus>\<^sub>P (\<ominus>\<^sub>P r2)) \<le> max (degree r1) (degree r2)"
          by (metis degree_add_le degree_neg poly_neg_closed r1c r2c)
        then show ?thesis using d1 d2 dp by auto
      qed simp
      ultimately have "r1 \<oplus>\<^sub>P (\<ominus>\<^sub>P r2) = \<zero>\<^sub>P" using low_mult_zero[OF diffc] by blast
      then show "r1 = r2" using poly_diff_zero_eq[OF r1c r2c] by simp
    qed
    \<comment> \<open>Image is exactly the set of cosets.\<close>
    show "(I.coset) ` low_poly (degree p) = I.quotient_set"
    proof
      show "(I.coset) ` low_poly (degree p) \<subseteq> I.quotient_set"
        by (meson I.coset_in_quotient_set image_subsetI low_poly_closed)
      show "I.quotient_set \<subseteq> (I.coset) ` low_poly (degree p)"
      proof
        fix C assume "C \<in> I.quotient_set"
        then obtain a where a: "a \<in> poly_carrier" and Ca: "C = I.coset a"
          using I.quotient_set_repr by blast
        \<comment> \<open>The remainder of @{term a} is a low-degree representative of the same coset.\<close>
        have mc: "pmod a p \<in> poly_carrier" using pmod_closed[OF a p pnz] .
        have pmc: "pmod a p \<in> low_poly (degree p)"
          using mc pmod_degree[OF a p pnz] by (simp add: low_poly_iff_degree)
        \<comment> \<open>\<open>a \<oplus> \<ominus>(pmod a p) = p \<otimes> q \<in> (p)\<close>, so @{term a} and @{term "pmod a p"} share a coset.\<close>
        obtain q where q: "q \<in> poly_carrier" and aeq: "a = (p \<otimes>\<^sub>P q) \<oplus>\<^sub>P pmod a p"
          using pmod_spec[OF a p pnz] by blast
        have pqc: "p \<otimes>\<^sub>P q \<in> poly_carrier" using p q by (rule poly_mult_closed)
        \<comment> \<open>Cancel @{term "pmod a p"}: \<open>a \<oplus> \<ominus>(pmod a p) = p \<otimes> q\<close>.\<close>
        have "a \<oplus>\<^sub>P (\<ominus>\<^sub>P pmod a p) = p \<otimes>\<^sub>P q"
          by (metis I.additive.commute_iff_inverse aeq inv_eq mc poly_add_comm pqc) 
        then have "a \<oplus>\<^sub>P (\<ominus>\<^sub>P pmod a p) = q \<otimes>\<^sub>P p"
          using poly_mult_comm[OF p q] by simp
        then have mem: "a \<oplus>\<^sub>P (\<ominus>\<^sub>P pmod a p) \<in> poly_pideal p"
          using q by (simp add: poly_pideal_memI)
        have "I.coset a = I.coset (pmod a p)"
          by (rule iffD2[OF same_coset[OF a mc] mem])
        then show "C \<in> (I.coset) ` low_poly (degree p)"
          by (simp add: Ca pmc)
      qed
    qed
  qed
qed

text \<open>\<^emph>\<open>The quotient \<open>F[X]/(p)\<close> has \<open>\<bar>F\<bar>\<^sup>d\<^sup>e\<^sup>g\<^sup>p\<close> elements\<close> when the field @{term F} is finite:
  the cosets are in bijection with the @{term "card R ^ degree p"} polynomials of degree below
  @{term p}.\<close>
theorem card_poly_quotient:
  assumes "finite R" "p \<in> poly_carrier" "p \<noteq> \<zero>\<^sub>P"
  shows "card (Ideal.quotient_set (poly_pideal p) poly_carrier (\<oplus>\<^sub>P) \<zero>\<^sub>P) = card R ^ degree p"
  by (metis bij_betw_low_poly_cosets bij_betw_same_card card_low_poly assms)


subsection \<open>Divisibility and Euclid's lemma\<close>

text \<open>Divisibility in @{text "F[X]"}: @{term d} divides @{term x} when @{term x} is a multiple of
  @{term d}.  This is exactly membership of @{term x} in the principal ideal @{term "poly_pideal d"}.\<close>
definition poly_dvd :: "(nat \<Rightarrow> 'a) \<Rightarrow> (nat \<Rightarrow> 'a) \<Rightarrow> bool"
  where "poly_dvd d x \<longleftrightarrow> (\<exists>q. q \<in> poly_carrier \<and> x = q \<otimes>\<^sub>P d)"

lemma poly_dvd_iff_mem_pideal: "poly_dvd d x \<longleftrightarrow> x \<in> poly_pideal d"
  unfolding poly_dvd_def poly_pideal_def by blast

text \<open>A concrete divisibility witness with a polynomial divisor necessarily has a polynomial
  dividend.  This recovers the carrier condition after working with the ambient function type.\<close>
lemma poly_dvd_closed:
  assumes dvd: "poly_dvd d x" and d: "d \<in> poly_carrier"
  shows "x \<in> poly_carrier"
proof -
  obtain q where q: "q \<in> poly_carrier" and xeq: "x = q \<otimes>\<^sub>P d"
    using dvd unfolding poly_dvd_def by blast
  then show ?thesis using d by (simp add: poly_mult_closed)
qed

text \<open>For a nonzero divisor, concrete polynomial divisibility is equivalent to having zero
  remainder under the polynomial division algorithm.\<close>
lemma poly_dvd_iff_pmod_zero:
  assumes d: "d \<in> poly_carrier" and dnz: "d \<noteq> \<zero>\<^sub>P"
    and x: "x \<in> poly_carrier"
  shows "poly_dvd d x \<longleftrightarrow> pmod x d = \<zero>\<^sub>P"
  using poly_dvd_iff_mem_pideal poly_pideal_iff_pmod[OF d dnz x] by blast

text \<open>\<^emph>\<open>Euclid's lemma / irreducibles are prime.\<close>  For an irreducible @{term p}, if @{term p}
  divides a product @{term "a \<otimes>\<^sub>P b"} then it divides one of the factors.  This is primality of the
  maximal ideal @{term "poly_pideal p"} (@{thm [source] ideal_in_comm_ring.maximal_imp_prime_ideal}
  applied to @{thm [source] poly_irreducible_maximal}).\<close>
theorem poly_irreducible_prime:
  assumes irr: "poly_irreducible p"
    and a: "a \<in> poly_carrier" and b: "b \<in> poly_carrier"
    and dvd: "poly_dvd p (a \<otimes>\<^sub>P b)"
  shows "poly_dvd p a \<or> poly_dvd p b"
proof -
  have p: "p \<in> poly_carrier" using irr by (rule poly_irreducibleD_carrier)
  interpret I: ideal_in_comm_ring "poly_pideal p" poly_carrier "(\<oplus>\<^sub>P)" "(\<otimes>\<^sub>P)" "\<zero>\<^sub>P" "\<one>\<^sub>P"
    by (rule poly_pideal_in_comm_ring[OF p])
  have "I.prime_ideal" using poly_irreducible_maximal[OF irr] by (rule I.maximal_imp_prime_ideal)
  \<comment> \<open>Primality: \<open>a \<otimes> b \<in> (p)\<close> gives \<open>a \<in> (p)\<close> or \<open>b \<in> (p)\<close>.\<close>
  have "a \<in> poly_pideal p \<or> b \<in> poly_pideal p"
    using I.prime_ideal_def \<open>I.prime_ideal\<close> a b dvd poly_dvd_iff_mem_pideal by blast
  then show ?thesis by (simp add: poly_dvd_iff_mem_pideal)
qed

text \<open>An irreducible polynomial does not divide @{term "\<one>\<^sub>P"} (else it would be a unit).\<close>
lemma poly_irreducible_not_dvd_one:
  assumes irr: "poly_irreducible p" shows "\<not> poly_dvd p \<one>\<^sub>P"
proof
  assume "poly_dvd p \<one>\<^sub>P"
  then obtain q where q: "q \<in> poly_carrier" and "\<one>\<^sub>P = q \<otimes>\<^sub>P p"
    unfolding poly_dvd_def by blast
  then have "poly_unit p" 
    using poly_unitI irr poly_irreducibleD_carrier poly_mult_comm by presburger
  with poly_irreducibleD_nonunit[OF irr] show False ..
qed

text \<open>\<^emph>\<open>Euclid's lemma for products.\<close>  If an irreducible @{term p} divides a product of a list of
  polynomials, it divides one of them.  (Base case: it cannot divide the empty product @{term "\<one>\<^sub>P"};
  step: split off the head with @{thm [source] poly_irreducible_prime}.)\<close>
lemma poly_irreducible_prime_list:
  assumes irr: "poly_irreducible p"
  shows "\<lbrakk> \<forall>f\<in>set fs. f \<in> poly_carrier; poly_dvd p (poly_prod fs) \<rbrakk>
           \<Longrightarrow> \<exists>f\<in>set fs. poly_dvd p f"
proof (induct fs)
  case Nil
  then have "poly_dvd p \<one>\<^sub>P" by simp
  with poly_irreducible_not_dvd_one[OF irr] show ?case ..
next
  case (Cons g gs)
  have gc: "g \<in> poly_carrier" using Cons.prems(1) by simp
  have gsc: "\<forall>f\<in>set gs. f \<in> poly_carrier" using Cons.prems(1) by simp
  have gsprod: "poly_prod gs \<in> poly_carrier"
    by (rule poly_prod_closed) (use gsc in blast)
  have "poly_dvd p (g \<otimes>\<^sub>P poly_prod gs)" using Cons.prems(2) by simp
  then have "poly_dvd p g \<or> poly_dvd p (poly_prod gs)"
    using poly_irreducible_prime[OF irr gc gsprod] by simp
  then show ?case
    using Cons.hyps gsc by force
qed


subsection \<open>Uniqueness of the irreducible factorisation\<close>

text \<open>A nonzero divisor has degree at most that of its multiple.\<close>
lemma poly_dvd_degree_le:
  assumes dvd: "poly_dvd d x" and dc: "d \<in> poly_carrier" and xnz: "x \<noteq> \<zero>\<^sub>P"
  shows "degree d \<le> degree x"
proof -
  obtain q where q: "q \<in> poly_carrier" and xeq: "x = q \<otimes>\<^sub>P d"
    using dvd unfolding poly_dvd_def by blast
  have "degree x = degree q + degree d" using xeq degree_mult[OF q dc]
    using dc poly_mult_comm poly_mult_zero_right q xnz by force
  then show ?thesis by simp
qed

text \<open>Two monic irreducibles that divide one another are equal: @{term p} dividing the irreducible
  @{term q} makes @{term p} a unit or an associate of @{term q}; being a non-unit monic, it equals
  the monic @{term q}.\<close>
lemma monic_irreducible_dvd_eq:
  assumes ip: "poly_irreducible p" and iq: "poly_irreducible q"
    and mp: "poly_monic p" and mq: "poly_monic q" and dvd: "poly_dvd p q"
  shows "p = q"
proof -
  have p: "p \<in> poly_carrier" using ip by (rule poly_irreducibleD_carrier)
  have qc: "q \<in> poly_carrier" using iq by (rule poly_irreducibleD_carrier)
  obtain c where c: "c \<in> poly_carrier" and qcp: "q = c \<otimes>\<^sub>P p" and uc: "poly_unit c"
    using dvd unfolding poly_dvd_def
    by (metis ip iq poly_irreducible_def)
  \<comment> \<open>@{term q} irreducible and @{term "q = c \<otimes>\<^sub>P p"}: one of @{term c}, @{term p} is a unit.\<close>
  \<comment> \<open>A unit has degree @{text 0}, so @{term c} is a nonzero constant and @{term p}, @{term q}
      have equal degree; being monic, they have equal leading terms too.\<close>
  have cconst: "c = poly_const (c 0) \<and> c 0 \<noteq> \<zero>" and dc0: "degree c = 0"
    using poly_unit_imp_const[OF uc] by auto
  have c0R: "c 0 \<in> R" using c by (rule poly_carrier_coeff_closed)
  have pnz: "p \<noteq> \<zero>\<^sub>P" using ip by (rule poly_irreducibleD_nonzero)
  \<comment> \<open>Leading coefficient of @{term "q = poly_const (c 0) \<otimes>\<^sub>P p"} is @{term "c 0 \<cdot> lead_coeff p"}.\<close>
  have "lead_coeff q = c 0 \<cdot> lead_coeff p"
    using qcp cconst lead_coeff_poly_const_mult[OF c0R _ p pnz] by simp
  moreover have "lead_coeff q = \<one>"  "lead_coeff p = \<one>" 
    using mp mq by (simp_all add: poly_monic_def)
  ultimately have "c 0 = \<one>" using c0R by simp
  \<comment> \<open>Hence @{term "c = \<one>\<^sub>P"} and @{term "q = p"}.\<close>
  then show ?thesis using qcp p
    using cconst poly_mult_one_left by auto
qed

text \<open>Pulling a factor out of a product: if @{term g} occurs in @{term gs}, the product factors as
  @{term g} times the product of the rest.\<close>
lemma poly_prod_remove1:
  assumes "g \<in> set gs" and "\<forall>f\<in>set gs. f \<in> poly_carrier"
  shows "poly_prod gs = g \<otimes>\<^sub>P poly_prod (remove1 g gs)"
  using assms
proof (induct gs)
  case Nil then show ?case by simp
next
  case (Cons h hs)
  show ?case
  proof (cases "g = h")
    case True then show ?thesis by simp
  next
    case False
    then have gs: "g \<in> set hs" and hc: "h \<in> poly_carrier" and hsc: "\<forall>f\<in>set hs. f \<in> poly_carrier" 
      using Cons.prems by auto
    have gc: "g \<in> poly_carrier" using gs hsc by blast
    have hsprod: "poly_prod (remove1 g hs) \<in> poly_carrier"
      by (meson hsc notin_set_remove1 poly_prod_closed)
    have "poly_prod (h # hs) = h \<otimes>\<^sub>P poly_prod hs" by simp
    also have "\<dots> = g \<otimes>\<^sub>P (h \<otimes>\<^sub>P poly_prod (remove1 g hs))"
      using hc gc hsprod Cons
      by (metis gs hsc poly_mult_assoc poly_mult_comm)
    finally show ?thesis
      using False by simp
  qed
qed


text \<open>\<^emph>\<open>Uniqueness of the monic irreducible factorisation.\<close>  Two lists of monic irreducibles with
  equal products are permutations of one another.  By induction on the first
  list: the head @{term f} divides the other product, hence equals some monic 
  irreducible @{term g} in it; cancel @{term f} and recurse on the remaining factors.\<close>
theorem factorization_unique:
  "\<lbrakk> \<forall>f\<in>set fs. poly_irreducible f \<and> poly_monic f;
     \<forall>g\<in>set gs. poly_irreducible g \<and> poly_monic g;
     poly_prod fs = poly_prod gs \<rbrakk> \<Longrightarrow> mset fs = mset gs"
proof (induct fs arbitrary: gs)
  case Nil 
  \<comment> \<open>Empty product is @{term "\<one>\<^sub>P"}; a nonempty @{term gs} would have an irreducible dividing
      @{term "\<one>\<^sub>P"}.\<close>
  have "gs = []"
  proof (rule ccontr)
    assume "gs \<noteq> []"
    then obtain g gs' where gs: "gs = g # gs'" by (cases gs) auto
    have ig: "poly_irreducible g" using Nil.prems(2) gs by simp
    have gsc: "\<forall>f\<in>set gs. f \<in> poly_carrier"
      using Nil.prems(2) by (auto simp: poly_irreducibleD_carrier)
    have "poly_prod gs = \<one>\<^sub>P" using Nil.prems(3) by simp
    then have "g \<otimes>\<^sub>P poly_prod gs' = \<one>\<^sub>P" using gs by simp
    \<comment> \<open>So @{term g} divides @{term "\<one>\<^sub>P"} --- impossible for an irreducible.\<close>
    moreover have "poly_prod gs' \<in> poly_carrier"
      using gsc gs by (auto intro!: poly_prod_closed)
    ultimately have "poly_dvd g \<one>\<^sub>P"
      unfolding poly_dvd_def
      using poly_irreducibleD_carrier[OF ig] by (metis poly_mult_comm)
    with poly_irreducible_not_dvd_one[OF ig] show False ..
  qed
  then show ?case using Nil.prems(3) by simp
next
  case (Cons f fs')
  have iff: "poly_irreducible f" and mf: "poly_monic f" using Cons.prems(1) by auto
  have fc: "f \<in> poly_carrier" using iff by (rule poly_irreducibleD_carrier)
  have fs'c: "\<forall>h\<in>set fs'. poly_irreducible h \<and> poly_monic h" using Cons.prems(1) by simp
  have gsc: "\<forall>g\<in>set gs. poly_irreducible g \<and> poly_monic g" using Cons.prems(2) .
  have gscarr: "\<forall>g\<in>set gs. g \<in> poly_carrier"
    using gsc by (auto simp: poly_irreducibleD_carrier)
  have fs'carr: "\<forall>h\<in>set fs'. h \<in> poly_carrier"
    using fs'c by (auto simp: poly_irreducibleD_carrier)
  have fs'prod: "poly_prod fs' \<in> poly_carrier"
    by (rule poly_prod_closed) (use fs'carr in blast)
  \<comment> \<open>@{term f} divides @{term "poly_prod gs = poly_prod (f # fs')"}, so divides some @{term g} in
      @{term gs}; both monic irreducibles, hence @{term "f = g"}.\<close>
  have "poly_dvd f (poly_prod gs)"
    unfolding poly_dvd_def using Cons.prems(3) fs'prod by (metis poly_prod_Cons poly_mult_comm fc)
  then obtain g where g: "g \<in> set gs" and "poly_dvd f g"
    using poly_irreducible_prime_list[OF iff gscarr] by blast
  have ig: "poly_irreducible g" and mg: "poly_monic g" using gsc g by auto
  have feq: "f = g" using monic_irreducible_dvd_eq[OF iff ig mf mg \<open>poly_dvd f g\<close>] .
  \<comment> \<open>Cancel @{term f}: @{term "poly_prod fs' = poly_prod (remove1 g gs)"}.\<close>
  have gc: "g \<in> poly_carrier" using ig by (rule poly_irreducibleD_carrier)
  have rprod: "poly_prod (remove1 g gs) \<in> poly_carrier"
    by (meson gscarr notin_set_remove1 poly_prod_closed)
  have gnz: "g \<noteq> \<zero>\<^sub>P" using ig by (rule poly_irreducibleD_nonzero)
  have "g \<otimes>\<^sub>P poly_prod fs' = g \<otimes>\<^sub>P poly_prod (remove1 g gs)"
    using Cons.prems(3) feq g gscarr poly_prod_remove1 by auto
  then have "poly_prod fs' = poly_prod (remove1 g gs)"
    using poly_mult_left_cancel[OF gc gnz fs'prod rprod] by simp
  \<comment> \<open>Recurse on the remaining factors.\<close>
  moreover have "\<forall>g'\<in>set (remove1 g gs). poly_irreducible g' \<and> poly_monic g'"
    using gsc by (meson notin_set_remove1)
  ultimately show ?case
    using Cons.hyps[OF fs'c]
    by (simp add: feq g)
qed

end

end
