section \<open>Transfer of Solvability\<close>

theory Solvable_Transfer
  imports Derived_Series
begin

text \<open>
  Solvability transfers along the basic group constructions: it passes to homomorphic
  (in particular quotient) images, and to subgroups.  These are the load-bearing
  facts connecting a solvable group to its subquotients.
\<close>

context group_homomorphism
begin

text \<open>A homomorphism carries commutators to commutators.\<close>
lemma image_commutator_elt:
  assumes "a \<in> G" "b \<in> G"
  shows "\<eta> (source.commutator_elt a b) = target.commutator_elt (\<eta> a) (\<eta> b)"
proof -
  have "\<eta> (source.commutator_elt a b) = \<eta> a \<cdot>' \<eta> b \<cdot>' inverse' (\<eta> a) \<cdot>' inverse' (\<eta> b)"
    using assms by (simp add: source.commutator_elt_def commutes_with_composition 
        invertible_commutes_with_inverse)
  also have "\<dots> = target.commutator_elt (\<eta> a) (\<eta> b)"
    using assms by (simp add: target.commutator_elt_def)
  finally show ?thesis .
qed

text \<open>The image of a generated subgroup is contained in the subgroup generated by the image.\<close>
lemma image_generate_sub: "\<eta> ` source.generate S \<subseteq> target.generate (\<eta> ` (S \<inter> G))"
proof
  fix y assume "y \<in> \<eta> ` source.generate S"
  then obtain x where x: "x \<in> source.generate S" and yx: "y = \<eta> x" by auto
  from x have "\<eta> x \<in> target.generate (\<eta> ` (S \<inter> G))"
  proof induction
    case unit
    then show ?case using commutes_with_unit target.generate.unit by simp
  next
    case (incl x)
    then have "\<eta> x \<in> \<eta> ` (S \<inter> G) \<inter> G'" by auto
    then show ?case by (rule target.generate.incl)
  next
    case (comp x y)
    have xG: "x \<in> G" "y \<in> G" using comp.hyps source.generate_subset_carrier by auto
    have "\<eta> (x \<cdot> y) = \<eta> x \<cdot>' \<eta> y" using xG by (simp add: commutes_with_composition)
    then show ?case using comp.IH by (simp add: target.generate.comp)
  next
    case (inv x)
    have xG: "x \<in> G" using inv.hyps source.generate_subset_carrier by auto
    have "\<eta> (inverse x) = inverse' (\<eta> x)" using xG by (simp add: invertible_commutes_with_inverse)
    then show ?case using inv.IH by (simp add: target.generate.inv)
  qed
  then show "y \<in> target.generate (\<eta> ` (S \<inter> G))" using yx by simp
qed

text \<open>The reverse: the subgroup generated by the image is contained in the image of the
  generated subgroup.  (No surjectivity needed.)\<close>
lemma image_generate_super: "target.generate (\<eta> ` (S \<inter> G)) \<subseteq> \<eta> ` source.generate S"
proof
  fix y assume "y \<in> target.generate (\<eta> ` (S \<inter> G))"
  then show "y \<in> \<eta> ` source.generate S"
  proof induction
    case unit
    then show ?case using commutes_with_unit source.generate.unit by force
  next
    case (incl x)
    then show ?case using source.generate.incl by force
  next
    case (comp x y)
    then obtain a b where \<section>: "a \<in> source.generate S" "x = \<eta> a" "b \<in> source.generate S" "y = \<eta> b"  "a \<in> G" "b \<in> G" 
      using source.generate_subset_carrier by auto
    then have "a \<cdot> b \<in> source.generate S" using source.generate.comp by blast
    with \<section> show ?case by (metis commutes_with_composition image_eqI)
  next
    case (inv x)
    then obtain a where a: "a \<in> source.generate S" "x = \<eta> a" "a \<in> G" 
      using source.generate_subset_carrier by auto
    then show ?case
      by (metis source.generate.inv image_eqI invertible_commutes_with_inverse source.invertible)
  qed
qed

text \<open>Hence the image of a commutator subgroup is the commutator subgroup of the images.\<close>
lemma image_commutator_subgroup_sub:
  assumes "H \<subseteq> G" "K \<subseteq> G"
  shows "\<eta> ` source.commutator_subgroup H K \<subseteq> target.commutator_subgroup (\<eta> ` H) (\<eta> ` K)"
proof -
  have genset_sub: "{ target.commutator_elt h' k' | h' k'. h' \<in> \<eta> ` H \<and> k' \<in> \<eta> ` K } \<subseteq> G'"
    using assms by force
  have "\<eta> ` source.commutator_subgroup H K
          \<subseteq> target.generate (\<eta> ` (({ source.commutator_elt h k | h k. h \<in> H \<and> k \<in> K } \<inter> G) \<inter> G))"
    using image_generate_sub source.Gen_def source.commutator_subgroup_def by presburger
  also have "\<eta> ` (({ source.commutator_elt h k | h k. h \<in> H \<and> k \<in> K } \<inter> G) \<inter> G)
               \<subseteq> { target.commutator_elt h' k' | h' k'. h' \<in> \<eta> ` H \<and> k' \<in> \<eta> ` K }"
    using assms by (force simp: image_def image_commutator_elt)
  then have "target.generate (\<eta> ` (({ source.commutator_elt h k | h k. h \<in> H \<and> k \<in> K } \<inter> G) \<inter> G))
               \<subseteq> target.generate { target.commutator_elt h' k' | h' k'. h' \<in> \<eta> ` H \<and> k' \<in> \<eta> ` K }"
    by (rule target.generate_mono)
  also have "\<dots> = target.commutator_subgroup (\<eta> ` H) (\<eta> ` K)"
    using genset_sub by (simp add: target.commutator_subgroup_def target.Gen_def Int_absorb2)
  finally show ?thesis .
qed

lemma image_commutator_subgroup_super:
  assumes "H \<subseteq> G" "K \<subseteq> G"
  shows "target.commutator_subgroup (\<eta> ` H) (\<eta> ` K) \<subseteq> \<eta> ` source.commutator_subgroup H K"
proof -
  have seteq: "{ target.commutator_elt h' k' | h' k'. h' \<in> \<eta> ` H \<and> k' \<in> \<eta> ` K } \<inter> G'
                 \<subseteq> \<eta> ` ({ source.commutator_elt h k | h k. h \<in> H \<and> k \<in> K } \<inter> G)"
    using assms by (force simp: image_def image_commutator_elt)
  have "target.commutator_subgroup (\<eta> ` H) (\<eta> ` K)
         \<subseteq> target.generate (\<eta> ` ({ source.commutator_elt h k | h k. h \<in> H \<and> k \<in> K } \<inter> G))"
    by (simp add: seteq target.Gen_def target.commutator_subgroup_def target.generate_mono)
  also have "\<dots> \<subseteq> \<eta> ` source.commutator_subgroup H K"
    using image_generate_super  
    by (fastforce simp add: source.commutator_subgroup_def source.Gen_def)
  finally show ?thesis .
qed

lemma image_commutator_subgroup_eq:
  assumes "H \<subseteq> G" "K \<subseteq> G"
  shows "\<eta> ` source.commutator_subgroup H K = target.commutator_subgroup (\<eta> ` H) (\<eta> ` K)"
  by (meson assms image_commutator_subgroup_sub image_commutator_subgroup_super equalityI)

text \<open>For a surjective homomorphism, the derived series of the target is the image of
  the derived series of the source.\<close>
lemma image_derivedSeries:
  assumes "\<eta> ` G = G'"
  shows "\<eta> ` source.derivedSeries n = target.derivedSeries n"
  by (induction n) (auto simp: assms image_commutator_subgroup_eq source.derivedSeries_subset)

text \<open>A surjective homomorphic image of a solvable group is solvable.\<close>
lemma solvable_image:
  assumes "\<eta> ` G = G'" and "source.solvable"
  shows "target.solvable"
  using assms unfolding source.solvable_def target.solvable_def
  by (metis commutes_with_unit image_derivedSeries image_empty image_insert)

text \<open>Unconditionally (no surjectivity), the image of the source derived series is contained in the
  target derived series.\<close>
lemma image_derivedSeries_subset: "\<eta> ` source.derivedSeries n \<subseteq> target.derivedSeries n"
proof (induction n)
  case 0
  show ?case using map_closed by auto
next
  case (Suc n) then show ?case
    by (simp add: image_commutator_subgroup_eq source.derivedSeries_subset
        target.commutator_subgroup_mono)
qed

text \<open>\<^emph>\<open>A group admitting an injective homomorphism into a solvable group is solvable.\<close>  If the target
  is solvable, its derived series reaches @{term "{\<one>'}"} at some step @{term n}; the image of the
  source derived series is contained there (@{thm [source] image_derivedSeries_subset}), so
  @{term \<eta>} maps @{term "source.derivedSeries n"} to @{term "\<one>'"}, and injectivity (with
  @{term "\<eta> \<one> = \<one>'"}) forces it to be @{term "{\<one>}"}.\<close>
lemma solvable_of_injective:
  assumes inj: "inj_on \<eta> G" and solv: "target.solvable"
  shows "source.solvable"
proof -
  from solv obtain n where n: "target.derivedSeries n = {\<one>'}"
    unfolding target.solvable_def by blast
  \<comment> \<open>Every element of @{term "source.derivedSeries n"} maps to @{term "\<one>'"}.\<close>
  have mapsto: "\<eta> x = \<one>'" if x: "x \<in> source.derivedSeries n" for x
    by (metis image_derivedSeries_subset image_subset_iff n singletonD x)
  have "source.derivedSeries n \<subseteq> {\<one>}"
    using inj source.unit_closed source.derivedSeries_subset
    using injective_iff_kernel_unit mapsto by blast
  with source.derivedSeries_unit_closed show ?thesis unfolding source.solvable_def by blast
qed

end (* group_homomorphism *)

text \<open>A surjective homomorphic image of a solvable group is solvable (top level).\<close>
theorem (in group_epimorphism) solvable_image_epi:
  assumes "source.solvable"
  shows "target.solvable"
  using solvable_image surjective assms by simp


subsection \<open>Subgroups\<close>

text \<open>We work in the ambient @{locale Group} and refer to a subgroup's own group
  operations through the locale-qualified constants \<open>Group.commutator_elt H (\<cdot>) \<one>\<close>,
  \<open>Group.generate H (\<cdot>) \<one>\<close> and \<open>Group.derivedSeries H (\<cdot>) \<one>\<close>.  This
  bridge avoids the awkward parameter naming of the bare @{locale Subgroup} locale and
  is reusable for any subgroup.\<close>

context Group
begin

text \<open>The subgroup's derived series is contained in the ambient derived series.\<close>
lemma derivedSeries_subgroup_subset:
  assumes H: "Subgroup H G (\<cdot>) \<one>"
  shows "Group.derivedSeries H (\<cdot>) \<one> n \<subseteq> derivedSeries n"
proof -
  interpret S: Subgroup H G "(\<cdot>)" \<one> by (rule H)
  show ?thesis
  proof (induction n)
    case 0
    show ?case using S.subset by simp
  next
    case (Suc n) 
    have "Group.derivedSeries H (\<cdot>) \<one> (Suc n)
          \<subseteq> commutator_subgroup (S.sub.derivedSeries n) (S.sub.derivedSeries n)"
      using commutator_subgroup_subgroup_subset[OF H] S.sub.derivedSeries_subset by simp
    also have "\<dots> \<subseteq> derivedSeries (Suc n)" 
      using commutator_subgroup_mono[OF Suc.IH Suc.IH] by simp
    finally show ?case .
  qed
qed

text \<open>A subgroup of a solvable group is solvable.\<close>
theorem solvable_subgroup:
  assumes H: "Subgroup H G (\<cdot>) \<one>" and solv: solvable
  shows "Group.solvable H (\<cdot>) \<one>"
proof -
  interpret S: Subgroup H G "(\<cdot>)" \<one> by (rule H)
  show ?thesis
    using solv H S.sub.derivedSeries_unit_closed derivedSeries_subgroup_subset
    unfolding S.sub.solvable_def solvable_def by blast
qed

text \<open>\<^emph>\<open>Shift lemma.\<close>  Once the derived series has entered a subgroup @{term H} (at step @{term k}),
  the later terms are dominated by @{term H}'s own derived series: @{term "derivedSeries (k + i)"}
  is contained in @{text "H\<^bsup>(i)\<^esup>"}.  (Induction on @{term i}, using commutator monotonicity and that a
  commutator of subsets of @{term H} is computed inside @{term H}.)\<close>
lemma derivedSeries_shift_subgroup:
  assumes H: "Subgroup H G (\<cdot>) \<one>" and k: "derivedSeries k \<subseteq> H"
  shows "derivedSeries (k + i) \<subseteq> Group.derivedSeries H (\<cdot>) \<one> i"
proof -
  interpret S: Subgroup H G "(\<cdot>)" \<one> by (rule H)
  show ?thesis
  proof (induction i)
    case 0
    show ?case using k by simp
  next
    case (Suc i) then 
    have "derivedSeries (k + Suc i) \<subseteq> commutator_subgroup (S.sub.derivedSeries i) (S.sub.derivedSeries i)"
      using commutator_subgroup_mono[OF Suc.IH Suc.IH] by simp
    also have "\<dots> \<subseteq> S.sub.derivedSeries (Suc i)"
      using commutator_subgroup_subset_subgroup[OF H] S.sub.derivedSeries_subset by simp
    finally show ?case .
  qed
qed

end (* Group *)


subsection \<open>Solvability of an extension\<close>

text \<open>\<^emph>\<open>An extension of a solvable group by a solvable group is solvable.\<close>  For a surjective
  homomorphism \<open>\<eta>\<close>: if the kernel and the image \<open>G'\<close> are both solvable, so is \<open>G\<close>.  The derived
  series of \<open>G\<close> maps onto that of \<open>G'\<close> (\<open>image_derivedSeries\<close>), which reaches \<open>{\<one>'}\<close>; so
  \<open>source.derivedSeries k \<subseteq> Ker\<close>, and the kernel's own solvability then drives the remaining terms
  to \<open>{\<one>}\<close> via the shift lemma.\<close>
theorem (in group_epimorphism) solvable_extension:
  assumes solvKer: "Group.solvable Ker (\<cdot>) \<one>"
    and solvImg: "target.solvable"
  shows "source.solvable"
proof -
  \<comment> \<open>The derived series of @{term G} maps onto that of the image, which vanishes at some step.\<close>
  from solvImg obtain k where k: "target.derivedSeries k = {\<one>'}"
    unfolding target.solvable_def by blast
  \<comment> \<open>Everything in @{term "source.derivedSeries k"} maps to @{term "\<one>'"}, hence lies in the kernel.\<close>
  have subKer: "source.derivedSeries k \<subseteq> Ker"
    using image_derivedSeries[OF surjective] k source.derivedSeries_subset by blast
  \<comment> \<open>The kernel is a subgroup; its solvability drives the shifted series to @{term "{\<one>}"}.\<close>
  from solvKer obtain m where m: "Group.derivedSeries Ker (\<cdot>) \<one> m = {\<one>}"
    using kernel.sub.solvable_def by auto
  have "source.derivedSeries (k + m) \<subseteq> Group.derivedSeries Ker (\<cdot>) \<one> m"
    by (simp add: kernel.Subgroup_axioms source.derivedSeries_shift_subgroup subKer)
  then show ?thesis unfolding source.solvable_def
    using m source.derivedSeries_unit_closed by auto
qed

end
