section \<open>The lattice of subgroups\<close>

theory Subgroup_Lattice
  imports Group_Theory Order_Theory
begin

text \<open>The subgroups of a group \<open>G\<close>, ordered by inclusion, form a complete lattice: the infimum of a
  family of subgroups is their intersection (taken together with \<open>G\<close> itself, so the empty family has
  infimum \<open>G\<close>), and the supremum is the subgroup generated by their union.  This is the first concrete
  consumer of the abstract order theory of \<open>Order_Theory\<close>.\<close>

context Group
begin

subsection \<open>Intersections of subgroups\<close>

text \<open>The intersection of a nonempty family of subgroups is a subgroup.\<close>
lemma subgroup_Inter:
  assumes ne: "\<A> \<noteq> {}" and sub: "\<And>H. H \<in> \<A> \<Longrightarrow> Subgroup H G (\<cdot>) \<one>"
  shows "Subgroup (\<Inter> \<A>) G (\<cdot>) \<one>"
proof -
  obtain H0 where H0: "H0 \<in> \<A>" using ne by blast
  interpret H0: Subgroup H0 G "(\<cdot>)" \<one> by (rule sub[OF H0])
  show ?thesis
  proof (rule subgroupI)
    show "\<Inter> \<A> \<subseteq> G" using H0 H0.subset by blast
    show "\<one> \<in> \<Inter> \<A>"
      using Subgroup_def Submonoid.sub_unit_closed sub by fastforce
  next
    fix g h assume g: "g \<in> \<Inter> \<A>" and h: "h \<in> \<Inter> \<A>"
    show "g \<cdot> h \<in> \<Inter> \<A>"
      using Subgroup_def Submonoid.sub_composition_closed g h sub by fastforce
  next
    fix g assume g: "g \<in> \<Inter> \<A>"
    then show "invertible g" using H0.sub H0 by blast
    show "inverse g \<in> \<Inter> \<A>"
      using H0 H0.sub g invertible sub by (meson Inter_iff Subgroup.subgroup_inverse_iff)
  qed
qed


subsection \<open>The complete lattice of subgroups\<close>

text \<open>Carrier: the set of all subgroups of \<open>G\<close>; order: inclusion.\<close>
definition subgroups :: "'a set set"
  where "subgroups = {H. Subgroup H G (\<cdot>) \<one>}"

lemma subgroups_iff [simp]: "H \<in> subgroups \<longleftrightarrow> Subgroup H G (\<cdot>) \<one>"
  by (simp add: subgroups_def)

text \<open>Inclusion is a partial order on the subgroups.\<close>
interpretation subgroup_order: Partial_Order subgroups "(\<subseteq>)"
  by unfold_locales auto

text \<open>Every family of subgroups has an infimum (its intersection with \<open>G\<close>) and a supremum (the
  subgroup generated by its union), so the subgroups form a complete lattice.\<close>
interpretation subgroup_lattice: Complete_Lattice subgroups "(\<subseteq>)"
proof (unfold_locales)
  fix \<A> :: "'a set set" assume \<A>: "\<A> \<subseteq> subgroups"
  \<comment> \<open>Supremum: the subgroup generated by the union.\<close>
  have s_sub: "Subgroup \<langle>\<Union>\<A>\<rangle> G (\<cdot>) \<one>" by (rule Gen_is_subgroup)
  have "subgroup_order.is_sup \<langle>\<Union>\<A>\<rangle> \<A>"
  proof (intro subgroup_order.upper_boundI subgroup_order.is_supI)
    show "\<langle>\<Union>\<A>\<rangle> \<in> subgroups" using s_sub by simp
    fix H assume H: "H \<in> \<A>"
    then interpret H: Subgroup H G "(\<cdot>)" \<one> using \<A> by auto
    show "H \<subseteq> \<langle>\<Union>\<A>\<rangle>" using Gen_incl H H.subset by blast
  next
    fix A assume "subgroup_order.upper_bound A \<A>"
    then have xsub: "Subgroup A G (\<cdot>) \<one>" and dom: "\<And>H. H \<in> \<A> \<Longrightarrow> H \<subseteq> A"
      by (auto dest: subgroup_order.upper_boundD simp: subgroup_order.upper_bound_def)
    then show "\<langle>\<Union>\<A>\<rangle> \<subseteq> A" using xsub by (intro Gen_minimal) auto
  qed
  then show "\<exists>s. subgroup_order.is_sup s \<A>" ..
next
  fix \<A> :: "'a set set" assume \<A>: "\<A> \<subseteq> subgroups"
  \<comment> \<open>Infimum: the intersection of \<open>\<A>\<close> together with \<open>G\<close> (so the empty family gives \<open>G\<close>).\<close>
  let ?i = "\<Inter> (insert G \<A>)"
  have all_sub: "\<And>H. H \<in> insert G \<A> \<Longrightarrow> Subgroup H G (\<cdot>) \<one>"
    using \<A> group_self_subgroup by auto
  have i_sub: "Subgroup ?i G (\<cdot>) \<one>" by (rule subgroup_Inter) (use all_sub in auto)
  have "subgroup_order.is_inf ?i \<A>"
  proof (intro subgroup_order.is_infI)
    show "subgroup_order.lower_bound ?i \<A>"
      using i_sub subgroup_order.lower_boundI by fastforce
  next
    fix x assume "subgroup_order.lower_bound x \<A>"
    then have xsub: "Subgroup x G (\<cdot>) \<one>" and dom: "\<And>H. H \<in> \<A> \<Longrightarrow> x \<subseteq> H"
      by (auto dest: subgroup_order.lower_boundD simp: subgroup_order.lower_bound_def)
    interpret x: Subgroup x G "(\<cdot>)" \<one> by (rule xsub)
    show "x \<subseteq> ?i" using dom x.subset by blast
  qed
  then show "\<exists>i. subgroup_order.is_inf i \<A>" ..
qed

text \<open>The lattice operations are the familiar ones: meet is intersection, join is the subgroup
  generated by the union, top is \<open>G\<close> and bottom is the trivial subgroup \<open>{\<one>}\<close>.\<close>

lemma subgroup_top: "subgroup_lattice.top = G"
proof -
  have "subgroup_order.is_sup G subgroups"
  proof (intro subgroup_order.upper_boundI subgroup_order.is_supI)
    show "G \<in> subgroups" by (simp add: group_self_subgroup)
    fix H assume "H \<in> subgroups"
    then show "H \<subseteq> G"
      using Gen_subgroup_eq Gen_subset_carrier by fastforce
  next
    fix A assume "subgroup_order.upper_bound A subgroups"
    then show "G \<subseteq> A" by (auto simp: subgroup_order.upper_bound_def group_self_subgroup)
  qed
  then show ?thesis
    unfolding subgroup_lattice.top_def
    using subgroup_order.is_sup_unique subgroup_lattice.is_sup_Sup[OF subset_refl] by blast
qed

end

end
