section \<open>Generating the Symmetric Group\<close>

theory Symmetric_Generation
  imports Symmetric_Group
begin

text \<open>@{term "Sn n"} is finite: it is a set of permutations of a finite set.  Stated here at the top
  level --- it was previously inside the anonymous context below that fixes a @{term p}-cycle
  @{term g}, so the exported fact carried that context's four irrelevant assumptions.\<close>
lemma finite_Sn: "finite (Sn n)"
  unfolding Sn_def using finite_permutations[of "{0..<n}"] by simp


text \<open>
  The symmetric group @{term "Sn n"} is generated by a single transposition
  together with a full @{term n}-cycle, and (for prime @{term p}) by \<^emph>\<open>any\<close> transposition
  together with \<^emph>\<open>any\<close> @{term p}-cycle.  These generation results are the combinatorial
  ingredient that, combined with \<open>Sn_not_solvable\<close>, shows that the Galois group
  of a quintic with exactly two non-real roots is the whole of @{term "Sn 5"}.\<close>

subsection \<open>A general lemma on generated subgroups\<close>

text \<open>Powers of an element of a generated subgroup stay inside it.\<close>
lemma (in Group) generate_funpow:
  assumes "g \<in> generate S"
  shows "power g k \<in> generate S"
  by (induction k) (auto simp add: assms generate.intros)

subsection \<open>Conjugation is an automorphism of the generated subgroup\<close>

text \<open>Conjugation by a group element @{term g} fixes the unit and commutes with generation:
  the image of @{term "generate S"} under @{term "conjugation g"} is the subgroup generated by
  the image of @{term S}.  This lets a generation result be transported along conjugacy, which
  is what upgrades the standard-cycle generation theorem to an \<^emph>\<open>arbitrary\<close> cycle.\<close>

lemma (in Group) conjugation_one: "g \<in> G \<Longrightarrow> conjugation g \<one> = \<one>"
  by (simp add: conjugation_def invertible_right_inverse)

lemma (in Group) conjugation_inv_cancel:
  assumes g: "g \<in> G" and x: "x \<in> G"
  shows "conjugation (inverse g) (conjugation g x) = x"
  using g x by (simp add: conjugation_def associative invertible_left_inverse2 invertible_right_inverse2)

lemma (in Group) conjugation_generate_sub:
  assumes g: "g \<in> G"
  shows "conjugation g ` generate S \<subseteq> generate (conjugation g ` (S \<inter> G))"
proof
  fix y assume "y \<in> conjugation g ` generate S"
  then obtain x where x: "x \<in> generate S" and yx: "y = conjugation g x" by auto
  from x have "conjugation g x \<in> generate (conjugation g ` (S \<inter> G))"
  proof induction
    case unit
    then show ?case using conjugation_one[OF g] generate.unit by simp
  next
    case (incl x) then show ?case
      by (simp add: generate.incl conjugation_closed g)
  next
    case (comp x y) 
    have xG: "x \<in> G" "y \<in> G" using comp.hyps generate_subset_carrier by auto
    then show ?case
      by (metis comp.IH conjugation_hom g generate.comp)
  next
    case (inv x)
    then show ?case
      by (metis IntD2 conjugation_inverse g generate.inv generate_subset_carrier inf.orderE)
  qed
  then show "y \<in> generate (conjugation g ` (S \<inter> G))" using yx by simp
qed

lemma (in Group) conjugation_generate_eq:
  assumes g: "g \<in> G"
  shows "conjugation g ` generate S = generate (conjugation g ` (S \<inter> G))"
proof
  show "conjugation g ` generate S \<subseteq> generate (conjugation g ` (S \<inter> G))"
    by (rule conjugation_generate_sub[OF g])
next
  have ginv: "inverse g \<in> G" using g by blast
  let ?T = "conjugation g ` (S \<inter> G)"
  have sub2: "conjugation (inverse g) ` generate ?T \<subseteq> generate (conjugation (inverse g) ` (?T \<inter> G))"
    by (rule conjugation_generate_sub[OF ginv])
  have "conjugation (inverse g) ` (?T \<inter> G) \<subseteq> S \<inter> G"
    by (auto simp: conjugation_inv_cancel g)
  then have step: "generate (conjugation (inverse g) ` (?T \<inter> G)) \<subseteq> generate (S \<inter> G)"
    by (rule generate_mono)
  show "generate ?T \<subseteq> conjugation g ` generate S"
  proof
    fix y assume y: "y \<in> generate ?T"
    have yG: "y \<in> G" using y generate_subset_carrier by blast
    have "conjugation g (conjugation (inverse g) y) \<in> conjugation g ` generate (S \<inter> G)" 
      using sub2 y step by auto
    moreover have "conjugation g (conjugation (inverse g) y) = y"
      using ginv yG conjugation_inv_cancel[OF ginv yG] g by simp
    ultimately show "y \<in> conjugation g ` generate S"
      using generate_mono[of "S \<inter> G" S] by auto
  qed
qed

subsection \<open>Transpositions generate the symmetric group\<close>

text \<open>The set of transpositions of points of @{term "{0..<n}"}.\<close>
definition transpositions :: "nat \<Rightarrow> (nat \<Rightarrow> nat) set"
  where "transpositions n = {Transposition.transpose a b | a b. a \<in> {0..<n} \<and> b \<in> {0..<n}}"

lemma transpositions_subset_Sn: "transpositions n \<subseteq> Sn n"
  by (auto simp: transpositions_def Sn_def permutes_swap_id)

subsection \<open>The standard \<open>n\<close>-cycle\<close>

text \<open>The cyclic shift sending \<open>i\<close> to \<open>Suc i mod n\<close> on @{term "{0..<n}"}, fixing everything
  outside.  We work with this explicit form rather than @{const cycle_of_list} because its
  powers have the transparent closed form @{term "(i + k) mod n"}.\<close>

definition ncycle :: "nat \<Rightarrow> nat \<Rightarrow> nat"
  where "ncycle n i = (if i < n then Suc i mod n else i)"

lemma ncycle_lt: "i < n \<Longrightarrow> ncycle n i < n" by (auto simp: ncycle_def)

lemma ncycle_inv_right: "i < n \<Longrightarrow> ncycle n ((i + (n-1)) mod n) = i"
  by (simp add: mod_if ncycle_def)

lemma ncycle_inv_left: "i < n \<Longrightarrow> (ncycle n i + (n-1)) mod n = i"
  using mod_if ncycle_def by force

lemma ncycle_permutes: "ncycle n permutes {0..<n}"
proof (rule bij_imp_permutes)
  show "bij_betw (ncycle n) {0..<n} {0..<n}"
  proof (rule bij_betw_byWitness)
    show "\<forall>i\<in>{0..<n}. ncycle n (if i < n then (i + (n-1)) mod n else i) = i"
      using ncycle_inv_right by auto
  qed (use ncycle_lt ncycle_inv_left in auto)
qed (auto simp: ncycle_def)

lemma ncycle_in_Sn: "ncycle n \<in> Sn n" by (simp add: Sn_def ncycle_permutes)

lemma ncycle_bij: "bij (ncycle n)"
  by (rule permutes_bij[OF ncycle_permutes])

text \<open>The closed form for the iterates of the @{term n}-cycle.\<close>
lemma ncycle_funpow: "i < n \<Longrightarrow> (ncycle n ^^ k) i = (i + k) mod n"
  by (induction k; simp add: mod_Suc_eq ncycle_def)


context
  fixes n::nat
begin

interpretation S: Group "Sn n" "(\<circ>)" id
  by (rule Group_Sn)

text \<open>Every permutation of @{term "{0..<n}"} is a product of transpositions, so the
  transpositions generate @{term "Sn n"}.  This follows directly from the tailored induction
  rule @{thm [source] permutes_induct}.\<close>
lemma Sn_generated_by_transpositions:
  "Group.generate (Sn n) (\<circ>) id (transpositions n) = Sn n"
proof
  show "S.generate (transpositions n) \<subseteq> Sn n"
    using S.generate_subset_carrier by simp
next
  show "Sn n \<subseteq> S.generate (transpositions n)"
  proof
    fix p assume "p \<in> Sn n"
    then have "p permutes {0..<n}" "finite {0..<n}" by (simp_all add: Sn_def)
    then show "p \<in> S.generate (transpositions n)"
    proof (induction p rule: permutes_induct)
      case id
      show ?case
        using S.generate.unit by blast
    next
      case (swap a b p) 
      then obtain "Transposition.transpose a b \<in> transpositions n" 
                  "Transposition.transpose a b \<in> Sn n"
        using transpositions_def transpositions_subset_Sn by fastforce
      then show ?case
        by (metis Int_iff S.generate.comp S.generate.incl swap.IH)
    qed
  qed
qed


subsection \<open>Conjugating a transposition\<close>

text \<open>Conjugating a transposition by a bijection transposes the images of the two points.\<close>
lemma transpose_conjug:
  assumes "bij q"
  shows "q \<circ> Transposition.transpose a b \<circ> inv q = Transposition.transpose (q a) (q b)"
proof -
  have "Transposition.transpose (q a) (q b) \<circ> q  = q \<circ> Transposition.transpose a b"
    using assms by (simp add: bij_def transpose_comp_eq)
  then show ?thesis
    by (metis assms bij_betw_inv_into bij_is_inj o_inv_o_cancel)
qed

subsection \<open>The symmetric group is generated by a transposition and a cycle\<close>

text \<open>The group power in @{term "Sn n"} (composition) is just function iteration.\<close>
lemma Sn_power_funpow: "Monoid.power (\<circ>) id (g :: nat \<Rightarrow> nat) k = g ^^ k"
  by (metis S.power_def comp_funpow comp_id)

text \<open>In @{term "Sn n"} the group inverse is the functional inverse.\<close>
lemma Sn_inverse_eq:
  assumes "p \<in> Sn n"
  shows "Monoid.inverse (Sn n) (\<circ>) id p = inv p"
  using S.invertible_left_inverse2 Sn_iff assms permutes_inv permutes_inv_o(1) by fastforce

lemma t01_in_Sn: "1 < n \<Longrightarrow> Transposition.transpose 0 1 \<in> Sn n"
  by (simp add: Sn_def permutes_swap_id)

text \<open>Conjugating @{term "transpose 0 1"} by the @{term k}-th power of the @{term n}-cycle
  yields the adjacent transposition @{term "transpose (k mod n) (Suc k mod n)"}.\<close>
lemma adjacent_transpose_conjug:
  assumes "k < n" "1 < n"
  shows "(ncycle n ^^ k) \<circ> Transposition.transpose 0 1 \<circ> inv (ncycle n ^^ k)
         = Transposition.transpose (k mod n) (Suc k mod n)"
proof -
  have "(ncycle n ^^ k) \<circ> Transposition.transpose 0 1 \<circ> inv (ncycle n ^^ k)
        = Transposition.transpose ((ncycle n ^^ k) 0) ((ncycle n ^^ k) 1)"
    using ncycle_bij bij_fn transpose_conjug by metis
  then show ?thesis
    by (metis One_nat_def Suc_lessD add_0 assms(2) ncycle_funpow plus_1_eq_Suc) 
qed

text \<open>Hence each adjacent transposition lies in the subgroup generated by
  @{term "transpose 0 1"} and the @{term n}-cycle.\<close>
lemma adjacent_in_generate:
  assumes "k < n" "1 < n"
  defines "S \<equiv> {Transposition.transpose 0 1, ncycle n}"
  shows "Transposition.transpose (k mod n) (Suc k mod n) \<in> Group.generate (Sn n) (\<circ>) id S"
proof -
  have t01: "Transposition.transpose 0 1 \<in> S.generate S"
    using Group.generate_incl S.Group_axioms S_def assms(2) t01_in_Sn by fastforce
  have nc: "ncycle n \<in> S.generate S"
    using ncycle_in_Sn by (intro S.generate.incl) (simp add: S_def)
  have powk: "S.power (ncycle n) k \<in> S.generate S" using nc by (rule S.generate_funpow)
  have powkSn: "S.power (ncycle n) k \<in> Sn n" using powk S.generate_subset_carrier by blast
  have conj: "S.power (ncycle n) k \<circ> Transposition.transpose 0 1 \<circ> S.inverse (S.power (ncycle n) k) \<in> S.generate S"
    using powk t01 by (meson S.generate.simps)
  have "S.inverse (S.power (ncycle n) k) = inv (ncycle n ^^ k)"
    using Sn_power_funpow powkSn Sn_inverse_eq by simp
  with conj Sn_power_funpow adjacent_transpose_conjug[OF assms(1,2)]
  show ?thesis by simp
qed

text \<open>Building from adjacent transpositions, every transposition \<open>transpose i j\<close> with
  \<open>i < j < n\<close> lies in the subgroup.  The recursion uses
  @{thm [source] transpose_comp_triple}.\<close>
lemma transpose_extend:
  assumes "a \<noteq> b" "b \<noteq> c" "a \<noteq> c"
  shows "Transposition.transpose a c = Transposition.transpose a b \<circ> Transposition.transpose b c \<circ> Transposition.transpose a b"
  using assms by (simp add: transpose_comp_triple)

lemma all_transpose_in_generate_aux:
  assumes "1 < n"
  defines "S \<equiv> {Transposition.transpose 0 1, ncycle n}"
  shows "\<forall>i. i + Suc d < n \<longrightarrow> Transposition.transpose i (i + Suc d) \<in> Group.generate (Sn n) (\<circ>) id S"
proof (induction d)
  case 0
  show ?case
    unfolding S_def
    using adjacent_in_generate[OF _ assms(1)]
    by (metis One_nat_def Suc_eq_plus1 Suc_lessD mod_less)
next
  case (Suc d)
  show ?case
  proof (intro allI impI)
    fix i assume i: "i + Suc (Suc d) < n"
    let ?b = "i + Suc d" and ?c = "i + Suc (Suc d)"
    have \<section>: "i + Suc d < n" using i by simp
    then have ib: "Transposition.transpose i ?b \<in> S.generate S"
      using Suc.IH unfolding S_def by blast
    have "?b mod n = ?b" "Suc ?b mod n = Suc ?b" using i by auto
    then have \<section>: "Transposition.transpose ?b (Suc ?b) \<in> S.generate S"
      using adjacent_in_generate[OF _ assms(1)] unfolding S_def by (metis \<section>)
    have "Transposition.transpose i ?c
            = Transposition.transpose i ?b \<circ> Transposition.transpose ?b ?c \<circ> Transposition.transpose i ?b"
      by (rule transpose_extend) auto
    with ib \<section> show "Transposition.transpose i ?c \<in> S.generate S" 
      by (auto intro: S.generate.comp simp: o_assoc)
  qed
qed

lemma transpose_in_generate:
  assumes "a < n" "b < n" "1 < n"
  shows "Transposition.transpose a b \<in> Group.generate (Sn n) (\<circ>) id {Transposition.transpose 0 1, ncycle n}"
proof -
  consider (eq) "a = b" | (lt) "a < b" | (gt) "b < a" using assms by linarith
  then show ?thesis
    using all_transpose_in_generate_aux
    by (metis S.generate.simps add_Suc_right assms less_iff_Suc_add transpose_commute
        transpose_eq_id_iff)
qed

text \<open>The canonical generation theorem: a transposition of two adjacent points together with
  the standard @{term n}-cycle generate the whole symmetric group.\<close>
theorem Sn_generated_canonical:
  assumes "1 < n"
  shows "Group.generate (Sn n) (\<circ>) id {Transposition.transpose 0 1, ncycle n} = Sn n"
proof
  show "S.generate {Transposition.transpose 0 1, ncycle n} \<subseteq> Sn n"
    using S.generate_subset_carrier by simp
next
  have sub: "S.generate (transpositions n) \<subseteq> S.generate {Transposition.transpose 0 1, ncycle n}"
    using transpose_in_generate[OF _ _ assms] 
      by (intro S.generate_minimal S.generate_is_subgroup) (auto simp: transpositions_def)
  then show "Sn n \<subseteq> S.generate {Transposition.transpose 0 1, ncycle n}"
    using Sn_generated_by_transpositions by simp
qed


subsection \<open>A transposition and a \<open>p\<close>-cycle generate \<open>S\<^sub>p\<close> for prime \<open>p\<close>\<close>

text \<open>For prime @{term p}, the standard @{term p}-cycle together with \<^emph>\<open>any\<close> transposition
  generates @{term "Sn p"}.  The primality is essential: it guarantees that the conjugates of
  the transposition by powers of the cycle have supports forming a single orbit covering all
  points, from which every transposition can be recovered.\<close>

text \<open>Conjugating @{term "transpose a b"} by the @{term k}-th power of the @{term n}-cycle
  shifts both points by @{term k} (modulo @{term n}); the result stays in the subgroup
  generated by the cycle and the transposition.\<close>
lemma ncycle_conj_transpose_in_generate:
  assumes "a < n" "b < n" "1 < n"
  defines "S \<equiv> {ncycle n, Transposition.transpose a b}"
  shows "Transposition.transpose ((a + k) mod n) ((b + k) mod n) \<in> Group.generate (Sn n) (\<circ>) id S"
proof -
  have tabSn: "Transposition.transpose a b \<in> Sn n"
    using assms by (auto simp: Sn_def permutes_swap_id)
  have tab: "Transposition.transpose a b \<in> S.generate S"
    using tabSn by (intro S.generate.incl) (simp add: S_def)
  have nc: "ncycle n \<in> S.generate S"
    using ncycle_in_Sn by (intro S.generate.incl) (simp add: S_def)
  have powk: "S.power (ncycle n) k \<in> S.generate S" using nc by (rule S.generate_funpow)
  have powkSn: "S.power (ncycle n) k \<in> Sn n" using powk S.generate_subset_carrier by blast
  have invk: "S.inverse (S.power (ncycle n) k) \<in> S.generate S"
    using powk by (rule S.generate.inv)
  have conj: "S.power (ncycle n) k \<circ> Transposition.transpose a b \<circ> S.inverse (S.power (ncycle n) k) \<in> S.generate S"
    using powk tab invk by (auto intro: S.generate.comp simp: o_assoc)
  have inveq: "S.inverse (S.power (ncycle n) k) = inv (ncycle n ^^ k)"
    using Sn_power_funpow powkSn Sn_inverse_eq by simp
  have "ncycle n ^^ k \<circ> Transposition.transpose a b \<circ> inv (ncycle n ^^ k)
        = Transposition.transpose ((ncycle n ^^ k) a) ((ncycle n ^^ k) b)"
    using ncycle_bij by (intro transpose_conjug bij_fn)
  with ncycle_funpow [of _ n k] assms
  have "ncycle n ^^ k \<circ> Transposition.transpose a b \<circ> inv (ncycle n ^^ k)
        = Transposition.transpose ((a + k) mod n) ((b + k) mod n)"   by presburger
  with conj Sn_power_funpow inveq show ?thesis by simp
qed

text \<open>If a subgroup contains two transpositions sharing a point, it contains their ``sum''.\<close>
lemma transpose_chain:
  assumes H: "Subgroup H (Sn n) (\<circ>) id"
    and "Transposition.transpose x y \<in> H"
    and "Transposition.transpose y z \<in> H"
    and "x \<noteq> z" "y \<noteq> z"
  shows "Transposition.transpose x z \<in> H"
proof -
  interpret H: Subgroup H "Sn n" "(\<circ>)" id by (rule H)
  show ?thesis
    using assms by (metis H.sub_composition_closed transpose_comp_triple)
qed

end (* n::nat *)

context
  fixes p::nat
  assumes p: "prime p"

begin

interpretation G: Group "Sn p" "(\<circ>)" id 
  by (rule Group_Sn)

text \<open>Number-theoretic facts about the stride @{term d} (the gap of the transposition).\<close>
lemma coprime_prime_stride:
  assumes "0 < d" "d < p"
  shows "coprime p d"
  by (simp add: assms nat_dvd_not_less p prime_imp_coprime)

lemma kd_mod_zero_iff:
  assumes "0 < d" "d < p"
  shows "(k * d) mod p = 0 \<longleftrightarrow> p dvd k"
  by (simp add: coprime_dvd_mult_left_iff coprime_prime_stride assms mod_eq_0_iff_dvd)

lemma stride_endpoints_distinct:
  assumes d1: "0 < d" and d2: "d < p"
  shows "(k * d) mod p \<noteq> (Suc k * d) mod p"
proof
  assume eq: "(k * d) mod p = (Suc k * d) mod p"
  then have "(k * d) mod p = (k * d + d) mod p" by (simp add: algebra_simps)
  then have "p dvd ((k * d + d) - k * d)" by (metis mod_eq_dvd_iff_nat le_add1)
  then show False using d1 d2 by (simp add: nat_dvd_not_less)
qed

text \<open>Each ``stride edge'' \<open>transpose (k * d mod p) (Suc k * d mod p)\<close> lies in the subgroup
  generated by the cycle and @{term "transpose 0 d"}.\<close>
lemma stride_edge:
  assumes d1: "0 < d" and d2: "d < p"
  defines "S \<equiv> {ncycle p, Transposition.transpose 0 d}"
  shows "Transposition.transpose ((k * d) mod p) ((Suc k * d) mod p) \<in> Group.generate (Sn p) (\<circ>) id S"
    using S_def Symmetric_Generation.ncycle_conj_transpose_in_generate d2
    by (metis add_0 mult_Suc p prime_gt_0_nat prime_nat_iff)

text \<open>Chaining the stride edges, every \<open>transpose 0 (k * d mod p)\<close> (for \<open>k\<close> not a
  multiple of @{term p}) lies in the subgroup.\<close>
lemma stride_walk:
  fixes d :: nat
  assumes d1: "0 < d" and d2: "d < p"
  defines "S \<equiv> {ncycle p, Transposition.transpose 0 d}"
  shows "\<not> p dvd k \<Longrightarrow> Transposition.transpose 0 ((k * d) mod p) \<in> Group.generate (Sn p) (\<circ>) id S"
proof (induction k)
  case 0
  then show ?case by simp
next
  case (Suc k)
  have edge: "Transposition.transpose ((k * d) mod p) ((Suc k * d) mod p) \<in> G.generate S"
    using stride_edge[OF d1 d2] unfolding S_def by blast
  have suc_ne0: "(Suc k * d) mod p \<noteq> 0"
    using Suc.prems d1 d2 kd_mod_zero_iff by blast
  show ?case
  proof (cases "p dvd k")
    case True
    then have z: "(k * d) mod p = 0" using kd_mod_zero_iff[OF d1 d2] by simp
    then show ?thesis using edge unfolding z S_def
      by meson
  next
    case False
    have ih: "Transposition.transpose 0 ((k * d) mod p) \<in> G.generate S"
      using Suc.IH[OF False] unfolding S_def by blast
    have kne0: "(k * d) mod p \<noteq> 0"
      using False d1 d2 kd_mod_zero_iff by blast
    have ne: "(k * d) mod p \<noteq> (Suc k * d) mod p"
      using d1 d2 stride_endpoints_distinct by blast
    show ?thesis 
      using transpose_chain[OF G.generate_is_subgroup ih edge] kne0 suc_ne0 ne
      unfolding S_def by argo
  qed
qed

lemma pymod: "(p * y + 1) mod p = (1::nat) mod p"
  by (metis mod_mult_self3 mult.commute)

text \<open>Since @{term d} is coprime to the prime @{term p}, some multiple of @{term d} is
  congruent to @{term 1}, so @{term "transpose 0 1"} is reached.\<close>
lemma stride_reaches_one:
  fixes d :: nat
  assumes d1: "0 < d" and d2: "d < p"
  shows "\<exists>k. (k * d) mod p = 1 \<and> \<not> p dvd k"
proof -
  have p1: "1 < p" using p by (simp add: prime_nat_iff)
  have cop: "coprime d p" using coprime_prime_stride[OF d1 d2] by (simp add: coprime_commute)
  obtain x y where xy: "d * x = p * y + 1" using coprime_bezout_strong[OF cop] p1 by auto
  have one: "(x * d) mod p = 1"
    by (metis mod_less mult.commute p1 pymod xy)
  with one show ?thesis by auto
qed

lemma t01_in_stride_generate:
  assumes "0 < d" "d < p"
  shows "Transposition.transpose 0 1 \<in> Group.generate (Sn p) (\<circ>) id {ncycle p, Transposition.transpose 0 d}"
  by (metis assms stride_reaches_one stride_walk)

text \<open>The cycle and a stride-@{term d} transposition generate @{term "Sn p"}.\<close>
theorem Sn_generated_cycle_transpose_0d:
  fixes d :: nat
  assumes d1: "0 < d" and d2: "d < p"
  shows "Group.generate (Sn p) (\<circ>) id {ncycle p, Transposition.transpose 0 d} = Sn p"
proof
  have p1: "1 < p" using p by (simp add: prime_nat_iff)
  have nc: "ncycle p \<in> G.generate {ncycle p, Transposition.transpose 0 d}"
    using ncycle_in_Sn by (intro G.generate.incl) simp
  have sub: "G.generate {Transposition.transpose 0 1, ncycle p} \<subseteq> G.generate {ncycle p, Transposition.transpose 0 d}"
    using t01_in_stride_generate[OF d1 d2] nc 
    by (intro G.generate_minimal G.generate_is_subgroup) auto
  then show "Sn p \<subseteq> G.generate {ncycle p, Transposition.transpose 0 d}"
    using Sn_generated_canonical[OF p1] by simp
qed (use G.generate_subset_carrier in simp)

lemma sum_pa_bounds:
  fixes a b :: nat
  assumes a: "a < p" and b: "b < p" and ab: "a \<noteq> b"
  shows "0 < (b + (p - a)) mod p"
proof (rule ccontr)
  have lo: "0 < b + (p - a)" using a by simp
  have hi: "b + (p - a) < 2 * p" using a b by simp
  have ne: "b + (p - a) \<noteq> p" using a b ab by simp
  assume "\<not> 0 < (b + (p - a)) mod p"
  then obtain k where "b + (p - a) = p * k" by (auto simp: dvd_def)
  then show False
    using lo hi ne by auto
qed

text \<open>The main result of this section: for prime @{term p}, the standard @{term p}-cycle and
  \<^emph>\<open>any\<close> transposition generate @{term "Sn p"}.\<close>
theorem Sn_generated_ncycle_transpose:
  fixes a b :: nat
  assumes a: "a < p" and b: "b < p" and ab: "a \<noteq> b"
  shows "Group.generate (Sn p) (\<circ>) id {ncycle p, Transposition.transpose a b} = Sn p"
proof
  have p1: "1 < p" using p by (simp add: prime_nat_iff)
  define d where "d = (b + (p - a)) mod p"
  have d1: "0 < d" unfolding d_def using a b ab by (rule sum_pa_bounds)
  have d2: "d < p" unfolding d_def using p1 by simp
  \<comment> \<open>Conjugating @{term "transpose a b"} by @{term "ncycle p ^^ (p - a)"} maps @{term a} to
    @{term 0}, exhibiting @{term "transpose 0 d"} inside the subgroup.\<close>
  have "Transposition.transpose ((a + (p - a)) mod p) ((b + (p - a)) mod p)
            \<in> G.generate {ncycle p, Transposition.transpose a b}"
    using ncycle_conj_transpose_in_generate[OF a b p1, of "p - a"] by blast
  then have t0d: "Transposition.transpose 0 d \<in> G.generate {ncycle p, Transposition.transpose a b}"
    using a d_def by auto
  have nc: "ncycle p \<in> G.generate {ncycle p, Transposition.transpose a b}"
    using ncycle_in_Sn by (intro G.generate.incl) simp
  have sub: "G.generate {ncycle p, Transposition.transpose 0 d} \<subseteq> G.generate {ncycle p, Transposition.transpose a b}"
    using t0d nc by (intro G.generate_minimal G.generate_is_subgroup) auto
  then show "Sn p \<subseteq> G.generate {ncycle p, Transposition.transpose a b}"
    using Sn_generated_cycle_transpose_0d[OF d1 d2] by simp
qed (use G.generate_subset_carrier in simp)


subsection \<open>An arbitrary cycle and transposition generate \<open>S\<^sub>p\<close>\<close>

text \<open>In @{term "Sn n"} the group conjugation specialises to the familiar
  @{term "g \<circ> x \<circ> inv g"}.\<close>
lemma Sn_conjugation_eq:
  assumes g: "g \<in> Sn n" and x: "x \<in> Sn n"
  shows "Group.conjugation (Sn n) (\<circ>) id g x = g \<circ> x \<circ> inv g"
  by (simp add: Group.conjugation_def Group_Sn Sn_inverse_eq g x)

text \<open>Transporting @{thm [source] Sn_generated_ncycle_transpose} along conjugacy: for prime
  @{term p}, \<^emph>\<open>any\<close> conjugate @{term "q \<circ> ncycle p \<circ> inv q"} of the standard @{term p}-cycle,
  together with the conjugate @{term "q \<circ> transpose a b \<circ> inv q"} of a transposition, generates
  @{term "Sn p"}.\<close>
lemma Sn_generated_conj_cycle_transpose:
  fixes q :: "nat \<Rightarrow> nat" and a b :: nat
  assumes q: "q \<in> Sn p" and a: "a < p" and b: "b < p" and ab: "a \<noteq> b"
  shows "Group.generate (Sn p) (\<circ>) id
           {q \<circ> ncycle p \<circ> inv q, q \<circ> Transposition.transpose a b \<circ> inv q} = Sn p"
proof -
  interpret G: Group "Sn p" "(\<circ>)" id by (rule Group_Sn)
  have qp: "q permutes {0..<p}" using q by (simp add: Sn_def)
  define S where "S = {ncycle p, Transposition.transpose a b}"
  have genS: "G.generate S = Sn p"
    unfolding S_def by (rule Sn_generated_ncycle_transpose[OF a b ab])
  have SsubSn: "S \<subseteq> Sn p"
    unfolding S_def using ncycle_in_Sn a b by (auto simp: Sn_def permutes_swap_id)
  have "G.conjugation q ` (S \<inter> Sn p)
          = {q \<circ> ncycle p \<circ> inv q, q \<circ> Transposition.transpose a b \<circ> inv q}"
    using G.conjugation_def S_def Sn_inverse_eq SsubSn q by auto
  then have "G.generate {q \<circ> ncycle p \<circ> inv q, q \<circ> Transposition.transpose a b \<circ> inv q}
           = G.conjugation q ` G.generate S"
    using G.conjugation_generate_eq[OF q] by simp
  also have "\<dots> = Sn p" using G.conjugation_bij[OF q] by (simp add: genS bij_betw_imp_surj_on)
  finally show ?thesis .
qed


subsection \<open>An order-\<open>p\<close> element of \<open>S\<^sub>p\<close> is a \<open>p\<close>-cycle\<close>

text \<open>The combinatorial counterpart of the previous result: every element of @{term "Sn p"}
  of order @{term p} (for @{term p} prime) is conjugate to the standard cycle, hence is itself
  a @{term p}-cycle.  Together with @{thm [source] Sn_generated_conj_cycle_transpose} this lets
  Cauchy's theorem (which only yields \<^emph>\<open>some\<close> order-@{term p} element) feed the generation
  argument for the quintic.\<close>

text \<open>Iterating @{term g} is periodic with period dividing @{term n} once @{term "g ^^ n = id"}.\<close>
lemma funpow_mod_period:
  assumes "(g ^^ n) = id"
  shows "(g ^^ (k mod n)) = (g ^^ k)"
  by (metis (no_types, lifting) ext assms funpow_mod_eq id_apply)

text \<open>If @{term g} has order @{term p} (prime) and moves @{term x}, then no smaller positive
  power fixes @{term x}: the only powers fixing @{term x} are the multiples of @{term p}.\<close>
lemma cycle_period_prime:
  assumes p: "prime p" and gp: "(g ^^ p) = id" and gx: "g x \<noteq> x"
    and d: "(g ^^ d) x = x"
  shows "d mod p = 0"
proof (rule ccontr)
  assume "d mod p \<noteq> 0"
  have dmod: "(g ^^ (d mod p)) x = x"
    using funpow_mod_period[OF gp, of d] d by simp
  obtain k where k: "(k * (d mod p)) mod p = 1"
    using \<open>d mod p \<noteq> 0\<close> p stride_reaches_one
    by (meson mod_less_divisor not_gr_zero prime_gt_0_nat)
  then have "(g ^^ ((k * (d mod p)) mod p)) x = x"
    using funpow_mod_period[OF gp] by (metis dmod funpow_mod_eq mod_mult_self2_is_0 mod_self)
  with gx show False using k by simp
qed

text \<open>The conjugator: the map sending @{term i} to @{term "(g ^^ i) x"} on @{term "{0..<p}"}
  and fixing the rest.\<close>
definition qmap :: "(nat \<Rightarrow> nat) \<Rightarrow> nat \<Rightarrow> nat \<Rightarrow> nat"
  where "qmap g x i = (if i < p then (g ^^ i) x else i)"

context
  fixes g :: "nat \<Rightarrow> nat" and x :: nat
  assumes gSn: "g \<in> Sn p" and gp: "(g ^^ p) = id"
    and gx: "g x \<noteq> x" and xp: "x < p"
begin

lemma g_funpow_lt: "i < p \<Longrightarrow> (g ^^ i) x < p"
  using gSn permutes_in_funpow_image xp by (fastforce simp: Sn_def permutes_funpow)

lemma qmap_inj_aux:
  assumes ij: "i < p" "j < p" "i \<le> j" and eq: "(g ^^ i) x = (g ^^ j) x"
  shows "i = j"
proof -
  have bij_i: "bij (g ^^ i)" using Sn_def gSn permutes_bij by fastforce
  have "(g ^^ i) x = (g ^^ i) ((g ^^ (j - i)) x)"
    by (metis Sn_iff bij_betw_def eq funpow_diff gSn ij(3) permutes_bij)
  then have "(j - i) mod p = 0" 
    using cycle_period_prime[OF p gp gx] by (simp add: bij_i bij_is_inj inj_eq)
  then show "i = j" using ij(3)
    using ij(2) by auto
qed

lemma qmap_inj_on: "inj_on (qmap g x) {0..<p}"
proof (rule inj_onI)
  fix i j assume "i \<in> {0..<p}" "j \<in> {0..<p}" "qmap g x i = qmap g x j"
  then have "i < p" "j < p" "(g ^^ i) x = (g ^^ j) x"
    by (auto simp: qmap_def)
  then show "i = j"
    by (metis nat_le_linear qmap_inj_aux)
qed

lemma qmap_image: "qmap g x ` {0..<p} = {0..<p}"
proof (rule endo_inj_surj)
  show "finite {0..<p}" by simp
  show "qmap g x ` {0..<p} \<subseteq> {0..<p}" using g_funpow_lt by (auto simp: qmap_def)
  show "inj_on (qmap g x) {0..<p}" by (rule qmap_inj_on)
qed

lemma qmap_permutes: "qmap g x permutes {0..<p}"
  using qmap_inj_on qmap_image
  by (intro bij_imp_permutes) (auto simp: bij_betw_def qmap_def)

lemma qmap_in_Sn: "qmap g x \<in> Sn p"
  using qmap_permutes by (simp add: Sn_def)

lemma g_qmap_eq:
  assumes "i < p"
  shows "g (qmap g x i) = qmap g x (ncycle p i)"
  using funpow_mod_period[OF gp, of "Suc i"] assms by (simp add: qmap_def ncycle_def)

lemma g_comp_qmap: "g \<circ> qmap g x = qmap g x \<circ> ncycle p"
  using g_qmap_eq gSn by (auto simp: Sn_def permutes_def ncycle_def qmap_def)

lemma g_conj_ncycle: "g = qmap g x \<circ> ncycle p \<circ> inv (qmap g x)"
  by (metis comp_assoc comp_id g_comp_qmap permutes_inv_o(1) qmap_permutes)

end

theorem order_p_elt_conj_ncycle:
  fixes g :: "nat \<Rightarrow> nat"
  assumes gSn: "g \<in> Sn p" and gp: "(g ^^ p) = id" and gne: "g \<noteq> id"
  shows "\<exists>q \<in> Sn p. g = q \<circ> ncycle p \<circ> inv q"
proof -
  obtain x where x: "g x \<noteq> x" using gne by (auto simp: fun_eq_iff)
  with gSn have xp: "x < p"
    by (auto simp: Sn_def permutes_def)
  show ?thesis
    using gSn g_conj_ncycle gp qmap_in_Sn x xp by blast
qed

text \<open>The same conclusion phrased through the group's @{const Monoid.element_order}: an element
  of @{term "Sn p"} of order @{term p} is a conjugate of the standard cycle.\<close>
theorem order_p_elt_conj_ncycle_order:
  fixes g :: "nat \<Rightarrow> nat"
  assumes gSn: "g \<in> Sn p"
    and ord: "Monoid.element_order (\<circ>) id g = p"
  shows "\<exists>q \<in> Sn p. g = q \<circ> ncycle p \<circ> inv q"
proof -
  have gp: "(g ^^ p) = id"
    using G.power_element_order Sn_power_funpow finite_Sn gSn ord by force
  have gne: "g \<noteq> id"
    using ord p by force
  show ?thesis by (rule order_p_elt_conj_ncycle[OF gSn gp gne])
qed

end (* p::nat *)

end
