#!/usr/bin/env perl
#
# Author: Sascha Boehme, TU Muenchen
#
# Compute MD5 hash key.

use strict;
use warnings;
use Digest::MD5;


# argument

my $file = $ARGV[0];


# compute MD5 hash key

my $md5 = Digest::MD5->new;
open FILE, "<$file" or die "ERROR: Failed to open '$file' ($!)";
$md5->addfile(*FILE);
close FILE;
print $md5->b64digest . "\n";

