#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle_hol.pdf "HOL"
"$ISABELLE_TOOL" logo -o isabelle_hol.eps "HOL"

cp "$ISABELLE_HOME/doc-src/proof.sty" .
cp "$ISABELLE_HOME/doc-src/ttbox.sty" .
cp "$ISABELLE_HOME/doc-src/manual.bib" .

cp "$ISABELLE_HOME/doc-src/TutorialI/ToyList/ToyList1" .
cp "$ISABELLE_HOME/doc-src/TutorialI/ToyList/ToyList2" .

"$ISABELLE_TOOL" latex -o sty
cp "$ISABELLE_HOME/doc-src/pdfsetup.sty" .

"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o bbl
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o "$FORMAT"
./isa-index root
[ -f root.out ] && "$ISABELLE_HOME/doc-src/fixbookmarks" root.out
"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o "$FORMAT"
