#!/usr/bin/env bash
#
# DESCRIPTION: build full Isabelle distribution from repository

unset CDPATH
THIS="$(cd "$(dirname "$0")"; pwd)"

"$THIS/../bin/isabelle" scala_build -q || exit $?
"$THIS/../bin/isabelle_java" isabelle.Build_Release "$@"
