#!/usr/bin/env bash
#
# DESCRIPTION: build full Isabelle distribution from repository

unset CDPATH
THIS="$(cd "$(dirname "$0")"; pwd)"

"$THIS/build" jars || exit $?
exec "$THIS/../bin/isabelle_java" isabelle.Build_Release "$@"
