#!/usr/bin/env bash
#
# DESCRIPTION: build history versions from another repository clone

unset CDPATH
THIS="$(cd "$(dirname "$0")"; pwd)"

"$THIS/build" jars > /dev/null || exit $?
exec "$THIS/../bin/isabelle_java" isabelle.Build_History "$@"
