#!/usr/bin/env bash
#
# $Id$
#
# Mirrors the Isabelle home page (those directly on http://isabelle.in.tum.de)
# It does *not* mirror the Isabelle distribution pages and downloads. There
# is a separate utility (mirror-dist) for that.
#
# Usage: mirror-main
#

HOST=$(hostname)

case ${HOST} in
  sunbroy51)
    DEST=/home/html/isabelle/html-data
    ;;
  *.cl.cam.ac.uk)
    USER=paulson
    DEST=/anfs/www/html/Research/HVG/Isabelle
    ;;
  *)
    echo "Unknown destination directory for ${HOST}"
    exit 2
    ;;
esac

rsync --rsh ssh --rsync-path /usr/local/dist/bin/rsync -va \
  $USER@sunbroy2.informatik.tu-muenchen.de:/usr/proj/isabelle-repository/www/. $DEST/.
