#!/bin/bash
#
# $Id$
#

HOST=$(hostname)

case ${HOST} in
  sunbroy51)
    DEST=/home/html/isabelle/html-data
    ;;
  *.cl.cam.ac.uk)
    USER=paulson
    DEST=/anfs/www/html/Research/HVG/Isabelle
    ;;
  *)
    echo "Unknown destination directory for ${HOST}"
    exit 2
    ;;
esac

rsync --rsh ssh --rsync-path /usr/local/dist/bin/rsync -va \
  $USER@sunbroy1.informatik.tu-muenchen.de:/usr/proj/isabelle-repository/www/. $DEST/.
