#!/bin/bash
#
# $Id$
#

HOST=$(hostname)

case  ${HOST} in
  *.cl.cam.ac.uk)
    USER=paulson
    DEST=/anfs/www/html/Research/HVG/Isabelle/dist
    ;;
  sunbroy79)
    DEST=/tmp/isabelle-dist
    ;;
  *)
    echo "Unknown destination directory for ${HOST}"
    exit 2
    ;;
esac

rsync --rsh ssh --rsync-path /usr/local/dist/bin/rsync -va \
  $USER@sunbroy30.informatik.tu-muenchen.de:/home/html/isabelle/html-data/dist/. $DEST/.
