#!/usr/bin/env bash
#
# $Id$
# Author: Makarius
#
# DESCRIPTION: Update standard keyword files.

cd "$(isatool getenv -b ISABELLE_HOME)"/etc
LOG="$(isatool getenv -b ISABELLE_OUTPUT)"/log

isatool keywords "$LOG/Pure.gz" "$LOG/Pure-ProofGeneral.gz" "$LOG/HOL.gz" "$LOG/HOLCF.gz" "$LOG/IOA.gz"
isatool keywords -k HOL-Nominal "$LOG/Pure.gz" "$LOG/Pure-ProofGeneral.gz" "$LOG/HOL.gz" "$LOG/HOL-Nominal.gz"
isatool keywords -k ZF "$LOG/Pure.gz" "$LOG/Pure-ProofGeneral.gz" "$LOG/FOL.gz" "$LOG/ZF.gz"

