#
# $Id$
#

## targets

default: dvi

## dependencies

dvi:
	cd Isar/document; make dvi

pdf:
	cd Isar/document; make pdf

clean:
	cd Isar/document; make clean

mrproper:
	rm -f *.pdf *.dvi
	cd Isar/document; make mrproper
