#!/usr/bin/env bash

set -e

FORMAT="$1"

isabelle latex -o "$FORMAT"

if [ -f root.bib ]
then
  isabelle latex -o bbl
  isabelle latex -o "$FORMAT"
fi

isabelle latex -o "$FORMAT"

if [ -f root.idx ]
then
  "$ISABELLE_HOME/src/Doc/sedindex" root
  isabelle latex -o "$FORMAT"
fi
