#!/usr/bin/env bash

set -e

FORMAT="$1"

cp "$ISABELLE_HOME/src/Doc/pdfsetup.sty" .

isabelle latex -o "$FORMAT"
isabelle latex -o bbl
[ -f root.idx ] && "$ISABELLE_HOME/src/Doc/sedindex" root
isabelle latex -o "$FORMAT"
[ -f root.out ] && "$ISABELLE_HOME/src/Doc/fixbookmarks" root.out
isabelle latex -o "$FORMAT"
