#!/bin/bash

set -e

FORMAT="$1"

"$ISABELLE_TOOL" latex -o sty
cp "$ISABELLE_HOME/doc-src/pdfsetup.sty" .

"$ISABELLE_TOOL" latex -o "$FORMAT"
"$ISABELLE_TOOL" latex -o bbl
[ -f root.idx ] && "$ISABELLE_HOME/doc-src/sedindex" root
"$ISABELLE_TOOL" latex -o "$FORMAT"
[ -f root.out ] && "$ISABELLE_HOME/doc-src/fixbookmarks" root.out
"$ISABELLE_TOOL" latex -o "$FORMAT"

