#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo Nitpick

cp "$ISABELLE_HOME/src/Doc/iman.sty" .
cp "$ISABELLE_HOME/src/Doc/manual.bib" .

"$ISABELLE_HOME/src/Doc/prepare_document" "$FORMAT"

