#!/bin/bash
# $Id$

JEDIT_HOME="$HOME/lib/jedit/current"
PLUGINS="$HOME/.jedit/jars"


rm -rf build/ && mkdir -p build
rm -f ../isabelle.jar

scalac -d build \
  -cp $JEDIT_HOME/jedit.jar:$PLUGINS/SideKick.jar:$PLUGINS/ErrorList.jar:$PLUGINS/Console.jar:../../classes/Pure.jar \
  isabelle/IsabellePlugin.scala \
  isabelle/IsabelleDock.scala \
  isabelle/IsabelleParser.scala \
&& (
  cp *.xml *.props build/
  cd build
  jar cf ../../isabelle.jar .
)

rm -rf build/
