include Makefile
bin/mosml/Makefile.src:
	mkdir -p `dirname $@`
	echo > $@
refresh_FILES:
	echo $(POLYML_SRC) | \
	sed "s/src\/PortablePolyml/PortableIsabelle/g" | \
	sed "s/ src\/Tptp\.s[a-z][a-z]//g" | \
	sed "s/ src\/Options\.s[a-z][a-z]//g" \
	> FILES
