include Makefile
bin/mosml/Makefile.src:
	mkdir -p `dirname $@`
	echo > $@
refresh_FILES:
	echo $(POLYML_SRC) | \
	sed "s/src\///g" | \
	sed "s/ Tptp\.s[a-z][a-z]//g" | \
	sed "s/ Options\.s[a-z][a-z]//g" \
	> FILES
