#!/usr/bin/env bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo Isar
./showsymbols "$ISABELLE_HOME/lib/texinputs/isabellesym.sty" > syms.tex
"$ISABELLE_HOME/src/Doc/prepare_document" "$FORMAT"

