#!/usr/bin/env perl

print "\\begin{supertabular}{ll\@{\\qquad}ll}\n";

$eol = "&";

while (<ARGV>) {
    if (m/^\\newcommand\{\\isasym([A-Za-z]+)\}/) {
        print "\\verb,\\<$1>, & {\\isasym$1} $eol\n";
        if ("$eol" eq "&") {
            $eol = "\\\\";
        } else {
            $eol = "&";
        }
    }
}

if ("$eol" eq "\\\\") {
    print "$eol\n";
}

print "\\end{supertabular}\n";

