#!/usr/bin/env bash
#
# Multi-platform build script

unset CDPATH
THIS="$(cd "$(dirname "$0")"; pwd)"
PRG="$(basename "$0")"


# diagnostics

function usage()
{
  echo
  echo "Usage: $PRG TARGET"
  echo
  exit 1
}

function fail()
{
  echo "$1" >&2
  exit 2
}


# command line args

[ "$#" -eq 0 ] && usage
TARGET="$1"; shift

[ "$#" -eq 0 ] || usage


# main

mkdir -p "$TARGET"

case "$TARGET" in
  arm64-linux)
    cc -Wall bash_process.c -o "$TARGET/bash_process"
    ;;
  x86_64-linux | x86_64-darwin)
    cc -Wall -m64 bash_process.c -o "$TARGET/bash_process"
    ;;
  x86_64-cygwin)
    cc -Wall bash_process.c -o "$TARGET/bash_process.exe"
    ;;
  *)
    fail "Bad target platform: \"$TARGET\""
    ;;
esac
