#!/bin/dash

PATH=/bin

FILE_LIST="$(mktemp)"

CONTRIB="$(cygpath -u "$(cygpath -w /)\..")"

for DIR in "$CONTRIB/polyml"*
do
  find "$DIR" -name "*.dll" >> "$FILE_LIST"
done

dash /bin/rebaseall -T "$FILE_LIST"

rm -f "$FILE_LIST"

