#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle_hol.pdf "HOL"
"$ISABELLE_TOOL" logo -o isabelle_hol.eps "HOL"

cp "$ISABELLE_HOME/doc-src/iman.sty" .
cp "$ISABELLE_HOME/doc-src/extra.sty" .
cp "$ISABELLE_HOME/doc-src/ttbox.sty" .
cp "$ISABELLE_HOME/doc-src/proof.sty" .
cp "$ISABELLE_HOME/doc-src/manual.bib" .
cp "$ISABELLE_HOME/doc-src/Logics/document/syntax.tex" .

"$ISABELLE_HOME/doc-src/prepare_document" "$FORMAT"

