#!/bin/bash
# set the keyboard modifiers used by Isabelle 8bit package

###############################################
# The variables SUPER_L and HYPER_R are automatically configured 
# by the Master Makefile. You should configure them there.
###############################################

#keycode for Super_L (= left Meta)
SUPER_L=127

#keycode for Hyper_R (= right Meta)
HYPER_R=129


# define modifier keys for Isabelle keystrokes
# map super-key onto left Meta key
xmodmap -e "keycode $SUPER_L = Super_L"

# map hyper-key onto right Meta key
xmodmap -e "keycode $HYPER_R = Hyper_R"

# define new keysyms to generate Mod1 and Mod5
xmodmap -e "clear Mod1" -e "add Mod1 = Super_L"
xmodmap -e "clear Mod5" -e "add Mod5 = Hyper_R"

# make bash, axe, and vim accept 8 bit input 
#export LANG=iso_8859_1
export LESSCHARSET=latin1
export INPUTRC=$ISABELLE8BIT/keyboard/bash.inputrc
