#!/bin/bash
#
# $Id$
# Author: Markus Wenzel, TU Muenchen
# License: GPL (GNU GENERAL PUBLIC LICENSE)
#
# DESCRIPTION: Isabelle graph browser


PRG="$(basename "$0")"

function usage()
{
  echo
  echo "Usage: $PRG [OPTIONS] [GRAPHFILE]"
  echo
  echo "  Options are:"
  echo "    -d           delete file after use"
  echo
  exit 1
}

## process command line

# options

DELETE=""

while getopts "d" OPT
do
  case "$OPT" in
    d)
      DELETE=true
      ;;
    \?)
      usage
      ;;
  esac
done

shift $(($OPTIND - 1))


# args

GRAPHFILE=""
[ "$#" -gt 0 ] && { GRAPHFILE="$1"; shift; }
[ "$#" -ne 0 ] && usage


## main

export CLASSPATH="$ISABELLE_HOME/lib/browser"
if [ -z "$GRAPHFILE" ]; then
  cd "$ISABELLE_BROWSER_INFO"
  exec java GraphBrowser.GraphBrowser
else
  java GraphBrowser.GraphBrowser "$GRAPHFILE"
  [ -n "$DELETE" ] && rm -f "$GRAPHFILE"
fi

