#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: build and manage Isabelle sessions

isabelle_admin_build jars || exit $?

case "$ISABELLE_JAVA_PLATFORM" in
  x86-*)
    ISABELLE_BUILD_JAVA_OPTIONS="$ISABELLE_BUILD_JAVA_OPTIONS32"
    ;;
  x86_64-*)
    ISABELLE_BUILD_JAVA_OPTIONS="$ISABELLE_BUILD_JAVA_OPTIONS64"
    ;;
esac

eval "declare -a JAVA_ARGS=($ISABELLE_BUILD_JAVA_OPTIONS)"

exec isabelle java "${JAVA_ARGS[@]}" isabelle.Build "$@"
