#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: run the Electron framework within the Isabelle environment

if [ -z "$ISABELLE_VSCODIUM_ELECTRON" ]; then
  echo '*** Undefined $ISABELLE_VSCODIUM_ELECTRON: missing "vscodium" component'
  exit 2
else
  exec "$ISABELLE_VSCODIUM_ELECTRON" "$@"
fi
