#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: Proof General / Emacs interface wrapper


## diagnostics

function fail()
{
  echo "$1" >&2
  exit 2
}


## main

[ -z "$PROOFGENERAL_HOME" ] && fail "Missing Proof General installation (PROOFGENERAL_HOME)"

INTERFACE="$PROOFGENERAL_HOME/isar/interface"
[ ! -x "$INTERFACE" ] && fail "Bad interface script: \"$INTERFACE\""

#legacy settings
export ISABELLE="$ISABELLE_PROCESS"
export ISATOOL="$ISABELLE_TOOL"

exec "$INTERFACE" "$@"
