#!/bin/bash
#
# $Id$
#
# DESCRIPTION: expand shorthand goal commands


PRG=$(basename $0)

function usage()
{
  echo
  echo "Usage: $PRG [FILES|DIRS...]"
  echo
  echo "  Recursively find .ML files, expand shorthand goal commands.  Also"
  echo "  contracts uses of resolve_tac, dresolve_tac, eresolve_tac,"
  echo "  forward_tac, rewrite_goals_tac on 1-element lists; furthermore expands"
  echo "  tabs, which are forbidden in SML string constants."
  echo
  echo "  Renames old versions of files by appending \"~~\"."
  echo
  exit 1
}


## process command line

[ $# -eq 0 -o "$1" = "-?" ] && usage

SPECS="$@"; shift $#


## main

#set by configure
AUTO_PERL=perl

find $SPECS -name \*.ML -print | xargs $AUTO_PERL -w $ISABELLE_HOME/lib/scripts/expandshort.pl
