#!/bin/bash
#
# $Id$
#
# DESCRIPTION: expand shorthand goal commands


PRG=$(basename $0)

function usage()
{
  echo
  echo "Usage: $PRG [FILES|DIRS...]"
  echo
  echo "  Recursively find .ML files, expand shorthand goal commands."
  echo "  Also contracts uses of resolve_tac, dresolve_tac, eresolve_tac,"
  echo "  rewrite_goals_tac on 1-element lists; furthermore expands tabs,"
  echo "  since they are now forbidden in ML string constants."
  echo
  echo "  Renames old versions of files by appending \"~~\"."
  echo
  exit 1
}


## process command line

[ $# -eq 0 -o "$1" = "-?" ] && usage

SPECS="$@"; shift $#


## main

find $SPECS -name \*.ML -print | xargs perl -w $ISABELLE_HOME/lib/scripts/expandshort.pl
