#!/bin/bash
#
# $Id$
# Author: Markus Wenzel, TU Muenchen
# License: GPL (GNU GENERAL PUBLIC LICENSE)
#
# DESCRIPTION: collect heap names from ISABELLE_PATH


PRG=$(basename "$0")

function usage()
{
  echo
  echo "Usage: $PRG"
  echo
  echo "  Collect heap file names from ISABELLE_PATH."
  echo
  exit 1
}


## main

[ "$#" -ne 0 ] && usage


LOGICS=""

ORIG_IFS="$IFS"
IFS=":"
for DIR in $ISABELLE_PATH
do
  DIR="$DIR/$ML_IDENTIFIER"
  for FILE in "$DIR"/*
  do
    if [ -f "$FILE" ]; then
      NAME=$(basename "$FILE")
      LOGICS="$LOGICS $NAME"
    fi
  done
done
IFS="$ORIG_IFS"

echo $({ for L in $LOGICS; do echo "$L"; done; } | sort | uniq)
