#!/usr/bin/env bash
#
# Author: Markus Wenzel, TU Muenchen
#
# DESCRIPTION: collect heap names from ISABELLE_PATH


PRG=$(basename "$0")

function usage()
{
  echo
  echo "Usage: isabelle $PRG"
  echo
  echo "  Collect heap file names from ISABELLE_PATH."
  echo
  exit 1
}


## main

[ "$#" -ne 0 ] && usage

declare -a LOGICS=()
declare -a ISABELLE_PATHS=()

splitarray ":" "$ISABELLE_PATH"; ISABELLE_PATHS=("${SPLITARRAY[@]}")

for DIR in "${ISABELLE_PATHS[@]}"
do
  DIR="$DIR/$ML_IDENTIFIER"
  for FILE in "$DIR"/*
  do
    if [ -f "$FILE" ]; then
      NAME=$(basename "$FILE")
      LOGICS["${#LOGICS[@]}"]="$NAME"
    fi
  done
done

echo $({ for L in "${LOGICS[@]}"; do echo "$L"; done; } | sort | uniq)
