#!/bin/bash
#
# $Id$
#
# DESCRIPTION: replace goal(w) commands by implicit versions Goal(w)


## diagnostics

PRG=$(basename $0)

function usage()
{
  echo
  echo "Usage: $PRG [FILES|DIRS...]"
  echo
  echo "  Recursively find .ML files, replacing goal(w)"
  echo "  commands by implicit versions Goal(w)"
  echo
  echo "  Renames old versions of FILES by appending \"~~\"."
  echo
  exit 1
}


## process command line

[ $# -eq 0 -o "$1" = "-?" ] && usage

SPECS="$@"; shift $#


## main

find $SPECS -name \*.ML -print | xargs perl -w $ISABELLE_HOME/lib/scripts/fixgoal.pl
