#!/usr/bin/env bash
#
# $Id$
# Author: Florian Haftmann, TUM
#
# DESCRIPTION: turn Isar theory headers into imports-uses-begin format


## diagnostics

PRG="$(basename "$0")"

function usage()
{
  echo
  echo "Usage: $PRG [FILES|DIRS...]"
  echo
  echo "  Recursively find .thy files, turning Isar theory headers into"
  echo "  imports-uses-begin format."
  echo
  echo "  Renames old versions of FILES by appending \"~~\"."
  echo
  exit 1
}


## process command line

[ "$#" -eq 0 -o "$1" = "-?" ] && usage

SPECS="$@"; shift "$#"


## main

#set by configure
AUTO_PERL=perl

find $SPECS -name \*.thy -print | \
  xargs "$AUTO_PERL" -w "$ISABELLE_HOME/lib/scripts/fixheaders.pl"
