#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: invoke Glasgow Haskell Compiler within the Isabelle environment

if [ -d "$ISABELLE_STACK_ROOT" ]; then
  isabelle_stack ghc -- "$@"
else
  exit 127
fi

