#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: setup Glasgow Haskell Compiler setup via Stack

set -e

isabelle_stack setup --resolver "$ISABELLE_STACK_RESOLVER" "$ISABELLE_GHC_VERSION"
isabelle_stack ghci --ghci-options --version
echo -n "$(standard_path "$(isabelle_stack path --programs)")" > "$ISABELLE_STACK_ROOT/ISABELLE_GHC_PROGRAMS"
