#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: setup Glasgow Haskell Compiler setup via Stack

set -e

isabelle_stack setup
isabelle_stack ghc -- --version
echo -n "$(standard_path "$(isabelle_stack path --programs)")" > "$ISABELLE_STACK_ROOT/ISABELLE_GHC_PROGRAMS"
