#!/bin/bash -norc
#
# $Id$
#
# DESCRIPTION: install Isabelle symbol fonts


PRG=$(basename $0)

function usage()
{
  echo
  echo "Usage: $PRG"
  echo
  echo "  Install the Isabelle symbol fonts into your X11 server."
  echo "  (May be savely called repeatedly.)"
  echo
  exit 1
}


## check for isabelle fonts

function checkfonts()
{
  RESULT=$(xlsfonts -fn "-isabelle-*-isabelle-0" 2>&1) || return 1

  case "$RESULT" in
    xlsfonts:*)
      return 1
      ;;
  esac

  return 0
}


## main

[ $# -ne 0 ] && usage

checkfonts || eval $ISABELLE_INSTALLFONTS
checkfonts || echo "WARNING: Isabelle fonts probably not installed correctly!" >&2
