#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: invoke Java within the Isabelle environment

CLASSPATH="$(jvmpath "$CLASSPATH")"

JAVA_EXE="${THIS_JAVA:-$ISABELLE_JAVA}"

if "$JAVA_EXE" -server >/dev/null 2>/dev/null; then
  SERVER="-server"
else
  SERVER=""
fi

exec "$JAVA_EXE" -Dfile.encoding=UTF-8 $SERVER \
  "-Djava.ext.dirs=$("$ISABELLE_HOME/lib/scripts/java_ext_dirs")" "$@"

