#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: invoke Java within the Isabelle environment

eval "declare -a JAVA_ARGS=($ISABELLE_JAVA_SYSTEM_OPTIONS)"

isabelle_setup_classpath

[ -n "$CLASSPATH" ] && classpath "$CLASSPATH"
unset CLASSPATH

isabelle_java java "${JAVA_ARGS[@]}" \
  -classpath "$(platform_path "$ISABELLE_CLASSPATH")" "$@"
