#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: monitor another Java process

isabelle java "-Dapple.awt.application.name=Java Monitor" --add-opens jdk.jconsole/sun.tools.jconsole=ALL-UNNAMED isabelle.Java_Monitor "$@"
