#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: invoke Java within the Isabelle environment

declare -a JAVA_ARGS; eval "JAVA_ARGS=($ISABELLE_JAVA_SYSTEM_OPTIONS)"

[ -n "$CLASSPATH" ] && classpath "$CLASSPATH"
unset CLASSPATH

isabelle_java java "${JAVA_ARGS[@]}" \
  -classpath "$(jvmpath "$ISABELLE_CLASSPATH")" "$@"

