#!/usr/bin/env bash
#
# $Id$
# Author: Makarius
#
# DESCRIPTION: Isabelle/jEdit interface wrapper


## diagnostics

function fail()
{
  echo "$1" >&2
  exit 2
}


## main

[ -z "$JEDIT_HOME" ] && fail "Missing Isabelle/jEdit installation (JEDIT_HOME)"

INTERFACE="$JEDIT_HOME/interface"
[ ! -x "$INTERFACE" ] && fail "Bad interface script: \"$INTERFACE\""

exec "$INTERFACE" "$@"
