#!/usr/bin/env bash
#
# $Id$
# Author: Markus Wenzel, TU Muenchen
# License: GPL (GNU GENERAL PUBLIC LICENSE)
#
# DESCRIPTION: Isabelle make utility


PRG="$(basename "$0")"

function usage()
{
  echo
  echo "Usage: $PRG [ARGS ...]"
  echo
  echo "  Compile the logic in current directory using IsaMakefile."
  echo "  ARGS are directly passed to the system make program."
  echo
  exit 1
}


## main

[ "$1" = "-?" ] && usage

exec make -f IsaMakefile "$@"
