#!/usr/bin/env bash
#
# $Id$
# Author: David Aspinall and Makarius Wenzel
#
# DESCRIPTION: prepare a session directory for PG-Eclipse

PRG="$(basename "$0")"

function usage()
{
  echo
  echo "Usage: isabelle $PRG NAME"
  echo
  echo "  Prepare a session directory for PG-Eclipse."
  exit 1
}

if [ "$#" -eq 1 ]; then
  NAME="$1"; shift
else
  usage
fi

"$ISABELLE_TOOL" mkdir -b -q "$NAME"
( cd document; "$ISABELLE_TOOL" latex -o sty; )
