#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: invoke OCaml within the Isabelle environment

if [ -d "$ISABELLE_OPAM_ROOT" -a -n "$ISABELLE_OCAML" ]
then
  isabelle_opam config exec --switch "$ISABELLE_OCAML_VERSION" -- ocaml "$@"
else
  echo "Cannot execute ocaml: missing Isabelle OCaml setup" >&2
  exit 127
fi
