#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: invoke OCaml compiler within the Isabelle environment

if [ -d "$ISABELLE_OPAM_ROOT" -a -n "$ISABELLE_OCAMLC" ]
then
  isabelle_opam config exec --switch "$ISABELLE_OCAML_VERSION" -- ocamlc "$@"
else
  echo "Cannot execute ocamlc: missing Isabelle OCaml setup" >&2
  exit 127
fi
