#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: setup OCaml via OPAM

if [ -d "$ISABELLE_OPAM_ROOT" ]
then
  isabelle_opam switch "$ISABELLE_OCAML_VERSION"
else
  isabelle_opam init --no-setup --compiler="$ISABELLE_OCAML_VERSION"
fi
