#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: setup OCaml via OPAM

set -e

if [ -e "$ISABELLE_OPAM_ROOT/config" ]
then
  isabelle_opam switch create "ocaml-base-compiler.$ISABELLE_OCAML_VERSION"
else
  isabelle_opam init --disable-sandboxing --no-setup --compiler="ocaml-base-compiler.$ISABELLE_OCAML_VERSION"
fi

isabelle_opam install zarith -y
