#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: raw ML process (batch mode)

isabelle_admin_build jars || exit $?

case "$ISABELLE_JAVA_PLATFORM" in
  x86-*)
    ISABELLE_BUILD_JAVA_OPTIONS="$ISABELLE_BUILD_JAVA_OPTIONS32"
    ;;
  x86_64-*)
    ISABELLE_BUILD_JAVA_OPTIONS="$ISABELLE_BUILD_JAVA_OPTIONS64"
    ;;
esac

declare -a JAVA_ARGS; eval "JAVA_ARGS=($ISABELLE_BUILD_JAVA_OPTIONS)"

mkdir -p "$ISABELLE_TMP_PREFIX" || exit $?

isabelle java isabelle.ML_Process "$@"
