#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: invoke Scala within the Isabelle environment

isabelle scala_build || exit $?

classpath "$ISABELLE_SETUP_CLASSPATH"; unset ISABELLE_SETUP_CLASSPATH
classpath "$CLASSPATH"; export CLASSPATH=""

export jvm_cp_args="$(platform_path "$ISABELLE_CLASSPATH")"
export JAVA_OPTS="$ISABELLE_JAVA_SYSTEM_OPTIONS -J-Dscala.usejavacp=true"

case "$ISABELLE_PLATFORM_FAMILY" in
  windows*)
    export TERM=dumb
    ;;
fi

isabelle_scala scala $ISABELLE_SCALAC_OPTIONS "$@"
