#!/usr/bin/env bash
#
# Author: Markus Wenzel, TU Muenchen
#
# DESCRIPTION: remove unreadable symbol names from sources


## diagnostics

PRG="$(basename "$0")"

function usage()
{
  echo
  echo "Usage: isabelle $PRG [FILES|DIRS...]"
  echo
  echo "  Recursively find .thy/.ML files and remove symbols that are unreadably"
  echo "  in plain text (e.g. \<Longrightarrow>)."
  echo
  echo "  Note: this is an ad-hoc script; there is no systematic way to replace"
  echo "  symbols independently of the inner syntax of a theory!"
  echo
  echo "  Old versions of files are preserved by appending \"~~\"."
  echo
  exit 1
}


## process command line

[ "$#" -eq 0 -o "$1" = "-?" ] && usage

SPECS="$@"; shift "$#"


## main

find $SPECS \( -name \*.ML -o -name \*.thy \) -print0 | \
  xargs -0 "$ISABELLE_HOME/lib/scripts/unsymbolize"
