#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: expand old Isar command conflations 'hence' and 'thus'

isabelle_admin_build jars || exit $?

"$ISABELLE_TOOL" java isabelle.Update_Then "$@"
