#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: run Isabelle/VSCode using local VSCodium installation

export ISABELLE_VSCODE_SYMBOLS="$(platform_path "$ISABELLE_VSCODE_WORKSPACE/symbols.json")"

DIR="$(isabelle vscode_setup -C)" || exit "$?"
exec "$DIR/bin/codium" \
  --locale en-US \
  --user-data-dir "$(platform_path "$ISABELLE_VSCODE_SETTINGS"/user-data)" \
  --extensions-dir "$(platform_path "$ISABELLE_VSCODE_SETTINGS"/extensions)" \
  "$@"
