#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: run Isabelle/VSCode (requires "vscodium-X.YY.Z" component)

isabelle vscode_setup || exit "$?"

export ISABELLE_VSCODIUM_APP="$(platform_path "$ISABELLE_VSCODIUM_RESOURCES/vscodium")"

ELECTRON_RUN_AS_NODE=1 "$ISABELLE_VSCODIUM_ELECTRON" \
  "$(platform_path "$ISABELLE_VSCODIUM_RESOURCES/vscodium/out/cli.js")" \
  --ms-enable-electron-run-as-node --locale en-US \
  --user-data-dir "$(platform_path "$ISABELLE_VSCODE_SETTINGS"/user-data)" \
  --extensions-dir "$(platform_path "$ISABELLE_VSCODE_SETTINGS"/extensions)" \
  "$@"
