#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: run Isabelle/VSCode (requires "vscodium-X.YY.Z" component)

isabelle vscode_setup || exit "$?"

exec "$ISABELLE_VSCODIUM_HOME/vscodium" \
  --locale en-US \
  --user-data-dir "$(platform_path "$ISABELLE_VSCODE_SETTINGS"/user-data)" \
  --extensions-dir "$(platform_path "$ISABELLE_VSCODE_SETTINGS"/extensions)" \
  "$@"
