#!/usr/bin/env bash
#
# Author: Makarius
#
# Invoke ghc via "stack".

if [ -f "$ISABELLE_STACK_ROOT/ISABELLE_GHC_EXE-$ISABELLE_PLATFORM_FAMILY" ]
then
  isabelle_stack ghc -- "$@"
else
  echo "Cannot execute ghc: missing Isabelle GHC setup" >&2
  exit 127
fi
