#!/usr/bin/env bash
#
# Author: Makarius
#
# Invoke ghc via "stack".

if [ -d "$ISABELLE_STACK_ROOT" ]; then
  isabelle_stack ghc -- "$@"
else
  echo "Cannot execute ghc: missing Isabelle GHC setup" >&2
  exit 127
fi
