#!/bin/bash -norc
#
# $Id$
#
# Emacs / Isamode interface.
#
# TODO: isabelle fonts


## diagnostics

function fail()
{
  echo "$1" >&2
  exit 2
}


## main

exec emacs -name "isabelle" $ISABELLE_INTERFACE_OPTIONS -l "$ISAMODE_HOME/elisp/isa-site.el" -l "$ISABELLE_HOME_USER/etc/isa-settings.el" -l "$ISAMODE_HOME/elisp/isa-start.el"
