#!/bin/bash
#
# $Id$
#
# Emacs Isamode interface wrapper.


## diagnostics

PRG=$(basename $0)

function usage()
{
  echo
  echo "Usage: $PRG [OPTIONS]"
  echo
  echo "  Options are:"
  echo "    -g GEOM      main window geometry (default 80x20)"
  echo
  echo "  Starts Emacs and Isamode."
  echo
  exit 1
}

function fail()
{
  echo "$1" >&2
  exit 2
}


## process command line

# options

MAINGEOM="80x20"

while getopts "g:" OPT
do
  case "$OPT" in
    g)
      MAINGEOM="$OPTARG"
      ;;
    \?)
      usage
      ;;
  esac
done

shift $(($OPTIND - 1))


# args

[ $# != 0 ] && usage


## main

CMDS="-l $ISAMODE_HOME/elisp/isa-site.el"

for FILE in "$ISABELLE_HOME/etc/isa-settings.el" \
    "$ISABELLE_HOME_USER/etc/isa-settings.el"
do
  [ -f "$FILE" ] && CMDS="$CMDS -l $FILE"
done

CMDS="$CMDS -f isabelle"


$ISAMODE_EMACS -T "Isabelle" -geometry $MAINGEOM $CMDS
