#!/bin/bash
#
# $Id$
#
# Isabelle within an xterm.


## diagnostics

function fail()
{
  echo "$1"
  exit 2
}


## main

if [ -z "$ISABELLE_SYMBOLS" -o "$ISABELLE_SYMBOLS" = false ]; then
  exec xterm -T Isabelle -n Isabelle $ISABELLE_INTERFACE_OPTIONS -e isabelle "$@"
else
  isatool installfonts
  exec xterm -T Isabelle -n Isabelle $ISABELLE_INTERFACE_OPTIONS -fn isacr14 \
    -xrm "*fontMenu.Label: Isabelle fonts" \
    -xrm "*fontMenu*font1*Label: Large" \
    -xrm "*VT100*font1: isacb24" \
    -xrm "*fontMenu*font2*Label:" \
    -xrm "*VT100*font2:" \
    -xrm "*fontMenu*font3*Label:" \
    -xrm "*VT100*font3:" \
    -xrm "*fontMenu*font4*Label:" \
    -xrm "*VT100*font4:" \
    -xrm "*fontMenu*font5*Label:" \
    -xrm "*VT100*font5:" \
    -xrm "*fontMenu*font6*Label:" \
    -xrm "*VT100*font6:" \
    -e isabelle -e 'print_mode:=["symbols"];' "$@"
fi
