#!/bin/bash -norc
#
# $Id$
#
# Emacs / Isamode interface.
#
# TODO: isabelle fonts


## diagnostics

function fail()
{
  echo "$1" >&2
  exit 2
}


## main

if [ -f "$ISABELLE_HOME_USER/etc/isa-settings.el" ]; then
  USER_SETTINGS="--load $ISABELLE_HOME_USER/etc/isa-settings.el"
else
  USER_SETTINGS=""
fi

exec emacs -name "isabelle" \
  --no-init-file "$@" \
  --load "$ISAMODE_HOME/elisp/isa-site.el" \
  $USER_SETTINGS \
  --load $HOME/.emacs \
  --funcall isabelle
