#!/usr/bin/env bash
#
# Author: Makarius; Florian Haftmann
#
# Invoke command in OCaml environment setup by "opam".

if [ -e "$ISABELLE_OPAM_ROOT/config" ]
then
  isabelle_opam config exec --switch "$ISABELLE_OCAML_VERSION" -- "$@"
else
  echo "Cannot execute: missing Isabelle OCaml setup" >&2
  exit 127
fi
