#!/usr/bin/env bash
#
# Author: Makarius
#
# Invoke ocamlc via "opam".

if [ -d "$ISABELLE_OPAM_ROOT" ]
then
  isabelle_opam config exec --switch "$ISABELLE_OCAML_VERSION" -- ocamlc "$@"
else
  echo "Cannot execute ocamlc: missing Isabelle OCaml setup" >&2
  exit 127
fi
