#!/usr/bin/env bash
#
# Author: Jasmin Blanchette
#
# DESCRIPTION: TPTP FOF version of Nitpick


PRG="$(basename "$0")"

function usage() {
  echo
  echo "Usage: isabelle $PRG FILES"
  echo
  echo "  Runs Nitrox on a FOF or CNF TPTP problem."
  echo
  exit 1
}

[ "$#" -eq 0 -o "$1" = "-?" ] && usage

for FILE in "$@"
do
  (echo "theory Nitrox_Run imports Main begin" &&
   echo "ML {* Nitrox.pick_nits_in_fof_file \"$FILE\" *}" &&
   echo "end;") | isabelle tty
done
