#!/usr/bin/env bash
#
# Author: Jasmin Blanchette
#
# DESCRIPTION: TPTP FOF version of Nitpick


PRG="$(basename "$0")"

function usage() {
  echo
  echo "Usage: isabelle $PRG FILES"
  echo
  echo "  Runs Nitrox on a FOF or CNF TPTP problem."
  echo
  exit 1
}

[ "$#" -eq 0 -o "$1" = "-?" ] && usage

for FILE in "$@"
do
  echo "theory Scratch imports \"Nitpick\" begin ML {* Nitrox.pick_nits_in_fof_file \"$FILE\" *} end;" \
    > /tmp/$ISABELLE_TMP/Scratch.thy
  $ISABELLE_PROCESS -e "use_thy \"/tmp/$ISABELLE_TMP/Scratch\"; exit 1;"
done
