#
# $Id$
#
# IsaMakefile for PSV2002
#

SESSIONS = a1 a2 a3 a5 a6

## targets

default: sessions
sessions: $(SESSIONS)


## a1

a1: a1/generated/session.tex

a1/generated/session.tex: a1/ROOT.ML a1/*.thy
	isatool make

## a2

a2: a2/generated/session.tex

a2/generated/session.tex: a2/ROOT.ML a2/*.thy
	isatool make

## a3

a3: a3/generated/session.tex

a3/generated/session.tex: a3/ROOT.ML a3/*.thy
	isatool make

## a5

a5: a5/generated/session.tex

a5/generated/session.tex: a5/ROOT.ML a5/*.thy
	isatool make

## a6

a6: a6/generated/session.tex

a6/generated/session.tex: a6/ROOT.ML a6/*.thy
	isatool make
