#!/bin/bash

set -e

FORMAT="$1"
VARIANT="$2"

"$ISABELLE_TOOL" logo -o isabelle_isar.pdf "Isar"
"$ISABELLE_TOOL" logo -o isabelle_isar.eps "Isar"

cp "$ISABELLE_HOME/doc-src/iman.sty" .
cp "$ISABELLE_HOME/doc-src/extra.sty" .
cp "$ISABELLE_HOME/doc-src/isar.sty" .
cp "$ISABELLE_HOME/doc-src/ttbox.sty" .
cp "$ISABELLE_HOME/doc-src/isar.sty" .
cp "$ISABELLE_HOME/doc-src/underscore.sty" .
cp "$ISABELLE_HOME/doc-src/manual.bib" .

./showsymbols "$ISABELLE_HOME/lib/texinputs/isabellesym.sty" > syms.tex

"$ISABELLE_HOME/doc-src/prepare_document" "$FORMAT"

