#! /bin/sh
#Make entire system using Standard ML of New Jersey
#Pathnames will have to be modified for your site
ISABELLEBIN=/homes/`whoami`/bin
ISABELLECOMP=sml
export ISABELLEBIN ISABELLECOMP 
nohup make-all $*
