#! /bin/sh
#  xlisten -- start a program in one window and create a listener window
#     environment variable $LISTEN specifies the file name

#create the file!
set -e			#fail immediately upon errors
date > ${LISTEN?'Set this variable to the desired filename'}

xterm -geo 80x10+0+0 -T Listener -n Listener -e tail -f $LISTEN &
sleep 2
xterm -geo 80x60+0-0 -e teeinput $* &
